"""SCM upload formats: which spreadsheet containers the channel accepts.

The format belongs to the CUSTOMER, not to us. AutoCount's own "Purchase Order Listing With
Detail" export is legacy BIFF `.xls`, and a hard-coded pair of extensions meant telling
somebody to re-save 13 MB of order history by hand before the system would look at it.

Two claims are pinned here:

  * the container is told apart by its MAGIC BYTES, not by the filename, so a workbook
    renamed on the way through email still reads as what it actually is,
  * the accept list has ONE home (`SCM_UPLOAD_EXTENSIONS`), read by the route that refuses
    and served to the dialog that offers, so the two cannot drift apart - which is exactly
    how the browser came to reject a file the reader parses perfectly well.
"""
from __future__ import annotations

import io

import pytest
from openpyxl import Workbook

from app.services.scm.upload_intake import allowed_extensions
from app.services.scm.outstanding_reader import sheet_rows


def _xlsx_bytes(rows: list[list]) -> bytes:
    wb = Workbook()
    ws = wb.active
    for r in rows:
        ws.append(r)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def test_the_accept_list_has_one_home_and_includes_legacy_xls():
    allowed = allowed_extensions()
    assert ".xls" in allowed, "the AutoCount PO listing export is legacy .xls"
    assert ".xlsx" in allowed and ".xlsm" in allowed
    # Normalised with the dot, so a caller can use `str.endswith` directly.
    assert all(e.startswith(".") and e == e.lower() for e in allowed)


def test_a_zip_workbook_is_read_as_a_zip_workbook():
    data = _xlsx_bytes([["Doc No", "Item"], ["PO-1", "ABC"]])
    rows = list(sheet_rows(data))
    assert rows[0] == ("Doc No", "Item")
    assert rows[1] == ("PO-1", "ABC")


def test_the_container_is_decided_by_content_not_by_the_filename():
    """`sheet_rows` never sees a filename, which is the point.

    An `.xls` that is really a zip, or an `.xlsx` that is really BIFF, both happen in the
    wild - a rename costs nothing and is done constantly. Sniffing the first bytes means the
    reader is right in both cases, where trusting the extension is wrong in both.
    """
    data = _xlsx_bytes([["A"], ["B"]])
    assert data[:4] == b"PK\x03\x04"
    assert list(sheet_rows(data)) == [("A",), ("B",)]


def test_a_workbook_in_neither_container_fails_loudly():
    """Not a silent empty read: an empty sheet and an unreadable file are different answers,
    and the operator has to be told which one they have."""
    with pytest.raises(Exception):
        list(sheet_rows(b"this is not a spreadsheet at all"))


def test_a_legacy_xls_is_read_and_its_dates_arrive_as_dates():
    """The one conversion that cannot be deferred.

    In BIFF a date is a float with a cell TYPE saying it is a date, and the type is the only
    thing that separates 43832-the-date from 43832-the-quantity. Downstream sees values, not
    types, so the conversion happens while the type is still in scope or it becomes guesswork.

    Read from a REAL committed `.xls`, not one built at test time: writing BIFF needs a
    write-only library nobody maintains, and a fixture generated by the same process that
    reads it proves less than a file Excel actually produced.
    """
    import datetime
    from pathlib import Path

    data = (Path(__file__).parent / "fixtures" / "legacy_biff_sample.xls").read_bytes()
    assert data[:8] == b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1", "the fixture is not BIFF"

    rows = list(sheet_rows(data))
    assert rows[0][:4] == ("Doc No", "Item Code", "Qty", "Date")
    assert rows[1][0] == "202001-S0001"
    assert rows[1][2] == 450.0
    # The point of the test: a date, not the float 43832.
    assert rows[1][3] == datetime.date(2020, 1, 2)
