"""Lifting a document to the live status: the cases the defect suite does not pin.

`test_outstanding_import_po_defects.py` pins that a DRAFT purchase order named by the extract
is lifted and that the lift is reported. Three things it does not, all of which are how a
report like this goes wrong in practice:

* **the quiet case** - nothing was lifted, so `activated_documents` must be empty. A field
  that names a document whenever it is looked at is a field an operator learns to ignore.
* **preview and apply must say the SAME thing.** The whole module is built on "the commit
  writes exactly what the confirm screen showed", so a status change that only appears AFTER
  the write is a preview that lied about its side effects.
* **the sales-order path**, which shares every line of that code through `_Binding`. Its
  `write_status` and `live_statuses` are both `open` (what `scm.committed_v` counts), so the
  split must be invisible there: an open order is left alone, and a non-live one is lifted by
  the same rule rather than by a PO-shaped special case.

Same discipline as the rest of the suite: every code is generated by the test, the upload is
generated from those same codes, nothing is borrowed with `LIMIT 1`, and `pg_session()` rolls
everything back.
"""
from __future__ import annotations

import uuid

import pytest
from sqlalchemy import text

from app.models.order import SalesOrder
from app.models.procurement import PurchaseOrder
from app.services.scm import outstanding_import_service as svc
from app.services.scm.outstanding_reader import PO, SO
from tests._pg_fixture import pg_session
from tests.scm._outstanding_workbooks import (
    Codes,
    make_codes,
    po_week1,
    seed_catalogue,
    seed_suppliers,
    week1,
)


def _u() -> str:
    return str(uuid.uuid4())


@pytest.fixture()
def db():
    with pg_session() as s:
        yield s


@pytest.fixture()
def codes() -> Codes:
    return make_codes()


def _status(db, table: str, column: str, number: str) -> str:
    return db.execute(
        text(f"SELECT status FROM {table} WHERE {column} = :n"), {"n": number}
    ).scalar()


# --------------------------------------------------------------------------- #
# the quiet case: nothing lifted, nothing announced
# --------------------------------------------------------------------------- #

def test_a_first_import_activates_nothing_because_it_created_the_headers(db, codes):
    """A header this import CREATED was never a draft, so there is nothing to report.

    Reporting the documents it just created as "activated" would put two rows in front of the
    operator on every single first upload, and a warning that fires every time is a warning
    nobody reads.
    """
    seed_catalogue(db, codes, doc_type="outstanding_po")
    seed_suppliers(db, codes)

    out = svc.apply(db, po_week1(codes), PO)

    assert out["applied"]["added"] == 5
    assert out["activated_documents"] == []


def test_reapplying_the_same_file_activates_nothing(db, codes):
    """The headers are already live, so the second run has no status to change."""
    seed_catalogue(db, codes, doc_type="outstanding_po")
    seed_suppliers(db, codes)
    svc.apply(db, po_week1(codes), PO)

    again = svc.apply(db, po_week1(codes), PO)

    assert again["activated_documents"] == []
    assert _status(db, "purchase_orders", "po_number", codes.main_po) == "active"


def test_a_part_received_order_is_not_lifted_back_to_active(db, codes):
    """`received` is already live, so it must be left exactly as it is.

    The lift exists to rescue documents the readers ignore, not to normalise every status to
    one value: rewriting `received` as `active` would erase the fact that a goods receipt has
    been booked against the order.
    """
    seed_catalogue(db, codes, doc_type="outstanding_po")
    seed_suppliers(db, codes)
    svc.apply(db, po_week1(codes), PO)
    db.execute(text("UPDATE purchase_orders SET status = 'received' WHERE po_number = :n"),
               {"n": codes.main_po})
    db.flush()

    out = svc.apply(db, po_week1(codes), PO)

    assert out["activated_documents"] == []
    assert _status(db, "purchase_orders", "po_number", codes.main_po) == "received"


# --------------------------------------------------------------------------- #
# preview says the same thing as apply
# --------------------------------------------------------------------------- #

def test_the_preview_names_the_document_it_would_activate(db, codes):
    """The confirm screen has to show the side effect BEFORE it happens.

    Asserted against apply's own answer rather than against a literal, because the invariant is
    that the two agree - a test comparing each to a hardcoded list would still pass if they
    disagreed with each other.
    """
    seed_catalogue(db, codes, doc_type="outstanding_po")
    seed_suppliers(db, codes)
    db.add(PurchaseOrder(id=_u(), po_number=codes.main_po, status="draft"))
    db.flush()

    promised = svc.preview(db, po_week1(codes), PO)

    assert promised.activated_documents == [codes.main_po]
    assert promised.to_dict()["activated_documents"] == [codes.main_po]
    # And the preview really did write nothing: the draft is still a draft.
    assert _status(db, "purchase_orders", "po_number", codes.main_po) == "draft"

    assert svc.apply(db, po_week1(codes), PO)["activated_documents"] == \
        promised.activated_documents


# --------------------------------------------------------------------------- #
# the sales-order path takes the same rule, and is otherwise untouched
# --------------------------------------------------------------------------- #

def test_an_open_sales_order_is_untouched_by_the_live_status_split(db, codes):
    """`open` is both the sales book's write status and its only live one.

    Splitting the field in two must therefore be invisible here: the diff still pairs against
    an existing open order, and nothing is reported as activated.
    """
    seed_catalogue(db, codes, doc_type="outstanding_so")
    svc.apply(db, week1(codes), SO)

    again = svc.apply(db, week1(codes), SO)

    assert again["applied"] == {"added": 0, "updated": 0, "closed": 0, "unchanged": 5}
    assert again["activated_documents"] == []
    assert _status(db, "sales_orders", "so_number", codes.project_so) == "open"


def test_a_non_live_sales_order_named_by_the_extract_is_lifted_and_reported(db, codes):
    """One rule, both books: `scm.committed_v` counts `open` and nothing else.

    A cancelled or held sales order that the outstanding extract still lists is by definition
    still a commitment, and left in that status its lines land where `committed_v` cannot see
    them - the same silent no-op the purchase-order side had, with the sign flipped: demand
    that exists and is invisible reads as spare stock.
    """
    seed_catalogue(db, codes, doc_type="outstanding_so")
    db.add(SalesOrder(id=_u(), so_number=codes.project_so, status="cancelled"))
    db.flush()

    out = svc.apply(db, week1(codes), SO)

    assert out["activated_documents"] == [codes.project_so]
    assert _status(db, "sales_orders", "so_number", codes.project_so) == "open"
    # The lines are visible to the view the plan reads, which is the point of lifting it.
    assert float(db.execute(text(
        "SELECT COALESCE(SUM(cv.committed), 0) FROM scm.committed_v cv "
        "JOIN products p ON p.id = cv.product_id WHERE p.product_code = :c"
    ), {"c": codes.item_rl}).scalar()) == 207.0
