"""The rule engine: a rule is a set of picks, compiled here, and nobody types a pattern.

Plan: `PLAN-product-specs-non-technical-26sep.md` D5 (owner ruling, 26 Sep 2026, Q5 and
Q6: "if the rule engine is not simple enough to cover, then the engine is the problem").
Contract: `CONTRACT-product-specs-rule-engine.md`, sections 1 to 3. A stored rule is
`{"builder": {...}}` and nothing else (shipped rules also carry `"_seed": true`); the
matching fields are compiled from the builder at run time, so no stored rule holds a
regular expression and no screen can show one.

Five kinds, one matching rulebook for all of them (contract section 2):

  * words   - words in the text; sets the choice the person picked
  * number  - a number next to words (before, after, or between them)
  * size    - one number out of a size such as 1500 x 750 x 630, or the labelled one
  * code    - the product code contains / starts with / ends with some text
  * product - a fact already on the product: its category's class, what its name says
              it is, its length / width / height

`compile_builder` is mirrored line for line by `lib/ruleSentence.ts::compileBuilder` in
the frontend, escaping included, and both are pinned by one shared fixture
(`lib/__fixtures__/rule-builders.json`, regenerated by
`scripts/generate_rule_builder_fixture.py`). A save whose screen-compiled pattern
disagrees with this one is refused, so the pattern the engine runs is never something
the screen did not show.

This module is a leaf: it imports nothing from the other spec services, so derivation,
the registry and the API can all import it.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from typing import Any

KINDS = ("words", "number", "size", "code", "product")
LOOK_INS = ("any", "description", "flyer", "name")
CODE_MATCHES = ("contains", "starts_with", "ends_with")
FACTS = ("class", "name", "length", "width", "height")
SIZE_PICKS = (1, 2, 3, 4, "L", "W", "H")
# What a number written in another unit is multiplied by: the catalogue stores mm.
WRITTEN_IN_SCALE = {"centimetres": 10, "metres": 1000}

# The one key that is never a specification (#1286, D1).
BRAND_KEY = "brand"
BRAND_IS_NOT_A_SPEC = "Brand is not a specification. The product's brand is on its Details tab."

# Which text a rule reads when its builder does not say. Product class reads the product
# name without sizes and extras; everything else reads the description or the flyer.
DEFAULT_LOOK_IN_BY_KEY = {"class": "name"}


def default_look_in(spec_key: str | None) -> str:
    return DEFAULT_LOOK_IN_BY_KEY.get(spec_key or "", "any")


# --------------------------------------------------------------------------- #
# the compiler (contract section 2 and 2.1)
# --------------------------------------------------------------------------- #
# JavaScript's escape set, not `re.escape`: Python's also escapes `-`, `&`, `#` and
# whitespace, which would compile a pattern the browser never produces and refuse the
# save as a mismatch.
_JS_REGEX_SPECIALS = re.compile(r"[.*+?^${}()|[\]\\]")


def _escape(raw: str) -> str:
    return _JS_REGEX_SPECIALS.sub(lambda match: "\\" + match.group(0), raw or "")


def _phrase(phrase: str) -> str:
    """One phrase: "..." splits it into segments that may sit apart in one sentence,
    and inside a segment a space, a hyphen or nothing all count between the words.
    Each segment is bounded by letters only, so "LED" never matches inside "SEALED"."""
    segments = [part.strip() for part in str(phrase or "").upper().split("...")]
    compiled = []
    for segment in (part for part in segments if part):
        tokens = [_escape(token) for token in re.split(r"[\s-]+", segment) if token]
        compiled.append("(?<![A-Z])" + _GAP.join(tokens) + "(?![A-Z])")
    return "[^.]*?".join(compiled)


# A space, a hyphen or nothing, between the words of a phrase.
_GAP = r"[\s\-]*"


def _alternation(phrases: list[str]) -> str:
    return f"(?:{'|'.join(_phrase(p) for p in phrases)})"


_NUMBER = r"(\d+(?:\.\d+)?)"
# A number read BEFORE a word must stand on its own: a letter or digit touching it,
# directly or across a hyphen, means it is part of a code (the 1008 in SRTKS1008L).
_NUMBER_GUARD = r"(?<![A-Z0-9.])(?<![A-Z0-9]-)"

_SIZE_PART = r"(?:([LWHD])\s*)?(\d+(?:\.\d+)?)\s*(?:MM)?"
SIZE_PATTERN = (
    rf"{_SIZE_PART}\s*[X*]\s*{_SIZE_PART}"
    rf"(?:\s*[X*]\s*{_SIZE_PART})?"
    rf"(?:\s*[X*]\s*{_SIZE_PART})?"
)


def _words_pattern(words: list[str], at_end: bool) -> str:
    return _alternation(words) + (r"\s*$" if at_end else "")


def _number_pattern(before: list[str], after: list[str]) -> str:
    near = _alternation(before) if before else ""
    far = _alternation(after) if after else ""
    if after and before:
        return rf"{far}[\s\-:,]*{_NUMBER}[\s\-]*{near}(?![A-Z])"
    if after:
        return rf"{far}[\s\-:,]*{_NUMBER}"
    return rf"{_NUMBER_GUARD}{_NUMBER}[\s\-]*{near}(?![A-Z])"


def _skip_pattern(skip_after) -> str | None:
    if not skip_after:
        return None
    return rf"(?<![A-Z]){_alternation(list(skip_after))}[\s\-:,(]*$"


def compile_builder(builder: dict) -> dict:
    """The engine fields one builder compiles to (contract 2.1). Never raises.

    Mirrors `compileBuilder` in `lib/ruleSentence.ts` exactly, including for a builder
    that would not pass validation, so the two can be compared on any input.
    """
    builder = builder if isinstance(builder, dict) else {}
    kind = builder.get("kind")
    out: dict[str, Any] = {
        "kind": kind,
        "scope": None,
        "pattern": None,
        "capture": None,
        "skip": None,
        "scale": None,
        "min": None,
        "pick": None,
        "code_match": None,
        "texts": None,
        "fact": None,
    }
    if kind == "words":
        out.update(
            scope=builder.get("look_in"),
            pattern=_words_pattern(list(builder.get("words") or []), bool(builder.get("at_end"))),
            skip=_skip_pattern(builder.get("skip_after")),
        )
    elif kind == "number":
        written_in = builder.get("written_in")
        out.update(
            scope=builder.get("look_in"),
            pattern=_number_pattern(
                list(builder.get("before") or []), list(builder.get("after") or [])
            ),
            capture=1,
            skip=_skip_pattern(builder.get("skip_after")),
            scale=WRITTEN_IN_SCALE.get(written_in) if written_in else None,
            min=builder.get("ignore_below"),
        )
    elif kind == "size":
        out.update(scope=builder.get("look_in"), pattern=SIZE_PATTERN, pick=builder.get("pick"))
    elif kind == "code":
        out.update(
            scope="code",
            code_match=builder.get("code_match"),
            texts=[str(text).upper() for text in (builder.get("texts") or [])],
        )
    elif kind == "product":
        out.update(scope="product", fact=builder.get("fact"))
    return out


@lru_cache(maxsize=4096)
def _regex(pattern: str) -> re.Pattern:
    return re.compile(pattern)


# Compiled once per builder object, not once per product: a catalogue run reads every
# rule for each of 11,000 codes with the same loaded rule dicts. Keyed on the object's
# identity and holding the object itself, so a freed dict can never hand its id to a
# different builder and inherit its compile.
_COMPILED: dict[int, tuple[dict, dict]] = {}
_COMPILED_LIMIT = 20000


def compiled_for(builder: dict) -> dict:
    cached = _COMPILED.get(id(builder))
    if cached is not None and cached[0] is builder:
        return cached[1]
    compiled = compile_builder(builder)
    if len(_COMPILED) >= _COMPILED_LIMIT:
        _COMPILED.clear()
    _COMPILED[id(builder)] = (builder, compiled)
    return compiled


# --------------------------------------------------------------------------- #
# reading text and codes (contract section 2)
# --------------------------------------------------------------------------- #
def builder_of(rule) -> dict:
    """The builder of a stored rule, or an empty dict for anything else."""
    if isinstance(rule, dict) and isinstance(rule.get("builder"), dict):
        return rule["builder"]
    return {}


def _number(raw: str):
    value = float(raw)
    return int(value) if value.is_integer() else value


def _texts_to_read(look_in: str, texts: dict[str, str]) -> list[str]:
    if look_in == "name":
        return ["class_tail"]
    if look_in in {"description", "flyer"}:
        return [look_in]
    return ["description", "flyer"]


def _skipped(skip: str | None, haystack: str, start: int) -> bool:
    return bool(skip) and _regex(skip).search(haystack[:start]) is not None


def _size_read(compiled: dict, haystack: str):
    """(number, evidence) for a size pick, or None.

    A numbered pick reads the nth number of the FIRST size in the text, and nothing when
    that size has no nth number. A labelled pick reads the number labelled L, W or H in
    the first size that labels one.
    """
    pick = compiled.get("pick")
    pattern = _regex(compiled["pattern"])
    if isinstance(pick, str):
        wanted = pick.upper()
        for match in pattern.finditer(haystack):
            for label_group in (1, 3, 5, 7):
                if match.group(label_group) == wanted:
                    return _number(match.group(label_group + 1)), match.group(0)
        return None
    match = pattern.search(haystack)
    if not match:
        return None
    try:
        position = int(pick)
    except (TypeError, ValueError):
        return None
    if not 1 <= position <= 4:
        return None
    raw = match.group(position * 2)
    if raw is None:
        return None
    return _number(raw), match.group(0)


def read_text(builder: dict, texts: dict[str, str], code: str, spec_key: str | None = None):
    """(value, evidence, which_text) for a words / number / size / code rule, or None.

    Never raises: a builder that cannot compile reads nothing, and the next rule is
    tried. Product rules read the product record and are answered by the caller.
    """
    kind = builder.get("kind")
    try:
        if kind == "code":
            texts_to_find = [str(t).upper() for t in builder.get("texts") or [] if str(t).strip()]
            code_match = builder.get("code_match")
            for needle in texts_to_find:
                if code_match == "ends_with":
                    hit = code.endswith(needle)
                elif code_match == "starts_with":
                    hit = code.startswith(needle)
                elif code_match == "contains":
                    hit = needle in code
                else:
                    return None
                if hit:
                    return builder.get("value"), needle, "code"
            return None
        if kind not in {"words", "number", "size"}:
            return None
        if kind == "words" and not builder.get("words"):
            return None
        if kind == "number" and not (builder.get("before") or builder.get("after")):
            return None

        compiled = compiled_for(builder)
        look_in = builder.get("look_in") or default_look_in(spec_key)
        for name in _texts_to_read(look_in, texts):
            haystack = texts.get(name, "")
            if not haystack:
                continue
            if kind == "size":
                found = _size_read(compiled, haystack)
                if found is not None:
                    return found[0], found[1], name
                continue
            for match in _regex(compiled["pattern"]).finditer(haystack):
                if _skipped(compiled.get("skip"), haystack, match.start()):
                    continue
                if kind == "words":
                    return builder.get("value"), match.group(0), name
                raw = match.group(1)
                if raw is None:
                    continue
                value = _number(raw)
                floor = compiled.get("min")
                if floor is not None and value < float(floor):
                    continue
                scale = compiled.get("scale")
                if scale:
                    value = value * float(scale)
                    if float(value).is_integer():
                        value = int(value)
                return value, match.group(0), name
    except (re.error, TypeError, ValueError):
        return None
    return None


def gate_passes(builder: dict, held: dict) -> bool:
    """Whether the rule's Only when is met by what this derivation has read so far.

    `is: true` needs the other spec to hold one of the values; `is: false` needs it not
    to. A spec the derivation has not read leaves `is: false` met and `is: true` unmet,
    which is exactly how the old `applies_when` / `unless` gates behaved.
    """
    only_when = builder.get("only_when")
    if not isinstance(only_when, dict) or not only_when.get("spec"):
        return True
    value = held.get(only_when["spec"])
    allowed = {str(v).strip().lower() for v in only_when.get("values") or []}
    hit = value is not None and str(value).strip().lower() in allowed
    return hit is bool(only_when.get("is", True))


def gate_keys(rules_by_key: dict[str, list[dict]]) -> set[str]:
    """Keys some rule's Only when reads, so they are derived before the rules that need them."""
    keys: set[str] = set()
    for rules in (rules_by_key or {}).values():
        for rule in rules or []:
            only_when = builder_of(rule).get("only_when")
            if isinstance(only_when, dict) and only_when.get("spec"):
                keys.add(str(only_when["spec"]))
    return keys


# --------------------------------------------------------------------------- #
# canonical form and validation (contract sections 1.1 and 3)
# --------------------------------------------------------------------------- #
def _upper_list(raw) -> list[str]:
    """Upper case, trimmed, no empties, no duplicates, order kept."""
    out: list[str] = []
    if isinstance(raw, str):
        raw = [raw]
    for item in raw or []:
        word = " ".join(str(item or "").upper().split())
        if word and word not in out:
            out.append(word)
    return out


def _clean_number(raw):
    if raw is None or raw == "":
        return None
    value = float(raw)
    return int(value) if value.is_integer() else value


def _clean_pick(raw):
    if isinstance(raw, bool):
        return None
    if isinstance(raw, str):
        text = raw.strip().upper()
        if text in {"L", "W", "H"}:
            return text
        if text.isdigit():
            raw = int(text)
        else:
            return None
    if isinstance(raw, float) and raw.is_integer():
        raw = int(raw)
    return raw if raw in (1, 2, 3, 4) else None


def clean_builder(builder: dict) -> dict:
    """A builder in its stored form. Assumes `validate_rules` has accepted it.

    Only the fields the kind uses, words upper case, empty optional parts dropped, so
    two builders that mean the same thing are the same JSON (the seed repair and the
    fold both compare builders by that JSON).
    """
    kind = builder.get("kind")
    out: dict[str, Any] = {"kind": kind}
    if kind in {"words", "number", "size"} and builder.get("look_in"):
        out["look_in"] = builder["look_in"]
    if kind == "words":
        out["words"] = _upper_list(builder.get("words"))
        if builder.get("at_end"):
            out["at_end"] = True
        skip = _upper_list(builder.get("skip_after"))
        if skip:
            out["skip_after"] = skip
        out["value"] = builder.get("value")
    elif kind == "number":
        for part in ("before", "after"):
            words = _upper_list(builder.get(part))
            if words:
                out[part] = words
        if builder.get("written_in"):
            out["written_in"] = builder["written_in"]
        floor = _clean_number(builder.get("ignore_below"))
        if floor is not None:
            out["ignore_below"] = floor
        skip = _upper_list(builder.get("skip_after"))
        if skip:
            out["skip_after"] = skip
    elif kind == "size":
        out["pick"] = _clean_pick(builder.get("pick"))
    elif kind == "code":
        out["code_match"] = builder.get("code_match")
        out["texts"] = _upper_list(builder.get("texts"))
        out["value"] = builder.get("value")
    elif kind == "product":
        out["fact"] = builder.get("fact")
    only_when = builder.get("only_when")
    if isinstance(only_when, dict) and only_when.get("spec"):
        out["only_when"] = {
            "spec": str(only_when["spec"]).strip(),
            "is": bool(only_when.get("is", True)),
            "values": [str(v).strip() for v in only_when.get("values") or [] if str(v).strip()],
        }
    return out


def builder_identity(builder: dict) -> str:
    """One string per meaning, for comparing a stored rule with a shipped one."""
    return json.dumps(builder or {}, sort_keys=True, default=str)


def _refuse(message: str, *, status_code: int = 400, code: str = "spec_registry_bad_rule"):
    from app.services.error_handler import AppException

    return AppException(status_code=status_code, message=message, code=code)


def _value_for(raw, *, data_type: str, allowed: list[str], n: int):
    """The value a Words or Code rule sets, in the shape the spec stores, or refused."""
    data_type = (data_type or "").lower()
    if raw is None or (isinstance(raw, str) and not raw.strip()):
        raise _refuse(f"Rule {n}: pick the value it sets.")
    if data_type == "boolean":
        if raw is True or str(raw).strip().lower() in {"true", "yes", "1"}:
            return True
        raise _refuse(f"Rule {n}: pick the value it sets.")
    if data_type == "numeric":
        try:
            return _clean_number(raw)
        except (TypeError, ValueError):
            raise _refuse(f"Rule {n}: pick the value it sets.")
    value = raw if not isinstance(raw, str) else raw.strip()
    if allowed and str(value) not in allowed:
        # Named without the choice's code name (D15): the person is looking at labels.
        raise _refuse(
            f"Rule {n} sets a value this specification does not have. Pick one of its "
            "choices, or add the choice first.",
            code="spec_registry_unknown_rule_value",
        )
    return value


def validate_rules(
    rules,
    *,
    spec_key: str | None = None,
    data_type: str = "",
    allowed_values: list | None = None,
) -> list[dict]:
    """Every rule checked and put in its stored form, `[{"builder": cleaned}, ...]`.

    Refused with a 400 naming the missing part in plain words, never a code name
    (contract section 3, D15). A rule sent with the `pattern` the screen compiled is held
    to the server's compile of the same builder, and a mismatch is a 422: the two
    compilers disagree, and saving would run something the screen did not show.
    """
    if (spec_key or "").strip().lower() == BRAND_KEY:
        raise _refuse(BRAND_IS_NOT_A_SPEC, code="spec_registry_brand")
    allowed = [str(v) for v in (allowed_values or [])]
    closed = allowed if (data_type or "").lower() == "enum" else []

    cleaned_rules: list[dict] = []
    for n, rule in enumerate(rules or [], start=1):
        builder = builder_of(rule)
        if not builder:
            raise _refuse(f"Rule {n} has no parts. Open it and pick what it reads.")
        kind = builder.get("kind")
        if kind not in KINDS:
            raise _refuse(f"Rule {n}: pick a kind (Words, Number, Size, Code or Product).")

        if kind in {"words", "number", "size"}:
            look_in = builder.get("look_in")
            if look_in is not None and look_in not in LOOK_INS:
                raise _refuse(f"Rule {n}: pick where to look.")

        if kind == "words":
            if not _upper_list(builder.get("words")):
                raise _refuse(f"Rule {n}: add at least one word to find.")
            value = _value_for(builder.get("value"), data_type=data_type, allowed=closed, n=n)
        elif kind == "number":
            if not (_upper_list(builder.get("before")) or _upper_list(builder.get("after"))):
                raise _refuse(f"Rule {n}: add at least one word next to the number.")
            written_in = builder.get("written_in")
            if written_in is not None and written_in not in WRITTEN_IN_SCALE:
                raise _refuse(f"Rule {n}: pick the unit the number is written in.")
            try:
                _clean_number(builder.get("ignore_below"))
            except (TypeError, ValueError):
                raise _refuse(f"Rule {n}: the number to ignore below must be a number.")
        elif kind == "size":
            if _clean_pick(builder.get("pick")) is None:
                raise _refuse(f"Rule {n}: pick which number of the size to read.")
        elif kind == "code":
            if builder.get("code_match") not in CODE_MATCHES:
                raise _refuse(f"Rule {n}: pick how the code is matched.")
            if not _upper_list(builder.get("texts")):
                raise _refuse(f"Rule {n}: add at least one piece of code to find.")
            value = _value_for(builder.get("value"), data_type=data_type, allowed=closed, n=n)
        elif kind == "product":
            if builder.get("fact") not in FACTS:
                raise _refuse(f"Rule {n}: pick which fact about the product to read.")

        only_when = builder.get("only_when")
        if only_when is not None:
            spec = (
                str((only_when or {}).get("spec") or "").strip()
                if isinstance(only_when, dict)
                else ""
            )
            values = (
                [v for v in only_when.get("values") or [] if str(v).strip()]
                if isinstance(only_when, dict)
                else []
            )
            if not spec or not values or spec.lower() == BRAND_KEY:
                raise _refuse(
                    f"Rule {n}: pick the specification and at least one value for Only when."
                )

        sent_pattern = rule.get("pattern") if isinstance(rule, dict) else None
        if sent_pattern is not None and sent_pattern != compile_builder(builder)["pattern"]:
            raise _refuse(
                f"Rule {n} does not match what the screen showed. Open it and save it again.",
                status_code=422,
                code="spec_rule_builder_mismatch",
            )

        cleaned = clean_builder(builder)
        if kind in {"words", "code"}:
            cleaned["value"] = value
        cleaned_rules.append({"builder": cleaned})
    return cleaned_rules


# --------------------------------------------------------------------------- #
# folding neighbours
# --------------------------------------------------------------------------- #
def _fold_key(builder: dict) -> str | None:
    """What two Words rules must share to fold into one: everything but the words."""
    if builder.get("kind") != "words":
        return None
    return builder_identity({k: v for k, v in builder.items() if k != "words"})


def fold_rules(rules: list[dict]) -> list[dict]:
    """Neighbouring Words rules with the same answer become one rule with several words.

    Order is kept: the folded rule sits where the first of its neighbours sat, and its
    words keep their order, so the first match still wins exactly as it did. Only
    NEIGHBOURS fold - two rules with the same answer and a different rule between them
    stay apart, or the one between would change which rule fires first. Code rules do
    not fold: each reads one convention and the list reads them one per row.
    """
    folded: list[dict] = []
    for rule in rules or []:
        builder = builder_of(rule)
        key = _fold_key(builder)
        if folded and key is not None and key == _fold_key(builder_of(folded[-1])):
            previous = dict(folded[-1])
            merged = dict(builder_of(previous))
            merged["words"] = _upper_list(
                list(merged.get("words") or []) + list(builder.get("words") or [])
            )
            previous["builder"] = merged
            folded[-1] = previous
            continue
        folded.append(dict(rule))
    return folded


# --------------------------------------------------------------------------- #
# the rules that came before builders
# --------------------------------------------------------------------------- #
class UnconvertibleRule(ValueError):
    """A stored rule with no builder that no kind can express."""


_SIZE_REGEX_V1 = (
    r"(?:[LWHDlwhd]\s*)?(\d+(?:\.\d+)?)\s*(?:MM|mm)?\s*[xX*]\s*(?:[LWHDlwhd]\s*)?"
    r"(\d+(?:\.\d+)?)\s*(?:MM|mm)?(?:\s*[xX*]\s*(?:[LWHDlwhd]\s*)?(\d+(?:\.\d+)?)\s*"
    r"(?:MM|mm)?)?(?:\s*[xX*]\s*(?:[LWHDlwhd]\s*)?(\d+(?:\.\d+)?)\s*(?:MM|mm)?)?"
)
_FIELD_TO_FACT = {
    "category": "class",
    "column:dimensions_length": "length",
    "column:dimensions_width": "width",
    "column:dimensions_height": "height",
}
_SOURCE_TO_LOOK_IN = {
    "description": "description",
    "flyer": "flyer",
    "class_tail": "name",
    "size_text": "description",
    "any": "any",
}
_SPEAKABLE = re.compile(r"[A-Za-z0-9 &/'.\-]+")


def _gate_to_only_when(rule: dict) -> dict | None:
    gates = []
    for field, is_ in (("applies_when", True), ("unless", False)):
        for spec, values in (rule.get(field) or {}).items():
            values = [str(v) for v in values or [] if str(v).strip()]
            if values:
                gates.append({"spec": str(spec), "is": is_, "values": values})
    if len(gates) > 1:
        raise UnconvertibleRule("it has more than one condition")
    return gates[0] if gates else None


def legacy_to_builder(rule: dict, spec_key: str | None = None) -> dict:
    """The builder a rule stored before builders existed means. Raises UnconvertibleRule.

    Used by tests and scripts to read the frozen pre-lane rules. The S1 migration
    carries its own frozen copy of this mapping, because a migration must not change
    when this module does.
    """
    if builder_of(rule).get("kind") in KINDS:
        return dict(builder_of(rule))
    match = str(rule.get("match") or "contains").lower()
    pattern = str(rule.get("pattern") or "")
    look_in = _SOURCE_TO_LOOK_IN.get(str(rule.get("source") or "any"), None) or "any"
    if look_in == "any":
        look_in = default_look_in(spec_key)
    only_when = _gate_to_only_when(rule)
    legacy = builder_of(rule)
    legacy_kind = legacy.get("kind")

    builder: dict | None = None
    if match == "contains" and pattern:
        builder = {
            "kind": "words",
            "look_in": look_in,
            "words": [pattern],
            "value": rule.get("value"),
        }
    elif match == "ends_with" and pattern:
        builder = {
            "kind": "words",
            "look_in": look_in,
            "words": [pattern],
            "at_end": True,
            "value": rule.get("value"),
        }
    elif match == "code_suffix" and pattern:
        builder = {
            "kind": "code",
            "code_match": "ends_with",
            "texts": [f"-{pattern.upper()}"],
            "value": rule.get("value"),
        }
    elif match in {"code_contains", "code_starts_with"} and pattern:
        builder = {
            "kind": "code",
            "code_match": "contains" if match == "code_contains" else "starts_with",
            "texts": [pattern],
            "value": rule.get("value"),
        }
    elif match == "from_field" and pattern in _FIELD_TO_FACT:
        builder = {"kind": "product", "fact": _FIELD_TO_FACT[pattern]}
    elif match == "name_head":
        builder = {"kind": "product", "fact": "name"}
    elif match == "regex" and pattern == _SIZE_REGEX_V1 and rule.get("capture"):
        builder = {"kind": "size", "look_in": look_in, "pick": int(rule["capture"])}
    elif legacy_kind in {"number_before", "number_after"} and legacy.get("word"):
        part = "before" if legacy_kind == "number_before" else "after"
        builder = {"kind": "number", "look_in": look_in, part: [legacy["word"]]}
    elif legacy_kind == "number_between" and legacy.get("from") and legacy.get("to"):
        builder = {
            "kind": "number",
            "look_in": look_in,
            "after": [legacy["from"]],
            "before": [legacy["to"]],
        }
    elif legacy_kind == "size_triple":
        builder = {"kind": "size", "look_in": look_in, "pick": int(legacy.get("position") or 1)}
    elif match == "present" and pattern and _SPEAKABLE.fullmatch(pattern):
        builder = {
            "kind": "words",
            "look_in": look_in,
            "words": [pattern],
            "value": rule.get("value", True),
        }
    if builder is None:
        raise UnconvertibleRule(f"{match} {pattern!r} has no kind that can express it")
    if rule.get("scale") and builder["kind"] == "number":
        scale = float(rule["scale"])
        builder["written_in"] = {10.0: "centimetres", 1000.0: "metres"}.get(scale)
        if builder["written_in"] is None:
            raise UnconvertibleRule(f"a scale of {rule['scale']} has no unit")
    if only_when:
        builder["only_when"] = only_when
    return clean_builder(builder)
