"""Read-only GET endpoint catalog → MCP tools (1:1 with CRM list/detail/search GETs in scope)."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ToolSpec:
    name: str
    description: str
    path: str
    path_params: tuple[str, ...] = ()
    query_params: tuple[str, ...] = ()


# Paths match [sorento_crm_backend/app/api/v1/__init__.py](sorento_crm_backend/app/api/v1/__init__.py) prefixes.
CATALOG: tuple[ToolSpec, ...] = (
    # --- master-data ---
    ToolSpec(
        "crm_master_products_list",
        "List products with filters and pagination. Parameter `query` matches product code, name, and description.",
        "/api/v1/master-data/products",
        (),
        (
            "page",
            "limit",
            "query",
            "category_id",
            "brand_id",
            "status",
            "price_min",
            "price_max",
            "item_type",
            "sort",
            "dir",
        ),
    ),
    ToolSpec(
        "crm_master_products_get",
        "Get one product by id (includes related data per API).",
        "/api/v1/master-data/products/{product_id}",
        ("product_id",),
        (),
    ),
    ToolSpec(
        "crm_master_products_select",
        "Lightweight product list for dropdowns (active only, optional search).",
        "/api/v1/master-data/products/select",
        (),
        ("query",),
    ),
    ToolSpec(
        "crm_master_brands_list",
        "List brands with pagination.",
        "/api/v1/master-data/brands",
        (),
        ("page", "limit", "query"),
    ),
    ToolSpec(
        "crm_master_brands_select",
        "Brands for select controls.",
        "/api/v1/master-data/brands/select",
        (),
        ("query",),
    ),
    ToolSpec(
        "crm_master_brands_get",
        "Get one brand by id.",
        "/api/v1/master-data/brands/{brand_id}",
        ("brand_id",),
        (),
    ),
    ToolSpec(
        "crm_master_product_categories_tree",
        "Product category tree.",
        "/api/v1/master-data/product-categories/tree",
        (),
        (),
    ),
    ToolSpec(
        "crm_master_product_categories_list",
        "List product categories.",
        "/api/v1/master-data/product-categories",
        (),
        ("page", "limit", "query"),
    ),
    ToolSpec(
        "crm_master_product_categories_select",
        "Categories for select controls.",
        "/api/v1/master-data/product-categories/select",
        (),
        ("query",),
    ),
    ToolSpec(
        "crm_master_product_categories_get",
        "Get one product category by id.",
        "/api/v1/master-data/product-categories/{category_id}",
        ("category_id",),
        (),
    ),
    ToolSpec(
        "crm_master_units_of_measure_list",
        "List units of measure.",
        "/api/v1/master-data/units-of-measure",
        (),
        ("page", "limit", "query"),
    ),
    ToolSpec(
        "crm_master_units_of_measure_select",
        "UOMs for select controls.",
        "/api/v1/master-data/units-of-measure/select",
        (),
        ("query",),
    ),
    ToolSpec(
        "crm_master_units_of_measure_get",
        "Get one UOM by id.",
        "/api/v1/master-data/units-of-measure/{uom_id}",
        ("uom_id",),
        (),
    ),
    ToolSpec(
        "crm_master_product_attachments_list",
        "List product–attachment links with filters. `product_id` accepts a product UUID or exact product code.",
        "/api/v1/master-data/product-attachments",
        (),
        ("page", "limit", "sort", "dir", "product_id", "attachment_id", "user_type"),
    ),
    ToolSpec(
        "crm_master_product_attachments_get",
        "Get one product attachment link by id.",
        "/api/v1/master-data/product-attachments/{product_attachment_id}",
        ("product_attachment_id",),
        (),
    ),
    ToolSpec(
        "crm_master_product_attachments_by_product",
        "All attachment links for a product. `product_id` accepts a product UUID or exact product code.",
        "/api/v1/master-data/product-attachments/product/{product_id}",
        ("product_id",),
        ("user_type",),
    ),
    # --- marketing ---
    ToolSpec(
        "crm_marketing_promotions_list",
        "List promotions (summary: promo fields and products_count only; no product lines). For lines use crm_marketing_promotion_products_list or nested products tool.",
        "/api/v1/marketing/promotions",
        (),
        ("page", "limit", "query", "user_type", "status", "promo_type", "sort", "dir"),
    ),
    ToolSpec(
        "crm_marketing_promotions_get",
        "Get one promotion metadata and groups (FOC tiers, etc.). Does NOT include product lines by default; set include_products=true only if you need nested SKU lines.",
        "/api/v1/marketing/promotions/{promotion_id}",
        ("promotion_id",),
        ("user_type", "include_products"),
    ),
    ToolSpec(
        "crm_marketing_promotion_products_nested",
        "Products linked to a promotion (nested under promotion). Optional page/limit (default limit 1000, max 5000).",
        "/api/v1/marketing/promotions/{promotion_id}/products",
        ("promotion_id",),
        ("page", "limit"),
    ),
    ToolSpec(
        "crm_marketing_promotion_products_list",
        "Promotion product lines (paginated). REQUIRED PATTERN: set promotion_id to ONE promotion (UUID or promo_code). Do NOT put promotion UUIDs only inside query. Optional query = text search (SKU/name/promo code). If promotion_id is omitted: a single bare UUID or promotion_id='<uuid>' in query scopes to one promotion; comma-separated UUIDs in query scope to those promotions (combined rows).",
        "/api/v1/marketing/promotion-products",
        (),
        ("page", "limit", "sort", "dir", "query", "promotion_id"),
    ),
    ToolSpec(
        "crm_marketing_promotion_attachments_list",
        "List promotion–attachment links. promotion_id accepts UUID or promo_code.",
        "/api/v1/marketing/promotion-attachments",
        (),
        ("page", "limit", "sort", "dir", "promotion_id", "attachment_id"),
    ),
    ToolSpec(
        "crm_marketing_promotion_attachments_get",
        "Get one promotion attachment link by id.",
        "/api/v1/marketing/promotion-attachments/{promotion_attachment_id}",
        ("promotion_attachment_id",),
        (),
    ),
    ToolSpec(
        "crm_marketing_promotion_attachments_by_promotion",
        "All promotion attachments for a promotion. promotion_id may be UUID or promo_code (ambiguous if duplicate codes exist—use UUID).",
        "/api/v1/marketing/promotion-attachments/promotion/{promotion_id}",
        ("promotion_id",),
        (),
    ),
    ToolSpec(
        "crm_marketing_campaigns_list",
        "List marketing campaigns.",
        "/api/v1/marketing/campaigns",
        (),
        ("page", "limit"),
    ),
    ToolSpec(
        "crm_marketing_campaigns_get",
        "Get one campaign by id.",
        "/api/v1/marketing/campaigns/{campaign_id}",
        ("campaign_id",),
        (),
    ),
    ToolSpec(
        "crm_marketing_campaign_types_list",
        "List campaign types.",
        "/api/v1/marketing/campaign-types",
        (),
        (),
    ),
    ToolSpec(
        "crm_marketing_campaign_types_get",
        "Get one campaign type by id.",
        "/api/v1/marketing/campaign-types/{type_id}",
        ("type_id",),
        (),
    ),
    # --- resource-management ---
    ToolSpec(
        "crm_resource_attachments_list",
        "List file attachments (filters: query, entity, directory, trash).",
        "/api/v1/resource-management/attachments",
        (),
        (
            "page",
            "limit",
            "query",
            "sort",
            "dir",
            "entity_type",
            "entity_id",
            "directory_id",
            "is_deleted",
            "resolve_signed_urls",
        ),
    ),
    ToolSpec(
        "crm_resource_attachments_current_stock_list",
        "Latest Stock List attachment row if configured.",
        "/api/v1/resource-management/attachments/current-stock-list",
        (),
        (),
    ),
    ToolSpec(
        "crm_resource_attachments_get",
        "Get attachment metadata by id (includes linked entities).",
        "/api/v1/resource-management/attachments/{attachment_id}",
        ("attachment_id",),
        (),
    ),
    ToolSpec(
        "crm_resource_attachments_download",
        "Download attachment bytes (binary; may be large). Prefer metadata tool when possible.",
        "/api/v1/resource-management/attachments/{attachment_id}/download",
        ("attachment_id",),
        (),
    ),
    ToolSpec(
        "crm_resource_attachments_metadata",
        "Attachment metadata only (same as get for most fields).",
        "/api/v1/resource-management/attachments/{attachment_id}/metadata",
        ("attachment_id",),
        (),
    ),
    ToolSpec(
        "crm_resource_attachments_preview_url",
        "Signed preview URL for an attachment.",
        "/api/v1/resource-management/attachments/{attachment_id}/preview-url",
        ("attachment_id",),
        (),
    ),
    ToolSpec(
        "crm_resource_attachment_types_list",
        "List attachment types.",
        "/api/v1/resource-management/attachment-types",
        (),
        ("page", "limit", "query", "sort", "dir"),
    ),
    ToolSpec(
        "crm_resource_attachment_types_get",
        "Get attachment type by id.",
        "/api/v1/resource-management/attachment-types/{type_id}",
        ("type_id",),
        (),
    ),
    ToolSpec(
        "crm_resource_directories_list",
        "List directories under optional parent_id.",
        "/api/v1/resource-management/directories",
        (),
        ("parent_id",),
    ),
    ToolSpec(
        "crm_resource_directories_tree",
        "Directory tree; use deleted=true for trash tree.",
        "/api/v1/resource-management/directories/tree",
        (),
        ("deleted",),
    ),
    ToolSpec(
        "crm_resource_directories_get",
        "Get one directory by id.",
        "/api/v1/resource-management/directories/{directory_id}",
        ("directory_id",),
        (),
    ),
    # --- inventory ---
    ToolSpec(
        "crm_inventory_stock_balance_list",
        "Paged stock balances (warehouse, product, quantity filters, status). product_id accepts UUID or product_code (SKU).",
        "/api/v1/inventory/stock/balance",
        (),
        (
            "page",
            "limit",
            "query",
            "sort",
            "dir",
            "warehouse_id",
            "product_id",
            "quantity_operator",
            "quantity_value",
            "status",
        ),
    ),
    ToolSpec(
        "crm_inventory_stock_dashboard",
        "Stock dashboard aggregates.",
        "/api/v1/inventory/stock/dashboard",
        (),
        (),
    ),
    ToolSpec(
        "crm_inventory_stock_alerts",
        "Low-stock style alerts from API.",
        "/api/v1/inventory/stock/alerts",
        (),
        (),
    ),
    ToolSpec(
        "crm_inventory_stock_balance_export",
        "Export all stock rows (no pagination) with optional filters; requires export permission on act-as user. product_id accepts UUID or product_code (SKU).",
        "/api/v1/inventory/stock/balance/export",
        (),
        ("warehouse_id", "product_id", "quantity_operator", "quantity_value"),
    ),
    ToolSpec(
        "crm_inventory_stock_ledger_by_product_warehouse",
        "Ledger for one product in one warehouse. product_id may be UUID or product_code (SKU).",
        "/api/v1/inventory/stock/{product_id}/{warehouse_id}/ledger",
        ("product_id", "warehouse_id"),
        ("page", "limit"),
    ),
    ToolSpec(
        "crm_inventory_warehouses_list",
        "List warehouses.",
        "/api/v1/inventory/warehouses",
        (),
        ("page", "limit", "query", "is_active"),
    ),
    ToolSpec(
        "crm_inventory_warehouses_get",
        "Get warehouse by id.",
        "/api/v1/inventory/warehouses/{warehouse_id}",
        ("warehouse_id",),
        (),
    ),
    ToolSpec(
        "crm_inventory_storage_zones_list",
        "List storage zones.",
        "/api/v1/inventory/storage-zones",
        (),
        ("page", "limit", "warehouse_id"),
    ),
    ToolSpec(
        "crm_inventory_storage_zones_tree",
        "Storage zone tree.",
        "/api/v1/inventory/storage-zones/tree",
        (),
        ("warehouse_id",),
    ),
    ToolSpec(
        "crm_inventory_storage_zones_get",
        "Get storage zone by id.",
        "/api/v1/inventory/storage-zones/{zone_id}",
        ("zone_id",),
        (),
    ),
    ToolSpec(
        "crm_inventory_stock_ledger_list",
        "Global stock ledger list. product_id query accepts UUID or product_code (SKU).",
        "/api/v1/inventory/stock-ledger",
        (),
        ("page", "limit", "product_id", "warehouse_id", "transaction_type"),
    ),
    ToolSpec(
        "crm_inventory_stock_batches_list",
        "List stock batches. product_id accepts UUID or product_code (SKU).",
        "/api/v1/inventory/stock-batches",
        (),
        ("page", "limit", "product_id", "warehouse_id"),
    ),
    ToolSpec(
        "crm_inventory_stock_batches_get",
        "Get stock batch by id.",
        "/api/v1/inventory/stock-batches/{batch_id}",
        ("batch_id",),
        (),
    ),
    # --- order-management ---
    ToolSpec(
        "crm_order_management_orders_list",
        "List orders (customer, status, has_order_lines, actual delivery date filters, search). Parameter `query` matches order number, debtor name/code, and customer name/code.",
        "/api/v1/order-management/orders",
        (),
        (
            "page",
            "limit",
            "query",
            "customer_id",
            "order_status_id",
            "has_order_lines",
            "has_actual_delivery_date",
            "actual_delivery_date_from",
            "actual_delivery_date_to",
            "sort",
            "dir",
        ),
    ),
    ToolSpec(
        "crm_order_management_orders_get",
        "Get one order by id (includes order lines in response).",
        "/api/v1/order-management/orders/{order_id}",
        ("order_id",),
        (),
    ),
    ToolSpec(
        "crm_order_management_orders_by_product_list",
        "List distinct orders matched by product search. Supports actual delivery date filters. Parameter `query` matches product code, name, description, order number, and debtor name.",
        "/api/v1/order-management/orders/by-product",
        (),
        (
            "page",
            "limit",
            "query",
            "product_id",
            "has_actual_delivery_date",
            "actual_delivery_date_from",
            "actual_delivery_date_to",
            "sort",
            "dir",
        ),
    ),
    # --- procurement ---
    ToolSpec(
        "crm_procurement_packing_lists_list",
        "Inbound shipment summaries (packing lists). Returns compact shipment headers only; use crm_procurement_packing_lists_get for full shipment lines. `shipment_status=open` means shipments with at least one line not fully received yet.",
        "/api/v1/procurement/packing-lists",
        (),
        ("page", "limit", "query", "supplier_id", "shipment_status", "sort", "dir"),
    ),
    ToolSpec(
        "crm_procurement_packing_lists_get",
        "Inbound shipment detail by id (includes lines / SPO context per API).",
        "/api/v1/procurement/packing-lists/{shipment_id}",
        ("shipment_id",),
        (),
    ),
    ToolSpec(
        "crm_procurement_spo_allocations_grouped_by_shipment",
        "Find inbound shipments in summary form using SPO allocation filters. Returns shipment summary plus counts only; use crm_procurement_packing_lists_get or crm_procurement_spo_allocations_list for details.",
        "/api/v1/procurement/spo-allocations/grouped-by-shipment",
        (),
        (
            "page",
            "limit",
            "query",
            "product_code",
            "warehouse_id",
            "receipt_status",
            "sort",
            "dir",
        ),
    ),
    ToolSpec(
        "crm_procurement_spo_allocations_grouped_by_spo",
        "SPO allocations grouped by SPO number.",
        "/api/v1/procurement/spo-allocations/grouped-by-spo-number",
        (),
        (
            "page",
            "limit",
            "query",
            "product_code",
            "warehouse_id",
            "receipt_status",
            "sort",
            "dir",
        ),
    ),
    ToolSpec(
        "crm_procurement_spo_allocations_list",
        "Flat list of SPO allocations.",
        "/api/v1/procurement/spo-allocations",
        (),
        (
            "page",
            "limit",
            "query",
            "shipment_id",
            "warehouse_id",
            "receipt_status",
            "sort",
            "dir",
        ),
    ),
    ToolSpec(
        "crm_procurement_spo_allocations_get",
        "Single SPO allocation with linked GRNs and computed receipt fields.",
        "/api/v1/procurement/spo-allocations/{allocation_id}",
        ("allocation_id",),
        (),
    ),
    ToolSpec(
        "crm_procurement_grn_list",
        "GRN / picking headers list.",
        "/api/v1/procurement/grn",
        (),
        ("page", "limit", "query", "picking_status", "inspection_status", "sort", "dir"),
    ),
    ToolSpec(
        "crm_procurement_grn_get",
        "GRN / picking header by id.",
        "/api/v1/procurement/grn/{grn_id}",
        ("grn_id",),
        (),
    ),
    ToolSpec(
        "crm_procurement_picking_lines_list",
        "Picking lines with search (SPO / product) and sort.",
        "/api/v1/procurement/picking-lines",
        (),
        ("page", "limit", "query", "sort", "dir"),
    ),
    # --- forms ---
    ToolSpec(
        "crm_forms_management_forms_list",
        "List legacy forms.",
        "/api/v1/forms-management/forms",
        (),
        ("page", "limit", "query", "language", "status", "sort", "dir"),
    ),
    ToolSpec(
        "crm_forms_management_forms_get",
        "Get legacy form by id.",
        "/api/v1/forms-management/forms/{form_id}",
        ("form_id",),
        (),
    ),
    # --- workflow-forms ---
    ToolSpec(
        "crm_workflow_forms_definitions_list",
        "List workflow form definitions.",
        "/api/v1/workflow-forms/definitions",
        (),
        ("page", "limit", "q", "is_active"),
    ),
    ToolSpec(
        "crm_workflow_forms_definitions_published_for_submission",
        "Published definitions for users who submit (narrow list).",
        "/api/v1/workflow-forms/definitions/published-for-submission",
        (),
        (),
    ),
    ToolSpec(
        "crm_workflow_forms_definitions_get",
        "Workflow definition by id.",
        "/api/v1/workflow-forms/definitions/{definition_id}",
        ("definition_id",),
        (),
    ),
    ToolSpec(
        "crm_workflow_forms_definitions_preview",
        "Preview draft or published schema. source=draft|published.",
        "/api/v1/workflow-forms/definitions/{definition_id}/preview",
        ("definition_id",),
        ("source",),
    ),
    ToolSpec(
        "crm_workflow_forms_definitions_published_schema",
        "Published schema for building submissions.",
        "/api/v1/workflow-forms/definitions/{definition_id}/published-schema",
        ("definition_id",),
        (),
    ),
    ToolSpec(
        "crm_workflow_forms_definitions_flow_graph",
        "Flow graph nodes/edges for a definition.",
        "/api/v1/workflow-forms/definitions/{definition_id}/flow-graph",
        ("definition_id",),
        ("source",),
    ),
    ToolSpec(
        "crm_workflow_forms_submissions_list",
        "List workflow submissions.",
        "/api/v1/workflow-forms/submissions",
        (),
        ("page", "limit", "definition_id", "state_code"),
    ),
    ToolSpec(
        "crm_workflow_forms_submissions_get",
        "Workflow submission by id (includes lines/logs).",
        "/api/v1/workflow-forms/submissions/{submission_id}",
        ("submission_id",),
        (),
    ),
    ToolSpec(
        "crm_workflow_forms_submissions_allowed_transitions",
        "Allowed transitions for a submission for the act-as user.",
        "/api/v1/workflow-forms/submissions/{submission_id}/allowed-transitions",
        ("submission_id",),
        (),
    ),
    # --- sla-management ---
    ToolSpec(
        "crm_sla_policies_list",
        "List SLA policies.",
        "/api/v1/sla-management/sla-policies",
        (),
        ("page", "limit", "query", "status", "sort", "dir"),
    ),
    ToolSpec(
        "crm_sla_policies_get",
        "SLA policy by id.",
        "/api/v1/sla-management/sla-policies/{policy_id}",
        ("policy_id",),
        (),
    ),
    ToolSpec(
        "crm_sla_policies_tiers",
        "Tiers for a policy.",
        "/api/v1/sla-management/sla-policies/{policy_id}/tiers",
        ("policy_id",),
        (),
    ),
    ToolSpec(
        "crm_sla_conversation_tracking_dashboard",
        "SLA tracking dashboard metrics.",
        "/api/v1/sla-management/conversation-sla-tracking/dashboard",
        (),
        (),
    ),
    ToolSpec(
        "crm_sla_conversation_tracking_list",
        "List conversation SLA tracking rows.",
        "/api/v1/sla-management/conversation-sla-tracking",
        (),
        ("page", "limit", "policy_id", "query", "sort", "dir", "assigned_to"),
    ),
    ToolSpec(
        "crm_sla_conversation_event_logs_list",
        "SLA event logs with filters (tracking_id, event_type, dates, assignee).",
        "/api/v1/sla-management/conversation-sla-tracking/event-logs",
        (),
        (
            "page",
            "limit",
            "sort",
            "dir",
            "tracking_id",
            "event_type",
            "assigned_to",
            "assigned_to_id",
            "date_from",
            "date_to",
        ),
    ),
    ToolSpec(
        "crm_sla_conversation_tracking_get",
        "Single conversation SLA tracking record.",
        "/api/v1/sla-management/conversation-sla-tracking/{tracking_id}",
        ("tracking_id",),
        (),
    ),
)
