"""sales_order_lines: discount + line_total

Revision ID: 413_so_line_discount_total
Revises: 412_merge_push_idea
Create Date: 2026-08-24 21:10:00.000000

The AutoCount sales-order detail listing states `Discount` and `Total (Inc)` on every line,
both have resolved through `import_field_alias` since migration 357, and neither had a column
to land in - so the reader dropped them and the detail page could only ever print a unit price
beside a quantity.

Two columns, `NUMERIC(15, 2)` to match `unit_price` beside them, both nullable: an absent
figure stays absent. A 0 discount claims a discount of nothing was given and a 0 total claims
the line was free, and the header's `total_amount` sums exactly these.

No backfill. The figures exist only in the source workbooks, so the honest way to fill them for
existing rows is a re-upload of the book, which the import path now writes them from
(`outstanding_import_service._BINDINGS[SO].money_cols`). Defaulting them from `unit_price *
qty_ordered` would invent a total nobody stated.

Hand-written rather than autogenerated: the local database is a prod copy that drifts ahead of
`alembic_version` (see `sorento_crm_backend/CLAUDE.md`), so a raw diff would carry unrelated
drift. These two columns are this revision's whole change.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '413_so_line_discount_total'
down_revision = '412_merge_push_idea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'sales_order_lines',
        sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=True),
    )
    op.add_column(
        'sales_order_lines',
        sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=True),
    )


def downgrade() -> None:
    op.drop_column('sales_order_lines', 'line_total')
    op.drop_column('sales_order_lines', 'discount')
