"""purchase_order_lines: discount + line_total + uom

Revision ID: 414_po_line_money
Revises: 413_so_line_discount_total
Create Date: 2026-08-24 23:10:00.000000

The supply-side twin of migration 413, and the same gap on the other book: the AutoCount PO
detail listing states `Discount` and `Total (Inc)` on every line beside the unit cost, and
neither had a column to land in - so the reader dropped them and the purchase-order detail
page could only ever print a cost beside a quantity, which is not what the supplier charged.

`uom` rides along for a third reason. The `outstanding_po` alias for `UOM` has resolved since
migration 311 and the sales side has had a per-line override column since it needed one, so a
purchase order written in cartons read in pieces off the product master's base unit. The
serializer falls back to that base unit when this column is NULL, exactly as
`sales_order_lines.uom` does.

`NUMERIC(15, 2)` on the two money columns to match `sales_order_lines.discount` /
`line_total`, both nullable: an absent figure stays absent. A 0 discount claims a discount of
nothing was given and a 0 total claims the line was free, and the header's `total_amount` sums
exactly these.

No backfill. The figures exist only in the source workbooks, so the honest way to fill them
for existing rows is a re-upload of the book, which the import path now writes them from
(`outstanding_import_service._BINDINGS[PO].money_cols`). Defaulting them from `unit_cost *
qty_ordered` would invent a total nobody stated.

Hand-written rather than autogenerated: the local database is a prod copy that drifts ahead of
`alembic_version` (see `sorento_crm_backend/CLAUDE.md`), so a raw diff would carry unrelated
drift. These three columns are this revision's whole change.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '414_po_line_money'
down_revision = '413_so_line_discount_total'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'purchase_order_lines',
        sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=True),
    )
    op.add_column(
        'purchase_order_lines',
        sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=True),
    )
    op.add_column(
        'purchase_order_lines',
        sa.Column('uom', sa.String(length=100), nullable=True),
    )


def downgrade() -> None:
    op.drop_column('purchase_order_lines', 'uom')
    op.drop_column('purchase_order_lines', 'line_total')
    op.drop_column('purchase_order_lines', 'discount')
