"""system_settings: the default unit of measure

Revision ID: 416_default_uom_setting
Revises: 415_po_money_aliases
Create Date: 2026-08-24 23:40:00.000000

The unit a product gets when nobody states one. It was a constant in the code -
`ProductService.DEFAULT_UOM_CODE = "EA"` - and the fallback before it took whatever unit the
database happened to return first, which is how 11,415 products came to be stamped `L`.

Correcting that with a backfill script means guessing what an admin can simply state, so the
admin states it here and a re-import of the product list applies it (the import now reads
this column for every row that carries no UOM cell, existing products included).

Nullable, with `ondelete="SET NULL"`: NULL means "nobody has said", which the service reads
as the built-in `EA` fallback, and deleting the configured unit puts the setting back to that
rather than leaving it pointing at nothing. No default value is seeded - a default here would
be the same guess the column exists to avoid.

Hand-written rather than autogenerated: the local database is a prod copy that drifts ahead of
`alembic_version` (see `sorento_crm_backend/CLAUDE.md`), so a raw diff would carry unrelated
drift. This one column is this revision's whole change.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '416_default_uom_setting'
down_revision = '415_po_money_aliases'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'system_settings',
        sa.Column('default_uom_id', postgresql.UUID(as_uuid=False), nullable=True),
    )
    op.create_foreign_key(
        'fk_system_settings_default_uom_id',
        'system_settings',
        'units_of_measure',
        ['default_uom_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint(
        'fk_system_settings_default_uom_id', 'system_settings', type_='foreignkey'
    )
    op.drop_column('system_settings', 'default_uom_id')
