"""projects.order_inquiries: a number of its own

Revision ID: 417_order_inquiry_number
Revises: 416_default_uom_setting
Create Date: 2026-08-25 11:20:00.000000

An order inquiry is what purchasing is handed, and until now the only way to name one was
its UUID. Nothing a person reads may be a UUID, so a planning record could be referred to
only as "the inquiry on SO414033" - which stops working the moment an amendment raises a
second one on the same order.

`OI-000001`, the same shape and the same series discipline as `ProjectSalesOrder`'s
`PSO-000001` (`project_so_draft_service._next_ref`), and UNIQUE on `(company_id,
inquiry_no)` for the same reason `provisional_ref` is: the read that mints the next number
is an ordinary ORM read and is therefore company-scoped, so each company runs its own
series. A table-wide constraint over a scoped read would mean the second company's first
inquiry asked for `OI-000001` and hit the constraint.

Three steps rather than one, because the column is NOT NULL on a table that already has
rows: add it nullable, number what is there, then tighten. The backfill is written even
though the table is empty on every database we can see - a migration that assumes an empty
table is a migration that fails on the one database nobody checked.

Hand-written rather than autogenerated: the local database is a prod copy that drifts ahead
of `alembic_version` (see `sorento_crm_backend/CLAUDE.md`), so a raw diff would carry
unrelated drift.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '417_order_inquiry_number'
down_revision = '416_default_uom_setting'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'order_inquiries',
        sa.Column('inquiry_no', sa.String(length=20), nullable=True),
        schema='projects',
    )
    # In id order, per company: the ids are what the table can be ordered by without
    # depending on a timestamp two rows can share (`now()` is fixed for a whole
    # transaction, so several inquiries raised by one confirm carry the identical
    # `raised_at`), and the series is per company like the constraint below.
    op.execute(
        """
        WITH numbered AS (
            SELECT id,
                   row_number() OVER (PARTITION BY company_id ORDER BY id) AS n
              FROM projects.order_inquiries
        )
        UPDATE projects.order_inquiries oi
           SET inquiry_no = 'OI-' || lpad(numbered.n::text, 6, '0')
          FROM numbered
         WHERE numbered.id = oi.id
        """
    )
    op.alter_column(
        'order_inquiries', 'inquiry_no', nullable=False, schema='projects',
    )
    op.create_unique_constraint(
        'uq_project_order_inquiry_no', 'order_inquiries', ['company_id', 'inquiry_no'],
        schema='projects',
    )


def downgrade() -> None:
    op.drop_constraint(
        'uq_project_order_inquiry_no', 'order_inquiries', schema='projects', type_='unique',
    )
    op.drop_column('order_inquiries', 'inquiry_no', schema='projects')
