"""projects.stock_transfers: the physical move a supply decision implies

Revision ID: 419_stock_transfers
Revises: 418_merge_oi_product_sets
Create Date: 2026-08-26 09:00:00.000000

`PLAN-scm-cs-planning-uat.md` section E, captain's Q2 ruling of 25 Aug 2026: stock taken
from a pool, or borrowed from another location, has to physically move to the line's own
location, and a person approves that move deliberately on a Transfers page.

Hand-written rather than autogenerated: the local database is a prod copy that drifts ahead
of `alembic_version` (see `sorento_crm_backend/CLAUDE.md`), so a raw diff would carry
unrelated drift.

Guarded with `IF NOT EXISTS` / inspector checks throughout, because this migration is
applied by hand on the shared dev database (whose `alembic_version` points at another
lane's head) and re-running it must be a no-op rather than a failure.

The second half is the grant sweep the DoD gate requires. Measured on the dev copy:
`inventory.stock.{view,add,edit,delete}` is held by admin, director, the three
`integration_*` roles, warehouse_executive and warehouse_manager (7 each), and
`projects.projects.{view,edit}` by the planning side. A transfer is a movement of stock
asked for by a planner and carried out by a warehouse, so BOTH audiences get the read and
BOTH get the transition grant; add/delete follow `inventory.stock` alone because nobody
creates or deletes a transfer by hand - the confirmation writes it and the state machine
retires it.
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "419_stock_transfers"
down_revision = "418_merge_oi_product_sets"
branch_labels = None
depends_on = None


# (target slug, source slugs whose holders get it, name, description). Name and description
# match `_crud("inventory", "stock_transfers", "Stock Transfers")` in
# `app/rbac/permission_registry.py`, so the create-if-absent branch cannot drift from what
# the registry sync would have written.
_SWEEP = (
    (
        "inventory.stock_transfers.view",
        ("inventory.stock.view", "projects.projects.view"),
        "View Stock Transfers",
        "Permission to view Stock Transfers.",
    ),
    (
        "inventory.stock_transfers.add",
        ("inventory.stock.add",),
        "Add Stock Transfers",
        "Permission to add Stock Transfers.",
    ),
    (
        "inventory.stock_transfers.edit",
        ("inventory.stock.edit", "projects.projects.edit"),
        "Edit Stock Transfers",
        "Permission to edit Stock Transfers.",
    ),
    (
        "inventory.stock_transfers.delete",
        ("inventory.stock.delete",),
        "Delete Stock Transfers",
        "Permission to delete Stock Transfers.",
    ),
)


def _has_table(bind) -> bool:
    return sa.inspect(bind).has_table("stock_transfers", schema="projects")


def upgrade() -> None:
    bind = op.get_bind()

    if not _has_table(bind):
        op.create_table(
            "stock_transfers",
            sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
            sa.Column("company_id", postgresql.UUID(as_uuid=False), nullable=True),
            sa.Column("transfer_no", sa.String(length=20), nullable=False),
            sa.Column("so_line_id", postgresql.UUID(as_uuid=False), nullable=True),
            sa.Column(
                "project_sales_order_id",
                postgresql.UUID(as_uuid=False),
                nullable=False,
            ),
            sa.Column(
                "supply_decision_id", postgresql.UUID(as_uuid=False), nullable=True
            ),
            sa.Column("product_id", postgresql.UUID(as_uuid=False), nullable=False),
            sa.Column(
                "from_warehouse_id", postgresql.UUID(as_uuid=False), nullable=False
            ),
            sa.Column(
                "to_warehouse_id", postgresql.UUID(as_uuid=False), nullable=False
            ),
            sa.Column("qty", sa.Numeric(precision=15, scale=4), nullable=False),
            sa.Column("kind", sa.String(length=16), nullable=False),
            sa.Column(
                "state", sa.String(length=16), server_default="proposed", nullable=False
            ),
            sa.Column(
                "proposed_at",
                sa.DateTime(timezone=False),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column("approved_by", sa.String(length=100), nullable=True),
            sa.Column("approved_at", sa.DateTime(timezone=False), nullable=True),
            sa.Column("moved_by", sa.String(length=100), nullable=True),
            sa.Column("moved_at", sa.DateTime(timezone=False), nullable=True),
            sa.Column("cancelled_reason", sa.Text(), nullable=True),
            sa.Column("autocount_ref", sa.String(length=80), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=False),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=False),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
            # Unqualified: the CORE `public.sales_order_lines`, not the module table of the
            # same bare name (see `app.models.project_so`'s header).
            sa.ForeignKeyConstraint(["so_line_id"], ["sales_order_lines.id"], ondelete="SET NULL"),
            sa.ForeignKeyConstraint(
                ["project_sales_order_id"], ["projects.sales_orders.id"], ondelete="CASCADE"
            ),
            sa.ForeignKeyConstraint(
                ["supply_decision_id"],
                ["projects.so_supply_decisions.id"],
                ondelete="SET NULL",
            ),
            sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
            sa.ForeignKeyConstraint(
                ["from_warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"
            ),
            sa.ForeignKeyConstraint(["to_warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
            sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
            sa.ForeignKeyConstraint(["moved_by"], ["users.id"], ondelete="SET NULL"),
            sa.UniqueConstraint(
                "company_id", "transfer_no", name="uq_project_stock_transfer_no"
            ),
            schema="projects",
        )

    # `CompanyScopedMixin.company_id` declares `index=True`, which `create_table` above does
    # not emit - named the way SQLAlchemy would have named it, so a schema built by
    # `Base.metadata.create_all` (the test fixture) and one built by this migration match.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_stock_transfers_company_id "
        "ON projects.stock_transfers (company_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_stock_transfers_order "
        "ON projects.stock_transfers (project_sales_order_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_stock_transfers_decision "
        "ON projects.stock_transfers (supply_decision_id, state)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_stock_transfers_line "
        "ON projects.stock_transfers (so_line_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_project_stock_transfers_state "
        "ON projects.stock_transfers (state)"
    )

    # --- the permission rows and the grant sweep ---------------------------------------
    for target, _sources, name, description in _SWEEP:
        bind.execute(
            sa.text(
                """
                INSERT INTO user_permissions (id, slug, name, description, created_at)
                SELECT gen_random_uuid()::text, :slug, :name, :descr, now()
                WHERE NOT EXISTS (SELECT 1 FROM user_permissions WHERE slug = :slug)
                """
            ),
            {"slug": target, "name": name, "descr": description},
        )

    for target, sources, _name, _descr in _SWEEP:
        for source in sources:
            bind.execute(
                sa.text(
                    """
                    INSERT INTO user_role_permissions (id, role_id, permission_id, assigned_at)
                    SELECT gen_random_uuid()::text, rp.role_id, tgt.id, now()
                    FROM user_role_permissions rp
                    JOIN user_permissions src
                      ON src.id = rp.permission_id AND src.slug = :source
                    CROSS JOIN user_permissions tgt
                    WHERE tgt.slug = :target
                    ON CONFLICT (role_id, permission_id) DO NOTHING
                    """
                ),
                {"source": source, "target": target},
            )


def downgrade() -> None:
    """Drop the table, and take back exactly the grants this migration made.

    Mirrored rather than blanket, like `414_product_set_grant_sweep`: a target grant is
    removed only where the role also holds one of the source grants that produced it. The
    permission ROWS stay - the registry sync would put them straight back, and deleting
    them would strand any grant made by hand.
    """
    bind = op.get_bind()

    for target, sources, _name, _descr in _SWEEP:
        for source in sources:
            bind.execute(
                sa.text(
                    """
                    DELETE FROM user_role_permissions grant_row
                    USING user_permissions tgt
                    WHERE grant_row.permission_id = tgt.id
                      AND tgt.slug = :target
                      AND EXISTS (
                          SELECT 1
                          FROM user_role_permissions src_rp
                          JOIN user_permissions src
                            ON src.id = src_rp.permission_id AND src.slug = :source
                          WHERE src_rp.role_id = grant_row.role_id
                      )
                    """
                ),
                {"source": source, "target": target},
            )

    if _has_table(bind):
        op.drop_table("stock_transfers", schema="projects")
