"""SPO documents live in `spo_allocations`, not in `purchase_orders`

Revision ID: 420_spo_docs_in_allocations
Revises: 419_stock_transfers
Create Date: 2026-08-26 12:00:00.000000

`PLAN-scm-cs-planning-uat.md` section K, captain's Q6 ruling of 25 Aug 2026 (option 1, 26
Aug): a shipping order is not a purchase order, and it moves PHYSICALLY.

Why it matters, measured on the captain's own database: `scm.on_order_v` reads
`spo_allocations` and nothing else, and that table held ONE row, while 3,983 `SPO-`
documents (79,968 lines) sat in `purchase_orders`. Every shipping order was therefore
invisible as incoming supply, and rung 1 of the fulfilment ladder - "an SPO already on its
way" - could never fire for anything. Netting a document family out of the supply read model
by filing it in the wrong table is not a filter somebody forgot; it is the table being wrong.

What moves, and what each family costs:

| `source_system` | documents | lines | lines with no warehouse |
| --- | --- | --- | --- |
| `scm_spo_history` | 3,517 | 74,016 | 1,283 |
| `scm_po_history`  |   414 |  5,237 | 5,237 (the banded report names no location) |
| `scm_upload`      |    52 |    715 | 0 (the only OPEN lines in the set) |

Routing is by the `SPO-` NUMBER, never by the stamp: the number is what the business quotes
and what cannot be typed wrong without being visibly wrong (the same authority
`po_listing_reader.doc_family` uses, and the reason nine rows of the 2023 book disagree with
AutoCount's own `Shipping Order` flag).

Three shape changes make the move possible, and each is a fact about the data:

  * `inbound_shipment_id` becomes nullable - a shipping order exists before anybody books a
    container for it.
  * `warehouse_id` becomes nullable and `location_code` arrives - 6,520 lines name a stock
    location we do not hold. The raw code is kept so nothing is lost, and `on_order_v`
    requires a warehouse, so such a row is incoming supply NOWHERE rather than everywhere.
  * the unique key moves from `(spo_number, product_id, warehouse_id)` to
    `(company_id, spo_number, spo_line_number)` - the old triple forbade the 13,305 repeated
    (document, product, location) groups the book actually contains, which are two containers
    of one item on one shipping order.

Hand-written rather than autogenerated, and guarded throughout: the shared dev database is a
prod copy that converges through `create_all` rather than `alembic upgrade` (see
`sorento_crm_backend/CLAUDE.md`), so every step must be a no-op when it has already happened.

The data half is exposed as functions so the test suite can drive it on a scratch schema
without running the whole chain. It refuses loudly rather than orphaning: every foreign key
that points INTO an SPO document is counted first, and anything with nowhere to go raises
with its counts instead of being silently NULLed by `ON DELETE SET NULL`.

`scm.order_link_claim` is the one exception, and it is not an orphan: the claim holds both
document numbers as TEXT and `po_line_id` is only the resolver's cache of where that number
landed (see the model docstring). 12,393 claims name an SPO, so that cache is cleared and
their `resolved_at` with it, and the claim is then re-pointed at the ALLOCATION through a
new column, `spo_allocation_id`. Without that column the claim could never resolve again -
`sales_order_service.with_links` reads `resolved_at`, so 2,989 sales orders would have read
"awaiting purchase order" for ever - and `po_history_service` would have gone on writing
more claims that could not. The downgrade drops the column and re-resolves `po_line_id` by
the resolver's own rule.

**If the migration refuses**, the counts name the table and the column. There is no column
on any of those tables that could point at an allocation, so the remediation is to deal with
the rows before re-running, not to widen the migration:

  * `scm.shipment_line_spo_link.purchase_order_id` / `.purchase_order_line_id` - a packing
    list that was matched to an SPO filed as a purchase order. Delete the link rows for
    those SPO documents (`consolidated_packing_list` rebuilds them from the shipment lines
    on the next match run) and re-run.
  * `picking_lines.po_line_id` - a GRN drawn against an SPO line. NULL the column on those
    rows; the GRN keeps its `spo_number_raw` and `grn_spo_matching` re-places it against the
    allocation, which is the link it should have had.
  * `projects.order_inquiry_rows.po_line_id` / `scm.loading_plan_line.po_line_id` /
    `scm.plan_exception.purchase_order_id` - all measured 0. If one is not, the row was
    placed on a document that is not a purchase order and belongs on the SPO through
    section I's Link SPO, so clear the column and re-place it there.

Not restored by the downgrade: each SPO document's own row id (nothing references it -
measured 0 on both `scm.shipment_line_spo_link.purchase_order_id` and
`scm.plan_exception.purchase_order_id`) and its `source_ref`. Every LINE id round-trips,
because an allocation is created carrying the id of the line it replaces.
"""
import logging

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "420_spo_docs_in_allocations"
down_revision = "419_stock_transfers"
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")

#: The stamps the move carries across, for the record. The DOWNGRADE does not test for
#: these three: it moves back every `SPO-` row whose `source_system` is set at all, because
#: the mover routes on the NUMBER and would carry a document stamped something nobody has
#: written yet. A row with NO stamp was raised inside this system
#: (`spo_conversion_service`) and has never lived in `purchase_orders`, so it stays.
MOVED_SOURCES = ("scm_spo_history", "scm_po_history", "scm_upload")

#: Every foreign key that can point INTO an SPO document, with the schema its table lives in.
#: Checked before the move: a reference with nowhere to go stops the migration rather than
#: being cascaded or NULLed behind the operator's back. All eight measured 0 on the dev copy
#: except `scm.order_link_claim`, which is handled explicitly below.
_LINE_REFERENCES = (
    (None, "picking_lines", "po_line_id"),
    (None, "spo_allocations", "po_line_id"),
    ("projects", "order_inquiry_rows", "po_line_id"),
    ("scm", "loading_plan_line", "po_line_id"),
    ("scm", "shipment_line_spo_link", "purchase_order_line_id"),
)
_DOCUMENT_REFERENCES = (
    ("scm", "shipment_line_spo_link", "purchase_order_id"),
    ("scm", "plan_exception", "purchase_order_id"),
)

#: Shipment states that mean the goods have landed. Kept verbatim from migration 337, whose
#: view body this one replaces.
_RECEIVED_SHIPMENT_STATES = (
    "('fully_received', 'closed', 'received', 'completed', 'cancelled')"
)


def _schema(bind, module: str) -> str:
    """Where a module's tables live, for RAW SQL, under BOTH substrates.

    `schema_translate_map` rewrites ORM and `Table` constructs only, so a hard-coded
    `scm.order_link_claim` in a `text()` statement would reach the REAL schema from a test
    running on a scratch copy - writing live data while the test believed it was isolated
    (the trap `test_migration_400_oi_place_on_po.py` documents from the other direction).
    The scratch schemas are named `<default>_scm` / `<default>_projects`
    (`tests/_pg_fixture.py`), so the current default schema is enough to tell the two apart.
    """
    current = bind.exec_driver_sql("SELECT current_schema()").scalar()
    return module if current in (None, "public") else f"{current}_{module}"


def _default_schema(bind) -> str:
    """Where the unqualified tables live: `public` normally, the scratch schema in a test."""
    return bind.exec_driver_sql("SELECT current_schema()").scalar()


def _has_column(bind, table: str, column: str, schema: str | None = None) -> bool:
    return bool(
        bind.execute(
            sa.text(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = :schema
                  AND table_name = :table AND column_name = :column
                """
            ),
            {"schema": schema or _default_schema(bind), "table": table, "column": column},
        ).first()
    )


def _has_constraint(bind, name: str, schema: str | None = None) -> bool:
    return bool(
        bind.execute(
            sa.text(
                """
                SELECT 1 FROM pg_constraint c
                JOIN pg_namespace n ON n.oid = c.connamespace
                WHERE n.nspname = :schema AND c.conname = :name
                """
            ),
            {"schema": schema or _default_schema(bind), "name": name},
        ).first()
    )


def _has_index(bind, name: str, schema: str | None = None) -> bool:
    return bool(
        bind.execute(
            sa.text(
                """
                SELECT 1 FROM pg_indexes
                WHERE schemaname = :schema AND indexname = :name
                """
            ),
            {"schema": schema or _default_schema(bind), "name": name},
        ).first()
    )


def _table_exists(bind, schema: str, table: str) -> bool:
    return bool(
        bind.execute(
            sa.text(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = :schema AND table_name = :table"
            ),
            {"schema": schema, "table": table},
        ).first()
    )


def _qualified(bind, schema, table: str) -> str:
    return f'"{_schema(bind, schema)}"."{table}"' if schema else f'"{table}"'


# --------------------------------------------------------------------------- schema


def widen_allocations(bind) -> None:
    """The shape an SPO document needs. Idempotent, column by column."""
    if not _has_column(bind, "spo_allocations", "location_code"):
        op.add_column("spo_allocations", sa.Column("location_code", sa.String(50), nullable=True))
    if not _has_column(bind, "spo_allocations", "source_system"):
        op.add_column("spo_allocations", sa.Column("source_system", sa.String(50), nullable=True))
    if not _has_column(bind, "spo_allocations", "issue_date"):
        op.add_column("spo_allocations", sa.Column("issue_date", sa.Date(), nullable=True))
    if not _has_column(bind, "spo_allocations", "expected_date"):
        op.add_column("spo_allocations", sa.Column("expected_date", sa.Date(), nullable=True))
    if not _has_column(bind, "spo_allocations", "unit_cost"):
        op.add_column("spo_allocations", sa.Column("unit_cost", sa.Numeric(12, 2), nullable=True))
    if not _has_column(bind, "spo_allocations", "currency"):
        op.add_column("spo_allocations", sa.Column("currency", sa.String(3), nullable=True))
    if not _has_column(bind, "spo_allocations", "line_status"):
        op.add_column(
            "spo_allocations",
            sa.Column("line_status", sa.String(50), nullable=False, server_default="open"),
        )
    if not _has_column(bind, "spo_allocations", "supplier_id"):
        op.add_column(
            "spo_allocations",
            sa.Column("supplier_id", postgresql.UUID(as_uuid=False), nullable=True),
        )
    if not _has_constraint(bind, "fk_spo_allocations_supplier_id"):
        op.create_foreign_key(
            "fk_spo_allocations_supplier_id", "spo_allocations", "suppliers",
            ["supplier_id"], ["id"], ondelete="SET NULL",
        )

    # NULLABLE, both of them. Postgres is a no-op when the column is already nullable, so
    # this needs no guard of its own.
    op.alter_column("spo_allocations", "inbound_shipment_id", nullable=True)
    op.alter_column("spo_allocations", "warehouse_id", nullable=True)

    if _has_constraint(bind, "uk_spo_allocations_spo_number_product_warehouse"):
        op.drop_constraint(
            "uk_spo_allocations_spo_number_product_warehouse", "spo_allocations", type_="unique"
        )
    if not _has_index(bind, "ix_spo_allocations_spo_product_warehouse"):
        op.create_index(
            "ix_spo_allocations_spo_product_warehouse", "spo_allocations",
            ["spo_number", "product_id", "warehouse_id"],
        )
    if not _has_constraint(bind, "uk_spo_allocations_company_spo_line"):
        # After the line numbers exist, or the constraint fails on the rows that have none.
        backfill_line_numbers(bind)
        op.create_unique_constraint(
            "uk_spo_allocations_company_spo_line", "spo_allocations",
            ["company_id", "spo_number", "spo_line_number"],
        )


def add_claim_spo_side(bind) -> None:
    """`scm.order_link_claim.spo_allocation_id`: the purchase side of an SPO claim.

    The claim resolves a document NUMBER to the row that number names, and an `SPO-` number
    now names a row in `spo_allocations`. Without a column for that half the 12,393 claims
    carrying one could never resolve again - `sales_order_service.with_links` reads
    `resolved_at`, so 2,989 sales orders would have read "awaiting purchase order" for ever,
    and `po_history_service` would have gone on writing more of them.

    Guarded step by step: this migration is applied by hand on a shared dev database, and it
    has already been applied there once, so it must add only what is missing.
    """
    scm = _schema(bind, "scm")
    if not _has_column(bind, "order_link_claim", "spo_allocation_id", schema=scm):
        op.add_column(
            "order_link_claim",
            sa.Column("spo_allocation_id", postgresql.UUID(as_uuid=False), nullable=True),
            schema=scm,
        )
    if not _has_constraint(bind, "fk_scm_order_link_claim_spo_allocation", schema=scm):
        op.create_foreign_key(
            "fk_scm_order_link_claim_spo_allocation", "order_link_claim", "spo_allocations",
            ["spo_allocation_id"], ["id"], ondelete="SET NULL",
            source_schema=scm, referent_schema=_default_schema(bind),
        )
    if not _has_index(bind, "ix_scm_order_link_claim_spo_allocation", schema=scm):
        op.create_index(
            "ix_scm_order_link_claim_spo_allocation", "order_link_claim",
            ["spo_allocation_id"], schema=scm,
        )


def repoint_spo_claims(bind) -> dict:
    """Point every claim naming an `SPO-` document at the allocation it now means.

    The same rule `order_link_service._purchase_side` applies, in SQL: a claim that names an
    ITEM resolves to that item's line on the document, one that names none (a `**SO:174830**`
    note in a PO export, which cannot say which line it describes) takes the document's first
    line as its anchor. Lowest line number wins where a document states the same product
    twice, so a re-run picks the same row rather than whichever Postgres returned first.

    Idempotent: only claims with no SPO side yet are touched. `resolved_at` comes back only
    where the sales side was already found, because resolved still has to mean both halves.
    """
    scm = _schema(bind, "scm")
    if not _table_exists(bind, scm, "order_link_claim"):
        return {"with_item": 0, "item_less": 0}
    if not _has_column(bind, "order_link_claim", "spo_allocation_id", schema=scm):
        return {"with_item": 0, "item_less": 0}

    with_item = bind.execute(
        sa.text(
            f"""
            WITH pick AS (
                SELECT DISTINCT ON (sa.company_id, sa.spo_number, p.product_code)
                       sa.company_id, sa.spo_number, p.product_code, sa.id
                FROM spo_allocations sa
                JOIN products p ON p.id = sa.product_id
                WHERE sa.spo_number LIKE 'SPO-%'
                ORDER BY sa.company_id, sa.spo_number, p.product_code,
                         sa.spo_line_number NULLS LAST, sa.id
            )
            UPDATE "{scm}"."order_link_claim" c
            SET spo_allocation_id = pick.id,
                resolved_at = CASE WHEN c.so_line_id IS NOT NULL AND c.resolved_at IS NULL
                                   THEN now() ELSE c.resolved_at END
            FROM pick
            WHERE c.spo_allocation_id IS NULL
              AND c.item_code IS NOT NULL
              AND c.po_number = pick.spo_number
              AND c.item_code = pick.product_code
              AND c.company_id = pick.company_id
            """
        )
    ).rowcount or 0

    item_less = bind.execute(
        sa.text(
            f"""
            WITH pick AS (
                SELECT DISTINCT ON (sa.company_id, sa.spo_number)
                       sa.company_id, sa.spo_number, sa.id
                FROM spo_allocations sa
                WHERE sa.spo_number LIKE 'SPO-%'
                ORDER BY sa.company_id, sa.spo_number,
                         sa.spo_line_number NULLS LAST, sa.id
            )
            UPDATE "{scm}"."order_link_claim" c
            SET spo_allocation_id = pick.id,
                resolved_at = CASE WHEN c.so_line_id IS NOT NULL AND c.resolved_at IS NULL
                                   THEN now() ELSE c.resolved_at END
            FROM pick
            WHERE c.spo_allocation_id IS NULL
              AND c.item_code IS NULL
              AND c.po_number = pick.spo_number
              AND c.company_id = pick.company_id
            """
        )
    ).rowcount or 0

    logger.info(
        "migration 420: re-pointed %s SPO claims by item and %s by document",
        with_item, item_less,
    )
    return {"with_item": with_item, "item_less": item_less}


def backfill_line_numbers(bind) -> int:
    """Give every allocation that names an SPO a line number within that SPO.

    The existing writer (`SPOAllocationService.create_allocation`) never set one, so the new
    unique key would treat all of a document's rows as the same line. Numbered after the
    highest number the document already carries, in creation order, so re-running this adds
    nothing and moves nothing.
    """
    result = bind.execute(
        sa.text(
            """
            WITH numbered AS (
                SELECT sa.id,
                       COALESCE(mx.max_no, 0)
                         + row_number() OVER (PARTITION BY sa.company_id, sa.spo_number
                                              ORDER BY sa.created_at, sa.id) AS line_no
                FROM spo_allocations sa
                LEFT JOIN (
                    SELECT company_id, spo_number, MAX(spo_line_number) AS max_no
                    FROM spo_allocations
                    WHERE spo_line_number IS NOT NULL
                    GROUP BY company_id, spo_number
                ) mx ON mx.company_id = sa.company_id AND mx.spo_number = sa.spo_number
                WHERE sa.spo_number IS NOT NULL AND sa.spo_line_number IS NULL
            )
            UPDATE spo_allocations sa
            SET spo_line_number = numbered.line_no
            FROM numbered
            WHERE numbered.id = sa.id
            """
        )
    )
    return result.rowcount or 0


# ----------------------------------------------------------------------------- data


def reference_counts(bind) -> dict:
    """How many rows outside `purchase_orders` point at an SPO document, per foreign key."""
    counts: dict = {}
    spo_lines = """
        SELECT pl.id FROM purchase_order_lines pl
        JOIN purchase_orders po ON po.id = pl.purchase_order_id
        WHERE po.po_number LIKE 'SPO-%'
    """
    spo_docs = "SELECT id FROM purchase_orders WHERE po_number LIKE 'SPO-%'"
    default_schema = _default_schema(bind)
    for reference in _LINE_REFERENCES + _DOCUMENT_REFERENCES:
        schema, table, column = reference
        where = _schema(bind, schema) if schema else default_schema
        if not _table_exists(bind, where, table):
            continue
        source = spo_docs if reference in _DOCUMENT_REFERENCES else spo_lines
        name = f"{schema}.{table}.{column}" if schema else f"{table}.{column}"
        counts[name] = bind.execute(
            sa.text(
                f"SELECT count(*) FROM {_qualified(bind, schema, table)} t "
                f"WHERE t.{column} IN ({source})"
            )
        ).scalar() or 0
    return counts


def move_spo_documents(bind) -> dict:
    """Every `SPO-` document in `purchase_orders`, as `spo_allocations` rows. Set-based.

    One allocation per purchase-order LINE, carrying that line's own id: nothing else
    references those ids today, and keeping them is what lets the downgrade put the same
    lines back rather than a copy of them.
    """
    blocking = {name: n for name, n in reference_counts(bind).items() if n}
    if blocking:
        # Loudly, with the numbers. There is no column on any of these tables that could
        # name an allocation, so re-pointing is not available and the alternatives are to
        # orphan the row or to cascade the delete into it. Neither is this migration's
        # decision to make silently.
        raise RuntimeError(
            "SPO documents are referenced by rows that cannot be re-pointed at an "
            f"allocation: {blocking}. Resolve them before running migration 420."
        )

    expected = bind.execute(
        sa.text(
            """
            SELECT count(*) FROM purchase_order_lines pl
            JOIN purchase_orders po ON po.id = pl.purchase_order_id
            WHERE po.po_number LIKE 'SPO-%'
            """
        )
    ).scalar() or 0

    moved = bind.execute(
        sa.text(
            """
            WITH src AS (
                SELECT pl.id, pl.product_id, pl.warehouse_id, pl.qty_ordered, pl.qty_received,
                       pl.unit_cost, pl.expected_date, pl.line_status, pl.created_at,
                       pl.purchase_order_id, pl.company_id,
                       COALESCE(pl.currency, po.currency) AS currency,
                       po.po_number, po.issue_date, po.supplier_id, po.source_system,
                       w.warehouse_code,
                       NULLIF(regexp_replace(COALESCE(pl.source_ref, ''), '[^0-9]', '', 'g'), '')::int AS ref_no
                FROM purchase_order_lines pl
                JOIN purchase_orders po ON po.id = pl.purchase_order_id
                LEFT JOIN warehouses w ON w.id = pl.warehouse_id
                WHERE po.po_number LIKE 'SPO-%'
            ), numbered AS (
                SELECT src.*,
                       COALESCE(
                           src.ref_no,
                           -- The live outstanding extract states no line number at all
                           -- (715 lines). They are numbered after whatever the document
                           -- does state, in creation order, so a re-upload of the same
                           -- document lands on the same numbers.
                           COALESCE(MAX(src.ref_no) OVER (PARTITION BY src.purchase_order_id), 0)
                           + row_number() OVER (
                               PARTITION BY src.purchase_order_id, (src.ref_no IS NULL)
                               ORDER BY src.created_at, src.id
                           )
                       ) AS line_no
                FROM src
            )
            INSERT INTO spo_allocations (
                id, spo_number, spo_line_number, product_id, warehouse_id, location_code,
                allocated_quantity, quantity_received, quantity_rejected, receipt_status,
                line_status, source_system, issue_date, expected_date, supplier_id,
                unit_cost, currency, company_id, created_at, synced_to_excel
            )
            SELECT n.id, n.po_number, n.line_no, n.product_id, n.warehouse_id, n.warehouse_code,
                   ROUND(n.qty_ordered)::int, ROUND(COALESCE(n.qty_received, 0))::int, 0,
                   CASE
                       WHEN COALESCE(n.qty_received, 0) >= n.qty_ordered THEN 'fully_received'
                       WHEN COALESCE(n.qty_received, 0) > 0 THEN 'partial_received'
                       ELSE 'pending'
                   END,
                   n.line_status, n.source_system, n.issue_date, n.expected_date, n.supplier_id,
                   n.unit_cost, n.currency, n.company_id, n.created_at, false
            FROM numbered n
            ON CONFLICT DO NOTHING
            """
        )
    ).rowcount or 0

    if moved != expected:
        # `ON CONFLICT DO NOTHING` is what makes a re-run safe, and it is also the one way
        # this move could lose a line without saying so: a line whose
        # (company, document, line number) an existing allocation already holds would
        # simply not arrive. The delete below is about to remove the source, so the
        # discrepancy is checked while both sides still exist.
        raise RuntimeError(
            f"migration 420: {expected} SPO lines to move but {moved} allocations were "
            f"written; {expected - moved} collided with rows already in spo_allocations. "
            "Nothing has been deleted."
        )

    scm = _schema(bind, "scm")
    cleared = 0
    if _table_exists(bind, scm, "order_link_claim"):
        # The claim keeps both document numbers, which is its stated identity; only the
        # resolver's cache of where the PO number landed is cleared, and `resolved_at` with
        # it so "resolved" still means "both halves found".
        cleared = bind.execute(
            sa.text(
                f"""
                UPDATE "{scm}"."order_link_claim" c
                SET po_line_id = NULL, resolved_at = NULL
                FROM purchase_order_lines pl
                JOIN purchase_orders po ON po.id = pl.purchase_order_id
                WHERE pl.id = c.po_line_id AND po.po_number LIKE 'SPO-%'
                """
            )
        ).rowcount or 0

    lines = bind.execute(
        sa.text(
            """
            DELETE FROM purchase_order_lines pl
            USING purchase_orders po
            WHERE po.id = pl.purchase_order_id AND po.po_number LIKE 'SPO-%'
            """
        )
    ).rowcount or 0
    docs = bind.execute(
        sa.text("DELETE FROM purchase_orders WHERE po_number LIKE 'SPO-%'")
    ).rowcount or 0

    logger.info(
        "migration 420: moved %s SPO lines into spo_allocations, deleted %s lines and "
        "%s documents, cleared %s order-link claims",
        moved, lines, docs, cleared,
    )
    return {"allocations": moved, "lines_deleted": lines, "documents_deleted": docs,
            "claims_cleared": cleared}


def restore_spo_documents(bind) -> dict:
    """Put the stamped allocations back as `purchase_orders` / `purchase_order_lines`.

    A document is born `active` when any of its lines is still open and `closed` otherwise -
    which is what it was, because history is written closed and the outstanding extract's
    lines are the only open ones in the set.
    """
    docs = bind.execute(
        sa.text(
            f"""
            INSERT INTO purchase_orders (
                id, po_number, supplier_id, issue_date, status, currency,
                source_system, company_id
            )
            SELECT gen_random_uuid(), sa.spo_number, MIN(sa.supplier_id::text)::uuid,
                   MIN(sa.issue_date),
                   CASE WHEN bool_or(COALESCE(sa.line_status, 'open') = 'open')
                        THEN 'active' ELSE 'closed' END,
                   MIN(sa.currency), MIN(sa.source_system), sa.company_id
            FROM spo_allocations sa
            WHERE sa.spo_number IS NOT NULL
              AND sa.source_system IS NOT NULL
            GROUP BY sa.company_id, sa.spo_number
            """
        )
    ).rowcount or 0

    lines = bind.execute(
        sa.text(
            """
            INSERT INTO purchase_order_lines (
                id, purchase_order_id, product_id, warehouse_id, qty_ordered, qty_received,
                unit_cost, currency, expected_date, line_status, source_system, source_ref,
                created_at, company_id
            )
            SELECT sa.id, po.id, sa.product_id, sa.warehouse_id, sa.allocated_quantity,
                   COALESCE(sa.quantity_received, 0), sa.unit_cost, sa.currency,
                   sa.expected_date, COALESCE(sa.line_status, 'open'), sa.source_system,
                   sa.spo_line_number::text, sa.created_at, sa.company_id
            FROM spo_allocations sa
            JOIN purchase_orders po
              ON po.po_number = sa.spo_number AND po.company_id = sa.company_id
            WHERE sa.spo_number IS NOT NULL
              AND sa.source_system IS NOT NULL
            """
        )
    ).rowcount or 0

    scm = _schema(bind, "scm")
    claims = 0
    if _table_exists(bind, scm, "order_link_claim"):
        # The resolver's own rule (`order_link_service._resolve`): a claim naming an item
        # takes that item's line on the document, one naming none takes the document's
        # first line. Deterministic by line number, where the resolver takes whichever the
        # query returned first.
        claims = bind.execute(
            sa.text(
                f"""
                UPDATE "{scm}"."order_link_claim" c
                SET po_line_id = pick.line_id,
                    spo_allocation_id = NULL,
                    resolved_at = CASE WHEN c.so_line_id IS NOT NULL THEN now() ELSE NULL END
                FROM (
                    SELECT DISTINCT ON (po.po_number, p.product_code)
                           po.po_number, p.product_code, pl.id AS line_id
                    FROM purchase_order_lines pl
                    JOIN purchase_orders po ON po.id = pl.purchase_order_id
                    JOIN products p ON p.id = pl.product_id
                    WHERE po.po_number LIKE 'SPO-%'
                    ORDER BY po.po_number, p.product_code, pl.source_ref, pl.id
                ) pick
                WHERE c.po_line_id IS NULL
                  AND c.item_code IS NOT NULL
                  AND c.po_number = pick.po_number
                  AND c.item_code = pick.product_code
                """
            )
        ).rowcount or 0
        # The item-less half, which the upgrade also re-points: a `**SO:174830**` note in a
        # PO export names no item, so it anchors on the document's first line. Nought of
        # them name an SPO on the captain's book today, which is exactly why it has to be
        # written rather than left for the day one does.
        claims += bind.execute(
            sa.text(
                f"""
                UPDATE "{scm}"."order_link_claim" c
                SET po_line_id = pick.line_id,
                    spo_allocation_id = NULL,
                    resolved_at = CASE WHEN c.so_line_id IS NOT NULL THEN now() ELSE NULL END
                FROM (
                    SELECT DISTINCT ON (po.po_number)
                           po.po_number, pl.id AS line_id
                    FROM purchase_order_lines pl
                    JOIN purchase_orders po ON po.id = pl.purchase_order_id
                    WHERE po.po_number LIKE 'SPO-%'
                    ORDER BY po.po_number, pl.source_ref, pl.id
                ) pick
                WHERE c.po_line_id IS NULL
                  AND c.item_code IS NULL
                  AND c.po_number = pick.po_number
                """
            )
        ).rowcount or 0

    removed = bind.execute(
        sa.text(
            "DELETE FROM spo_allocations WHERE spo_number IS NOT NULL "
            "AND source_system IS NOT NULL"
        )
    ).rowcount or 0

    logger.info(
        "migration 420 downgrade: restored %s documents and %s lines, re-resolved %s claims, "
        "removed %s allocations", docs, lines, claims, removed,
    )
    return {"documents": docs, "lines": lines, "claims": claims, "allocations_removed": removed}


# ----------------------------------------------------------------------------- view


def on_order_from_spo_documents(bind) -> str:
    """`scm.on_order_v` with SPO documents in it.

    Two changes from migration 337, and one rule each:

      * LEFT JOIN to the shipment - a shipping order with no container booked is still
        stock on its way, and the inner join dropped every one of them.
      * `warehouse_id IS NOT NULL` - 6,520 lines name a location we do not hold, and supply
        that cannot be placed must not be counted at a location. It is counted NOWHERE
        rather than everywhere; `location_code` keeps the evidence for a human to fix.

    `line_status` joins the predicate for the same reason the purchase-order view carried
    it: a closed line has left the book. History is written closed AND fully received, so it
    fails both halves and is excluded by construction rather than by a filter to remember.
    """
    return f"""
CREATE OR REPLACE VIEW "{_schema(bind, 'scm')}".on_order_v AS
SELECT sa.product_id,
       sa.warehouse_id,
       SUM((sa.allocated_quantity - COALESCE(sa.quantity_received, 0))::numeric) AS on_order
FROM spo_allocations sa
LEFT JOIN inbound_shipments s ON s.id = sa.inbound_shipment_id
-- Guard, not decoration: `spo_allocations_product_id_fkey` is NOT VALID, so rows predating
-- it were never checked and an orphan in a read model fails the whole analytics run.
JOIN products pr ON pr.id = sa.product_id
WHERE sa.warehouse_id IS NOT NULL
  AND (s.id IS NULL OR s.shipment_status NOT IN {_RECEIVED_SHIPMENT_STATES})
  AND COALESCE(sa.line_status, 'open') = 'open'
  -- `fully_received` is the value the column's CHECK constraint allows. Migration 337
  -- tested `<> 'received'`, which no row has ever carried, so the test could never be
  -- false: a filter that looks like a guard and is not one. Both spellings are listed so
  -- the honest test survives whichever a future writer picks.
  AND COALESCE(sa.receipt_status, 'pending') NOT IN ('fully_received', 'received')
  AND sa.allocated_quantity > COALESCE(sa.quantity_received, 0)
  -- STALENESS (`app/services/scm/spo_supply.py`, the one copy of this rule in Python).
  -- A shipping order nobody has booked a container for, whose promised date has passed,
  -- is not supply: all 715 open SPO lines on the captain's book are past-dated, the
  -- oldest by two years, and no feed refreshes them. A shipment-backed row is never
  -- stale, because its arrival is tracked; a row with no date at all is not stale
  -- either, because nothing says its date has passed.
  AND (sa.inbound_shipment_id IS NOT NULL
       OR sa.expected_date IS NULL
       OR sa.expected_date >= CURRENT_DATE)
GROUP BY sa.product_id, sa.warehouse_id;
"""


def on_order_from_shipped_allocations(bind) -> str:
    """Migration 337's body, for the downgrade. Kept verbatim apart from the schema name."""
    return f"""
CREATE OR REPLACE VIEW "{_schema(bind, 'scm')}".on_order_v AS
SELECT sa.product_id,
       sa.warehouse_id,
       SUM((sa.allocated_quantity - COALESCE(sa.quantity_received, 0))::numeric) AS on_order
FROM spo_allocations sa
JOIN inbound_shipments s ON s.id = sa.inbound_shipment_id
JOIN products pr ON pr.id = sa.product_id
WHERE s.shipment_status NOT IN {_RECEIVED_SHIPMENT_STATES}
  AND sa.receipt_status <> 'received'
  AND sa.allocated_quantity > COALESCE(sa.quantity_received, 0)
GROUP BY sa.product_id, sa.warehouse_id;
"""


# -------------------------------------------------------------------------- alembic


def upgrade() -> None:
    bind = op.get_bind()
    widen_allocations(bind)
    # Before the move, so the claim half exists the moment the rows it points at do.
    add_claim_spo_side(bind)
    move_spo_documents(bind)
    # After it, because a claim can only be pointed at an allocation that has been written.
    repoint_spo_claims(bind)
    op.execute(on_order_from_spo_documents(bind))


def downgrade() -> None:
    bind = op.get_bind()
    restore_spo_documents(bind)
    op.execute(on_order_from_shipped_allocations(bind))

    scm = _schema(bind, "scm")
    if _has_index(bind, "ix_scm_order_link_claim_spo_allocation", schema=scm):
        op.drop_index("ix_scm_order_link_claim_spo_allocation",
                      table_name="order_link_claim", schema=scm)
    if _has_constraint(bind, "fk_scm_order_link_claim_spo_allocation", schema=scm):
        op.drop_constraint("fk_scm_order_link_claim_spo_allocation", "order_link_claim",
                           type_="foreignkey", schema=scm)
    if _has_column(bind, "order_link_claim", "spo_allocation_id", schema=scm):
        # `restore_spo_documents` has already put `po_line_id` back on these claims by the
        # resolver's own rule, so the SPO side has nothing left to say.
        op.drop_column("order_link_claim", "spo_allocation_id", schema=scm)

    if _has_constraint(bind, "uk_spo_allocations_company_spo_line"):
        op.drop_constraint("uk_spo_allocations_company_spo_line", "spo_allocations", type_="unique")
    if _has_index(bind, "ix_spo_allocations_spo_product_warehouse"):
        op.drop_index("ix_spo_allocations_spo_product_warehouse", table_name="spo_allocations")
    if not _has_constraint(bind, "uk_spo_allocations_spo_number_product_warehouse"):
        # The old key is not a key any more: one SPO can state the same product at the same
        # location twice, and after this migration has run once the table holds rows that
        # prove it. Creating it would fail, so a collision is REPORTED and the constraint is
        # left off rather than the whole downgrade dying on data it created itself.
        collisions = bind.execute(
            sa.text(
                """
                SELECT count(*) FROM (
                    SELECT 1 FROM spo_allocations
                    WHERE spo_number IS NOT NULL AND warehouse_id IS NOT NULL
                    GROUP BY spo_number, product_id, warehouse_id
                    HAVING count(*) > 1
                ) dupes
                """
            )
        ).scalar() or 0
        if collisions:
            logger.warning(
                "migration 420 downgrade: %s (document, product, location) groups carry more "
                "than one row, so uk_spo_allocations_spo_number_product_warehouse is NOT "
                "restored. Those rows are two containers of one item and were never a "
                "duplicate; the index would refuse them.", collisions,
            )
        else:
            op.create_unique_constraint(
                "uk_spo_allocations_spo_number_product_warehouse", "spo_allocations",
                ["spo_number", "product_id", "warehouse_id"],
            )

    # NOT NULL comes back only where the data allows it. A row that arrived after the
    # upgrade with no shipment or no warehouse is real data, and a downgrade is not
    # entitled to delete it to make a constraint fit; the column stays nullable and says so.
    for column in ("inbound_shipment_id", "warehouse_id"):
        orphans = bind.execute(
            sa.text(f"SELECT count(*) FROM spo_allocations WHERE {column} IS NULL")
        ).scalar() or 0
        if orphans:
            logger.warning(
                "migration 420 downgrade: %s allocations have no %s, so the column stays "
                "nullable", orphans, column,
            )
            continue
        op.alter_column("spo_allocations", column, nullable=False)

    if _has_constraint(bind, "fk_spo_allocations_supplier_id"):
        op.drop_constraint("fk_spo_allocations_supplier_id", "spo_allocations", type_="foreignkey")
    for column in ("location_code", "source_system", "issue_date", "expected_date",
                   "supplier_id", "unit_cost", "currency", "line_status"):
        if _has_column(bind, "spo_allocations", column):
            op.drop_column("spo_allocations", column)
