"""products.is_searchable: let a placeholder row stay active and still not be a chat answer

Revision ID: 420_product_is_searchable
Revises: 419_merge_stockvis_oi
Create Date: 2026-08-25 21:30:00.000000

`SORENTO` ("DESCRIPTION WILL AMEND, FOR SORENTO AND CABANA ORDER OR SAMPLE USE
ONLY") is booked on real orders, so it must stay `is_active`, and it was shown to
a customer as an answer to "sorento black kitchen tap". A category-level flag
already exists (`product_categories.is_searchable`); this is the per-product one,
for placeholders that sit in an otherwise searchable category (SORENTOBAG is in
SAMPLE).

Default true, server default true, NOT NULL: every existing row keeps today's
behaviour and the resolve response stays byte-identical until someone turns a
product off. No backfill beyond the server default is needed for that reason.

Hand-written rather than autogenerated: the local database is a prod copy that
drifts ahead of `alembic_version`, so a raw diff would carry unrelated drift.
Issue: jayson-odoo/sorento-crm#300.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '420_product_is_searchable'
down_revision = '419_merge_stockvis_oi'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'products',
        sa.Column(
            'is_searchable',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('true'),
        ),
    )


def downgrade() -> None:
    op.drop_column('products', 'is_searchable')
