"""One order inquiry row per sales-order line, and a child table for its placements

Revision ID: 421_order_inquiry_links
Revises: 420_spo_docs_in_allocations
Create Date: 2026-08-26 15:00:00.000000

`PLAN-scm-cs-planning-uat.md` section 3.I, the captain's ruling of 25 August 2026 walking
SO414285: "1 line here should correspond to 1 line in sales order, so 1 line can be placed
by multiple PO and SPO".

Today `order_inquiry_rows` holds exactly ONE `po_line_id`, so a cascade that needs two
purchase-order lines has nowhere to put the second and SPLITS the row instead. Measured on
the captain's own database: M310-CR-PJ's 8 is two rows (5 + 3 on 202607-S0105), MSK11C's 67
is two rows (10 + 57 on 202608-S0002), B2155-NL-BLUE on SO414341 is SIX rows across two
purchase orders, and SO414285's nine sales-order lines read as eleven instructions on a
screen whose whole job is to say what to buy.

Three things change, and the third is the one with data in it.

**A child table, `projects.order_inquiry_links`.** One row per placement: the row it
belongs to, exactly ONE of `po_line_id` / `spo_allocation_id` (a CHECK, not a convention),
the quantity, who linked it and whether the cascade did. `document` is denormalised beside
the ids because both foreign keys are `ON DELETE SET NULL`, and a link that can no longer
say WHICH document it was on is not evidence of anything.

**`cited_document` on the row.** What CS NAMED for an order back - "202604-S0083",
"SPO-2026/08-0061" - as they spelled it. Not a link: a citation is what the auto-link walk
tries FIRST, before any location tier or date, and a document this system does not hold is
recorded rather than refused (AC-J2). Its own column because `po_ref` / `spo_ref` become
the DERIVED display of the first link, and a citation is a different fact from a placement.

**The verb `BORROW_SHORTFALL` becomes `ORDER_BACK`,** in the data and in the code. One verb
for the two things that are the same instruction: the hole a borrow left at the donor's
location, and the quantity CS marks ORDER BACK on the Order Inquiry Form. It is the one
verb whose links may name an `spo_allocations` row. Measured: 0 rows carry the old value on
the dev copy, so the UPDATE is a no-op there and the rename costs nothing; it is written
anyway because another database may hold some.

**The backfill merges the splits** (AC-I8). Per `(so_line_id, supply_decision_id, verb)`,
among rows in `raised` / `placed` only:

  * the OLDEST row survives and takes the SUM of the group's quantities;
  * every `placed` fragment becomes ONE link on the survivor, carrying its own quantity,
    `po_line_id`, `po_ref` as the document, and the person and time that placed it;
  * the other rows are deleted;
  * a `placed` row that was never split becomes one row plus one link, the same shape;
  * `po_ref` / `po_line_id` are cleared on every row that gained links, because from here
    they are derived from the links and a stale scalar beside a list is a second opinion.

`actioned` and `cancelled` rows are left alone: those states are a person's word about a
row, and merging one into a raised sibling would overwrite it. Rows with no `so_line_id`
are their own row by definition - the Order Inquiry Form's ORDER BACK quantities have no
open sales-order line at all (fixture section 5), and there is nothing to group them by.

Measured dry run on the dev copy, 26 August 2026: 34 rows, of which 4 groups of more than
one (12 rows) merge to 4; 19 placed rows become 19 links; 26 rows remain, and every
`(so_line_id, supply_decision_id)` holds exactly one. SO414285 goes from eleven rows to
nine, which is AC-I6.

**The downgrade splits them back.** A merge cannot be undone row-for-row, but the SHAPE the
old code reads can be rebuilt exactly: one `placed` row per link at that link's quantity
and `po_line_id`, the original row left holding the unlinked remainder (or deleted when
there is none). Row ids differ, the same caveat migration 420 accepted for the documents it
moved; every quantity and every placement round-trips.

Hand-written rather than autogenerated, and guarded throughout: the shared dev database is
a prod copy that converges through `create_all` rather than `alembic upgrade` (see
`sorento_crm_backend/CLAUDE.md`), so every step must be a no-op when it has already
happened. The data half is exposed as functions so a test can drive it on a scratch schema
without running the whole chain.
"""
import logging

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "421_order_inquiry_links"
down_revision = "420_spo_docs_in_allocations"
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.421_order_inquiry_links")

#: The states a link change may set. `actioned` / `cancelled` are a person's word about the
#: row and are never touched by anything here.
_LINK_STATES = ("raised", "placed")


def _schema(bind, module: str) -> str:
    """Where a module's tables live, for RAW SQL, under BOTH substrates.

    `schema_translate_map` rewrites ORM and `Table` constructs only, so a hard-coded
    `projects.order_inquiry_rows` inside a `text()` statement would reach the REAL schema
    from a test running on a scratch copy - writing live data while the test believed it
    was isolated. The scratch schemas are named `<default>_projects`
    (`tests/_pg_fixture.py`), so the current default schema is enough to tell them apart.
    The same helper migration 420 carries, for the same reason.
    """
    current = bind.exec_driver_sql("SELECT current_schema()").scalar()
    return module if current in (None, "public") else f"{current}_{module}"


def _rows(bind) -> str:
    return f'"{_schema(bind, "projects")}"."order_inquiry_rows"'


def _links(bind) -> str:
    return f'"{_schema(bind, "projects")}"."order_inquiry_links"'


def _has_links_table(bind) -> bool:
    return bool(
        bind.execute(
            sa.text(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = :schema AND table_name = 'order_inquiry_links'"
            ),
            {"schema": _schema(bind, "projects")},
        ).first()
    )


def _has_column(bind, table: str, column: str, schema: str = "projects") -> bool:
    return bool(
        bind.execute(
            sa.text(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = :schema
                  AND table_name = :table AND column_name = :column
                """
            ),
            {"schema": _schema(bind, schema), "table": table, "column": column},
        ).first()
    )


# --------------------------------------------------------------------------- data steps
#
# Each is idempotent on its own and each returns its counts, so the migration can report
# what it did and a test can drive one at a time on a scratch schema.


def rename_order_back_verb(bind) -> int:
    """`BORROW_SHORTFALL` -> `ORDER_BACK`. Returns how many rows moved."""
    result = bind.execute(
        sa.text(
            f"UPDATE {_rows(bind)} SET verb = 'ORDER_BACK' "
            "WHERE verb = 'BORROW_SHORTFALL'"
        )
    )
    return result.rowcount or 0


def merge_split_rows(bind) -> dict:
    """Merge every split group into one row, and write one link per placed fragment.

    Idempotent by construction: a second run finds no group of more than one and no placed
    row still carrying a `po_line_id`, so it writes nothing.
    """
    states = ", ".join(f"'{state}'" for state in _LINK_STATES)

    # 1. The survivor of each group, and everything that folds into it. Grouped on the
    #    verb as well as the line and the decision: an ORDER and an ORDER BACK on one line
    #    are two instructions, and summing them would state a quantity nobody asked for.
    groups = bind.execute(
        sa.text(
            f"""
            SELECT so_line_id, supply_decision_id, verb, count(*) AS n
            FROM {_rows(bind)}
            WHERE so_line_id IS NOT NULL AND state IN ({states})
            GROUP BY so_line_id, supply_decision_id, verb
            HAVING count(*) > 1
            """
        )
    ).fetchall()

    merged_groups = 0
    rows_removed = 0
    for so_line_id, decision_id, verb, _n in groups:
        decision_clause = (
            "supply_decision_id = :decision"
            if decision_id is not None
            else "supply_decision_id IS NULL"
        )
        params = {"line": so_line_id, "verb": verb}
        if decision_id is not None:
            params["decision"] = decision_id
        members = bind.execute(
            sa.text(
                f"""
                SELECT id, qty, state
                FROM {_rows(bind)}
                WHERE so_line_id = :line AND verb = :verb AND {decision_clause}
                  AND state IN ({states})
                ORDER BY created_at ASC, id ASC
                """
            ),
            params,
        ).fetchall()
        if len(members) < 2:
            continue
        survivor_id = members[0][0]
        total = sum((member[1] or 0) for member in members)
        # Every fragment's links move to the survivor FIRST, so nothing is lost when the
        # fragment row is deleted (the FK would cascade its links away with it).
        for member in members[1:]:
            bind.execute(
                sa.text(
                    f"UPDATE {_links(bind)} SET row_id = :survivor "
                    "WHERE row_id = :member"
                ),
                {"survivor": survivor_id, "member": member[0]},
            )
        bind.execute(
            sa.text(
                f"DELETE FROM {_rows(bind)} WHERE id = ANY(:ids)"
            ),
            {"ids": [member[0] for member in members[1:]]},
        )
        bind.execute(
            sa.text(f"UPDATE {_rows(bind)} SET qty = :qty WHERE id = :id"),
            {"qty": total, "id": survivor_id},
        )
        merged_groups += 1
        rows_removed += len(members) - 1

    return {"merged_groups": merged_groups, "rows_removed": rows_removed}


def links_from_placed_rows(bind) -> int:
    """One link per row still carrying a `po_line_id`, then clear the scalar.

    Runs BEFORE the merge in `upgrade`, so a fragment's placement is already a link row by
    the time the merge re-points it at the survivor. `qty` comes from the row itself,
    which is exactly what a split fragment's quantity was: its allocation.
    """
    states = ", ".join(f"'{state}'" for state in _LINK_STATES)
    result = bind.execute(
        sa.text(
            f"""
            INSERT INTO {_links(bind)}
                (id, company_id, row_id, po_line_id, spo_allocation_id, document, qty,
                 linked_by, linked_at, auto, claim_id, created_at)
            SELECT gen_random_uuid(), r.company_id, r.id, r.po_line_id, NULL, r.po_ref,
                   r.qty, r.actioned_by, COALESCE(r.actioned_at, now()), false, NULL, now()
            FROM {_rows(bind)} r
            WHERE r.po_line_id IS NOT NULL
              AND r.state IN ({states})
              AND r.qty > 0
              AND NOT EXISTS (
                  SELECT 1 FROM {_links(bind)} l WHERE l.row_id = r.id
              )
            """
        )
    )
    written = result.rowcount or 0
    bind.execute(
        sa.text(
            f"UPDATE {_rows(bind)} SET po_line_id = NULL "
            f"WHERE po_line_id IS NOT NULL AND EXISTS ("
            f"SELECT 1 FROM {_links(bind)} l WHERE l.row_id = {_rows(bind)}.id)"
        )
    )
    return written


def refresh_link_states(bind) -> int:
    """Set every row's state and derived display from its links.

    `raised` with no links, `partly_linked` while the links cover part of the quantity,
    `placed` once they cover it all - the stored value stays `placed` because renaming it
    would rewrite `scm.committed_v`, the worklist filter and every saved column preference
    to say the same thing in a different word. `po_ref` is the FIRST link's document.
    """
    states = ", ".join(f"'{state}'" for state in _LINK_STATES)
    result = bind.execute(
        sa.text(
            f"""
            WITH totals AS (
                SELECT r.id,
                       r.qty AS need,
                       COALESCE(SUM(l.qty), 0) AS linked,
                       -- The FIRST link's document, by when it was made: "first" is an
                       -- order in time, and MIN() would have answered alphabetically.
                       (SELECT f.document
                          FROM {_links(bind)} f
                         WHERE f.row_id = r.id
                         ORDER BY f.linked_at ASC, f.id ASC
                         LIMIT 1) AS document
                FROM {_rows(bind)} r
                LEFT JOIN {_links(bind)} l ON l.row_id = r.id
                WHERE r.state IN ({states}, 'partly_linked')
                GROUP BY r.id, r.qty
            )
            UPDATE {_rows(bind)} r
            SET state = CASE
                    WHEN t.linked <= 0 THEN 'raised'
                    WHEN t.linked < t.need THEN 'partly_linked'
                    ELSE 'placed'
                END,
                po_ref = t.document
            FROM totals t
            WHERE r.id = t.id
              AND (r.state IS DISTINCT FROM CASE
                    WHEN t.linked <= 0 THEN 'raised'
                    WHEN t.linked < t.need THEN 'partly_linked'
                    ELSE 'placed'
                END
                OR r.po_ref IS DISTINCT FROM t.document)
            """
        )
    )
    return result.rowcount or 0


def split_rows_from_links(bind) -> int:
    """The downgrade's data half: rebuild the shape the pre-421 code reads.

    One `placed` row per link, at that link's quantity and `po_line_id`; the original row
    keeps the unlinked remainder as `raised`, or is deleted when the links covered it
    whole. Row ids differ from the ones the upgrade merged away - nothing else does.
    """
    rows = bind.execute(
        sa.text(
            f"""
            SELECT r.id, r.qty, r.company_id, r.order_inquiry_id, r.so_line_id,
                   r.item_code, r.delivery_date, r.stock_location, r.verb,
                   r.covered_by, r.supply_decision_id, r.note, r.redirected_to_pool,
                   r.created_at
            FROM {_rows(bind)} r
            WHERE EXISTS (SELECT 1 FROM {_links(bind)} l WHERE l.row_id = r.id)
            """
        )
    ).fetchall()

    written = 0
    for row in rows:
        links = bind.execute(
            sa.text(
                f"SELECT id, po_line_id, document, qty, linked_by, linked_at "
                f"FROM {_links(bind)} WHERE row_id = :row "
                "ORDER BY linked_at ASC, id ASC"
            ),
            {"row": row[0]},
        ).fetchall()
        if not links:
            continue
        linked_total = sum((link[3] or 0) for link in links)
        remainder = (row[1] or 0) - linked_total

        for index, link in enumerate(links):
            reuse_original = index == 0 and remainder <= 0
            if reuse_original:
                bind.execute(
                    sa.text(
                        f"UPDATE {_rows(bind)} SET qty = :qty, "
                        "po_line_id = :po_line, po_ref = :document, state = 'placed', "
                        "actioned_by = :by, actioned_at = :at WHERE id = :id"
                    ),
                    {
                        "qty": link[3],
                        "po_line": link[1],
                        "document": link[2],
                        "by": link[4],
                        "at": link[5],
                        "id": row[0],
                    },
                )
            else:
                bind.execute(
                    sa.text(
                        f"""
                        INSERT INTO {_rows(bind)}
                            (id, company_id, order_inquiry_id, so_line_id, item_code, qty,
                             delivery_date, stock_location, verb, covered_by,
                             supply_decision_id, note, po_ref, po_line_id,
                             redirected_to_pool, state, actioned_by, actioned_at,
                             created_at)
                        VALUES
                            (gen_random_uuid(), :company, :inquiry, :line, :item, :qty,
                             :delivery, :location, :verb, :covered, :decision, :note,
                             :document, :po_line, :redirected, 'placed', :by, :at,
                             :created)
                        """
                    ),
                    {
                        "company": row[2],
                        "inquiry": row[3],
                        "line": row[4],
                        "item": row[5],
                        "qty": link[3],
                        "delivery": row[6],
                        "location": row[7],
                        "verb": row[8],
                        "covered": row[9],
                        "decision": row[10],
                        "note": row[11],
                        "document": link[2],
                        "po_line": link[1],
                        "redirected": row[12],
                        "by": link[4],
                        "at": link[5],
                        "created": row[13],
                    },
                )
                written += 1

        if remainder > 0:
            bind.execute(
                sa.text(
                    f"UPDATE {_rows(bind)} SET qty = :qty, state = 'raised', "
                    "po_line_id = NULL, po_ref = NULL WHERE id = :id"
                ),
                {"qty": remainder, "id": row[0]},
            )
    return written


# ------------------------------------------------------------------------------ schema


def upgrade() -> None:
    bind = op.get_bind()

    if not _has_links_table(bind):
        op.create_table(
            "order_inquiry_links",
            sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
            sa.Column("company_id", postgresql.UUID(as_uuid=False), nullable=True),
            sa.Column("row_id", postgresql.UUID(as_uuid=False), nullable=False),
            sa.Column("po_line_id", postgresql.UUID(as_uuid=False), nullable=True),
            sa.Column(
                "spo_allocation_id", postgresql.UUID(as_uuid=False), nullable=True
            ),
            sa.Column("document", sa.String(length=80), nullable=True),
            sa.Column("qty", sa.Numeric(precision=15, scale=4), nullable=False),
            sa.Column("linked_by", sa.String(length=100), nullable=True),
            sa.Column(
                "linked_at",
                sa.DateTime(timezone=False),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column(
                "auto", sa.Boolean(), server_default=sa.text("false"), nullable=False
            ),
            sa.Column("claim_id", postgresql.UUID(as_uuid=False), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=False),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
            sa.ForeignKeyConstraint(
                ["row_id"], ["projects.order_inquiry_rows.id"], ondelete="CASCADE"
            ),
            sa.ForeignKeyConstraint(
                ["po_line_id"], ["purchase_order_lines.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(
                ["spo_allocation_id"],
                ["spo_allocations.id"],
                ondelete="SET NULL",
                name="fk_order_inquiry_links_spo_allocation",
            ),
            sa.ForeignKeyConstraint(
                ["linked_by"], ["users.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(
                ["claim_id"], ["scm.order_link_claim.id"], ondelete="SET NULL"
            ),
            sa.CheckConstraint(
                "(po_line_id IS NOT NULL)::int + (spo_allocation_id IS NOT NULL)::int = 1",
                name="ck_order_inquiry_links_one_target",
            ),
            sa.CheckConstraint("qty > 0", name="ck_order_inquiry_links_qty_positive"),
            schema="projects",
        )

    # `CompanyScopedMixin.company_id` declares `index=True`, which `create_table` does not
    # emit; the rest are the model's own. IF NOT EXISTS throughout, because this may be a
    # database that already converged through `create_all`.
    for name, columns in (
        ("ix_order_inquiry_links_company_id", "company_id"),
        ("ix_order_inquiry_links_row", "row_id"),
        ("ix_order_inquiry_links_po_line", "po_line_id"),
        ("ix_order_inquiry_links_spo_allocation", "spo_allocation_id"),
    ):
        op.execute(
            f"CREATE INDEX IF NOT EXISTS {name} ON {_links(bind)} ({columns})"
        )

    if not _has_column(bind, "order_inquiry_rows", "cited_document"):
        op.add_column(
            "order_inquiry_rows",
            sa.Column("cited_document", sa.String(length=80), nullable=True),
            schema="projects",
        )

    renamed = rename_order_back_verb(bind)
    written = links_from_placed_rows(bind)
    merged = merge_split_rows(bind)
    restated = refresh_link_states(bind)
    logger.info(
        "421: %s rows renamed to ORDER_BACK, %s links written, %s groups merged "
        "(%s rows removed), %s rows restated",
        renamed,
        written,
        merged["merged_groups"],
        merged["rows_removed"],
        restated,
    )


def downgrade() -> None:
    bind = op.get_bind()

    if _has_links_table(bind):
        split_rows_from_links(bind)

    bind.execute(
        sa.text(
            f"UPDATE {_rows(bind)} SET state = 'raised' "
            "WHERE state = 'partly_linked'"
        )
    )
    bind.execute(
        sa.text(
            f"UPDATE {_rows(bind)} SET verb = 'BORROW_SHORTFALL' "
            "WHERE verb = 'ORDER_BACK'"
        )
    )

    if _has_column(bind, "order_inquiry_rows", "cited_document"):
        op.drop_column("order_inquiry_rows", "cited_document", schema="projects")

    if _has_links_table(bind):
        op.drop_table("order_inquiry_links", schema="projects")
