"""Fulfilment planning: the per-bin flag, the TBA date, and the Stock Debt permission.

S1 of `PLAN-scm-borrow-ladder-v7-stock-debt.md` (section 3.5), rulings R17 / R20 / R22.

Four things, one revision, because they are one decision: what fulfilment planning READS.

* `warehouses.fulfilment_planning` (boolean, not null, default false) - R17. A bin that is
  off is outside fulfilment planning ENTIRELY: its on hand, its incoming and its
  sales-order lines are invisible to the ladder, the board and the Stock Debt view. Seeded
  true for the ACTIVE bins whose code carries one of the five ownership groups the client
  actually plans (`-BB`, `-IB`, `-IR`, `-NTC`, `-AM`; 24 rows of 83 measured on the dev copy
  29 Aug, the plan's 23 having been counted before `RSW-*` went live), and false
  for everything else, the site pools included - a pool is reached through
  `pool_warehouse_id`, never as an ownership group, so flagging it off costs the pool rung
  nothing. The seed is a ONE-OFF starting position, not a rule: from here an admin turns a
  bin on or off on the Warehouses screen, the same way `counts_as_available` works.
* `scm.priority_policy.tba_date_from` (date, not null, default 2029-01-01) - R20. Demand
  dated on or AFTER it is TBA: it takes no supply, is never covered and never donates.
  A policy field rather than a constant because "2030-01-01" is this client's convention
  for "no date agreed yet" and the next one will have another.
* `cross_group_borrow_max_qty` / `cross_group_borrow_max_pct` are DROPPED - R5. Any
  ownership group may donate now, so there is nothing left for a cap to cap.
* `projects.stock_debt.view` plus the grant sweep from `projects.projects.view` - R22.
  Same shape as `419_stock_transfers.py`: create the row if it is absent, then give it to
  every role already holding the source grant, and take back on downgrade exactly the
  grants this migration made.

Hand-written rather than autogenerated, and guarded with `IF NOT EXISTS` / inspector checks
throughout, for the reason 419 states: the shared dev database is a prod copy whose
`alembic_version` points at another lane's head, so this is applied there by hand and
re-running it has to be a no-op rather than a failure.

The revision id is shorter than the file name on purpose - `alembic_version.version_num` is
provisioned at 255 but the house rule keeps ids short enough for alembic's own default 32.

Revision ID: 443_fulfilment_planning_flag
Revises: 442_notice_recipients_opens
"""
import sqlalchemy as sa
from alembic import op

revision = "443_fulfilment_planning_flag"
down_revision = "442_notice_recipients_opens"
branch_labels = None
depends_on = None


#: The ownership groups the client plans, as the suffix a warehouse code carries. Written
#: as a regex rather than a list of codes because the bins are added and retired by the
#: client, and a code list would be stale the week after it was written.
PLANNED_GROUP_SUFFIX = r"-(BB|IB|IR|NTC|AM)$"

#: The TBA date every install starts on: this client books "no date agreed yet" as 2030,
#: so anything from 2029 on is a placeholder rather than a promise.
DEFAULT_TBA_DATE_FROM = "2029-01-01"

#: (target slug, source slugs whose holders get it, name, description). Name and description
#: match `app/rbac/permission_registry.py`, so the create-if-absent branch here cannot drift
#: from what the registry sync would have written on a create_all database.
_SWEEP = (
    (
        "projects.stock_debt.view",
        ("projects.projects.view",),
        "View Stock Debt",
        (
            "View the Stock Debt month-by-product balance and drill into a month's demand "
            "and supply."
        ),
    ),
)


def _columns(table: str, schema: "str | None" = None) -> set:
    bind = op.get_bind()
    return {
        column["name"]
        for column in sa.inspect(bind).get_columns(table, schema=schema)
    }


def seed_fulfilment_planning_flags(conn) -> int:
    """Turn the flag on for the ACTIVE bins of the five planned ownership groups.

    Exported so `scripts/bootstrap_env.py` can replay it: a create_all database gets the
    COLUMN from the ORM and nothing else, and a seed that lives only in a migration body
    does not exist there (the lesson from #363). Idempotent - it is an UPDATE of rows that
    match a predicate, so running it twice writes the same thing.

    Returns how many rows it turned on, for the bootstrap log line.
    """
    result = conn.execute(
        sa.text(
            "UPDATE warehouses SET fulfilment_planning = true "
            "WHERE is_active AND warehouse_code ~ :suffix "
            "AND fulfilment_planning IS DISTINCT FROM true"
        ),
        {"suffix": PLANNED_GROUP_SUFFIX},
    )
    return result.rowcount or 0


def upgrade() -> None:
    bind = op.get_bind()

    # --- the per-bin flag --------------------------------------------------------------
    if "fulfilment_planning" not in _columns("warehouses"):
        op.add_column(
            "warehouses",
            sa.Column(
                "fulfilment_planning",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            ),
        )
        # Seeded INSIDE the add_column branch, and nowhere else. The seed is a one-off
        # STARTING POSITION, not a rule: from here the flag is configuration an admin edits
        # on the Warehouses screen. Run on every `upgrade()` it would turn back on every bin
        # somebody had deliberately turned off, which is a silent config rollback dressed as
        # an idempotent migration.
        seed_fulfilment_planning_flags(bind)

    # --- the TBA date, and the caps it replaces ----------------------------------------
    policy_columns = _columns("priority_policy", schema="scm")
    if "tba_date_from" not in policy_columns:
        op.add_column(
            "priority_policy",
            sa.Column(
                "tba_date_from",
                sa.Date(),
                nullable=False,
                server_default=sa.text(f"'{DEFAULT_TBA_DATE_FROM}'::date"),
            ),
            schema="scm",
        )
    for dropped in ("cross_group_borrow_max_qty", "cross_group_borrow_max_pct"):
        if dropped in policy_columns:
            op.drop_column("priority_policy", dropped, schema="scm")

    # --- the permission row and the grant sweep ----------------------------------------
    for target, _sources, name, description in _SWEEP:
        bind.execute(
            sa.text(
                """
                INSERT INTO user_permissions (id, slug, name, description, created_at)
                SELECT gen_random_uuid()::text, :slug, :name, :descr, now()
                WHERE NOT EXISTS (SELECT 1 FROM user_permissions WHERE slug = :slug)
                """
            ),
            {"slug": target, "name": name, "descr": description},
        )

    for target, sources, _name, _descr in _SWEEP:
        for source in sources:
            bind.execute(
                sa.text(
                    """
                    INSERT INTO user_role_permissions (id, role_id, permission_id, assigned_at)
                    SELECT gen_random_uuid()::text, rp.role_id, tgt.id, now()
                    FROM user_role_permissions rp
                    JOIN user_permissions src
                      ON src.id = rp.permission_id AND src.slug = :source
                    CROSS JOIN user_permissions tgt
                    WHERE tgt.slug = :target
                    ON CONFLICT (role_id, permission_id) DO NOTHING
                    """
                ),
                {"source": source, "target": target},
            )


def downgrade() -> None:
    """Put back the two caps, drop the flag and the TBA date, and take back exactly the
    grants this migration made.

    The grant removal is mirrored rather than blanket, like `419_stock_transfers`: a target
    grant goes only where the role also holds the source grant that produced it. The
    permission ROW stays - the registry sync would put it straight back, and deleting it
    would strand any grant made by hand.
    """
    bind = op.get_bind()

    for target, sources, _name, _descr in _SWEEP:
        for source in sources:
            bind.execute(
                sa.text(
                    """
                    DELETE FROM user_role_permissions grant_row
                    USING user_permissions tgt
                    WHERE grant_row.permission_id = tgt.id
                      AND tgt.slug = :target
                      AND EXISTS (
                          SELECT 1
                          FROM user_role_permissions src_rp
                          JOIN user_permissions src
                            ON src.id = src_rp.permission_id AND src.slug = :source
                          WHERE src_rp.role_id = grant_row.role_id
                      )
                    """
                ),
                {"source": source, "target": target},
            )

    policy_columns = _columns("priority_policy", schema="scm")
    if "cross_group_borrow_max_qty" not in policy_columns:
        op.add_column(
            "priority_policy",
            sa.Column(
                "cross_group_borrow_max_qty",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("50"),
            ),
            schema="scm",
        )
    if "cross_group_borrow_max_pct" not in policy_columns:
        op.add_column(
            "priority_policy",
            sa.Column(
                "cross_group_borrow_max_pct",
                sa.Numeric(6, 2),
                nullable=False,
                server_default=sa.text("10"),
            ),
            schema="scm",
        )
    if "tba_date_from" in policy_columns:
        op.drop_column("priority_policy", "tba_date_from", schema="scm")

    if "fulfilment_planning" in _columns("warehouses"):
        op.drop_column("warehouses", "fulfilment_planning")
