"""delivery schedule version content hash

Revision ID: c98ad50a64ce
Revises: 29d85dc3ccc3
Create Date: 2026-08-19 09:05:00.000000

Duplicate-upload guard (captain fix, 19 Aug 2026): `create_version` computes the sha256 of
the uploaded bytes and refuses a second upload matching an existing version of the SAME
schedule unless `force=true`. Hand-written, not autogenerated - the local DB is a prod copy
that drifts ahead of `alembic_version` (see `sorento_crm_backend/CLAUDE.md`), so a raw diff
here would carry unrelated drift. Only this one column is this revision's own change.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c98ad50a64ce'
down_revision = '29d85dc3ccc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'delivery_schedule_versions',
        sa.Column('content_sha256', sa.String(length=64), nullable=True),
        schema='projects',
    )


def downgrade() -> None:
    op.drop_column('delivery_schedule_versions', 'content_sha256', schema='projects')
