"""so_draft_findings: a batch-level home for findings with no order of their own

Revision ID: d41f7a2b9c31
Revises: c98ad50a64ce
Create Date: 2026-08-19 10:30:00.000000

Captain live-fix, 19 Aug 2026: a PO-vs-schedule finding with no PO line to point at
(``total_mismatch``, ``phase_unmatched``, an un-mapped schedule column, a schedule column
for a product not on the PO at all) used to be attached to EVERY sales order the build
produced, so a split order that carries none of the offending product still showed the
finding and still had it block publish. `project_sales_order_id` is relaxed to nullable and
`purchase_order_id` / `schedule_version_id` are added so those four finding kinds can be
recorded ONCE per (PO, schedule version) instead, independent of any one order's lifecycle
(an order can be rebuilt/deleted without losing the batch's own finding).

Hand-written, not autogenerated - the local DB is a prod copy that drifts ahead of
`alembic_version` (see `sorento_crm_backend/CLAUDE.md`), so a raw diff here would carry
unrelated drift. Only these columns are this revision's own change.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd41f7a2b9c31'
down_revision = 'c98ad50a64ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column(
        'so_draft_findings',
        'project_sales_order_id',
        nullable=True,
        schema='projects',
    )
    op.add_column(
        'so_draft_findings',
        sa.Column('purchase_order_id', postgresql.UUID(as_uuid=False), nullable=True),
        schema='projects',
    )
    op.add_column(
        'so_draft_findings',
        sa.Column('schedule_version_id', postgresql.UUID(as_uuid=False), nullable=True),
        schema='projects',
    )
    op.create_foreign_key(
        'fk_so_draft_findings_purchase_order',
        'so_draft_findings',
        'purchase_orders',
        ['purchase_order_id'],
        ['id'],
        source_schema='projects',
        referent_schema='projects',
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_so_draft_findings_schedule_version',
        'so_draft_findings',
        'delivery_schedule_versions',
        ['schedule_version_id'],
        ['id'],
        source_schema='projects',
        referent_schema='projects',
        ondelete='CASCADE',
    )
    op.create_index(
        'ix_so_findings_batch',
        'so_draft_findings',
        ['purchase_order_id', 'schedule_version_id'],
        schema='projects',
    )


def downgrade() -> None:
    op.drop_index('ix_so_findings_batch', table_name='so_draft_findings', schema='projects')
    op.drop_constraint(
        'fk_so_draft_findings_schedule_version',
        'so_draft_findings',
        schema='projects',
        type_='foreignkey',
    )
    op.drop_constraint(
        'fk_so_draft_findings_purchase_order',
        'so_draft_findings',
        schema='projects',
        type_='foreignkey',
    )
    op.drop_column('so_draft_findings', 'schedule_version_id', schema='projects')
    op.drop_column('so_draft_findings', 'purchase_order_id', schema='projects')
    op.alter_column(
        'so_draft_findings',
        'project_sales_order_id',
        nullable=False,
        schema='projects',
    )
