#!/usr/bin/env python3
"""Regenerate `tests/chatbot/COVERAGE.md` - the fixture-coverage matrix (AC-008).

REPORT ONLY. This script reads what has already been captured; it never talks to n8n and
never captures anything. Fresh captures come from the n8n repo's own
`scripts/capture-fixtures.py` recipe, run against real live executions, because a
hand-written fixture proves the port agrees with whoever wrote the fixture and nothing
else.

Cutover gate 0 is what this report serves: before a slice PR opens, every branch of every
node that slice ports needs at least 5 real captures. An empty cell blocks the slice. The
report says which cells are short; the fix is always more captures, never a lowered bar.

Usage::

    python scripts/chatbot_fixture_coverage.py            # write the file
    python scripts/chatbot_fixture_coverage.py --check     # exit 1 if it is stale
    CHATBOT_FIXTURES_DIR=... python scripts/chatbot_fixture_coverage.py
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from tests.chatbot import _corpus  # noqa: E402

OUTPUT = BACKEND_ROOT / "tests" / "chatbot" / "COVERAGE.md"

# Gate 0's bar. Not a knob: it is the owner's stated floor.
CAPTURES_PER_BRANCH = 5


def _expected_branch_kind(fixture: _corpus.Fixture) -> str | None:
    """The `branch_kind` a route-turn capture recorded."""
    for item in fixture.expected:
        kind = (item.get("json") or {}).get("branch_kind")
        if kind:
            return str(kind)
    return None


def _branch_of(fixture: _corpus.Fixture) -> str:
    """A coverage CELL for one fixture.

    `route-turn` is cut by the arm it decided, which is the vocabulary gate 0 is written
    in. The other nodes have no branch vocabulary of their own, so they are cut by the
    turn's DOMAIN, which is what actually varies the code path through them.
    """
    if fixture.node == "route-turn":
        return _expected_branch_kind(fixture) or "unknown"
    if fixture.node in ("output_exchange", "suggest-follow-up"):
        for item in fixture.expected:
            output = (item.get("json") or {}).get("output")
            if isinstance(output, dict):
                return str(output.get("domain_hint") or "no_domain")
        return "unknown"
    return "all"


def _provenance(fixture: _corpus.Fixture) -> str:
    """`runData` (a real execution said so) vs anything else (a frozen body run)."""
    source = fixture.data.get("source") or {}
    return str(source.get("expected_from") or "body-run")


def collect() -> dict:
    rows: dict[str, dict[str, Counter]] = defaultdict(lambda: defaultdict(Counter))
    totals: Counter = Counter()
    provenance: dict[str, Counter] = defaultdict(Counter)
    vendored_names: dict[str, set[str]] = defaultdict(set)

    for node in sorted(_corpus.NODE_SLUGS):
        # UNION by file stem, so a fixture that is only vendored (the world-derived
        # route-turn capture) is counted once and only once alongside the full corpus.
        seen: dict[str, _corpus.Fixture] = {}
        for fixture in _corpus.vendored(node):
            vendored_names[node].add(fixture.name)
            seen[fixture.name] = fixture
        for fixture in _corpus.full_corpus(node):
            seen.setdefault(fixture.name.split("/")[-1], fixture)
        for fixture in seen.values():
            rows[node][_branch_of(fixture)][_provenance(fixture)] += 1
            totals[node] += 1
            provenance[node][_provenance(fixture)] += 1
    return {
        "rows": rows,
        "totals": totals,
        "provenance": provenance,
        "vendored": {k: len(v) for k, v in vendored_names.items()},
        "corpus_root": str(_corpus.corpus_root() or "(absent - vendored subset only)"),
    }


def render(data: dict) -> str:
    lines: list[str] = []
    lines.append("# Chatbot fixture coverage")
    lines.append("")
    lines.append(
        "Generated by `scripts/chatbot_fixture_coverage.py`. Do not edit by hand - re-run it."
    )
    lines.append("")
    lines.append(f"Corpus: `{data['corpus_root']}`")
    lines.append("")
    lines.append(
        f"Gate 0 (plan, cutover ladder): every branch of every node a slice ports needs at "
        f"least **{CAPTURES_PER_BRANCH}** REAL captures (`expected_from: runData`) before that "
        "slice's PR opens. A short cell is fixed by capturing more turns with the n8n repo's "
        "`scripts/capture-fixtures.py`, never by lowering the bar or hand-writing a fixture."
    )
    lines.append("")
    lines.append("## Per node")
    lines.append("")
    lines.append("| node | fixtures | real captures | vendored (always run) |")
    lines.append("| --- | ---: | ---: | ---: |")
    for node in sorted(data["totals"]):
        real = data["provenance"][node].get("runData", 0)
        lines.append(
            f"| `{node}` | {data['totals'][node]} | {real} | {data['vendored'].get(node, 0)} |"
        )
    lines.append("")
    lines.append("## Per branch")
    lines.append("")
    lines.append("| node | branch | real captures | other | gate 0 |")
    lines.append("| --- | --- | ---: | ---: | --- |")
    short: list[str] = []
    for node in sorted(data["rows"]):
        for branch in sorted(data["rows"][node]):
            counts = data["rows"][node][branch]
            real = counts.get("runData", 0)
            other = sum(counts.values()) - real
            ok = real >= CAPTURES_PER_BRANCH
            if not ok:
                short.append(f"{node}/{branch} ({real} of {CAPTURES_PER_BRANCH})")
            lines.append(
                f"| `{node}` | `{branch}` | {real} | {other} | {'met' if ok else 'SHORT'} |"
            )
    lines.append("")
    lines.append("## Gate 0 status")
    lines.append("")
    if short:
        lines.append(
            f"**{len(short)} cell(s) short of the bar.** Capture more turns for: "
            + ", ".join(short)
            + "."
        )
    else:
        lines.append("Every cell meets the bar.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 when the file is stale")
    ap.add_argument("--json", action="store_true", help="print the raw counts instead")
    args = ap.parse_args()

    data = collect()
    if args.json:
        print(
            json.dumps(
                {
                    node: {branch: dict(counts) for branch, counts in branches.items()}
                    for node, branches in data["rows"].items()
                },
                indent=2,
                sort_keys=True,
            )
        )
        return 0

    rendered = render(data)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT} is stale - re-run scripts/chatbot_fixture_coverage.py")
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
