"""The phone-list reader, against a workbook shaped like the real one.

No database: the reader takes an `AliasResolver` and bytes, so these tests pin
parsing behaviour without a session, a company, or a migration.

The fixture is generated by `tests/fixtures/make_onboarding_phone_list.py` and
carries, on purpose, everything the real file carried: a title line above the
table, four sections, the header repeated under each, dashed and spaced phone
numbers, trailing-whitespace emails, a row with no email, a row whose phone
cannot be read, a footer, and one person whose name starts with a furniture
word.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from app.services.import_alias_service import AliasResolver
from app.services.onboarding_reader import DOC_TYPE, read_workbook

FIXTURE = Path(__file__).parent / "fixtures" / "onboarding_phone_list.xlsx"

#: The aliases migration 360 seeds. Restated here so the reader tests fail if
#: the seeded set stops covering the shape they were written against.
ALIASES = {
    "staffname": "full_name",
    "name": "full_name",
    "fullname": "full_name",
    "nickname": "nick_name",
    "phone": "phone",
    "mobile": "phone",
    "email": "email",
}


@pytest.fixture()
def resolver() -> AliasResolver:
    return AliasResolver(DOC_TYPE, ALIASES)


@pytest.fixture()
def result(resolver: AliasResolver):
    return read_workbook(FIXTURE.read_bytes(), resolver)


def test_file_is_readable(result):
    assert result.ok
    assert result.missing_columns == []


def test_every_person_is_read_and_no_furniture_is(result):
    """18 people, and exactly 18 - the sections, the repeated headers, the rule
    line, the end-of-report marker and the page number are all skipped."""
    assert len(result.rows) == 18
    assert result.total_rows == 18


def test_sections_ride_onto_their_people(result):
    assert result.sections == [
        "SALES PERSON",
        "SALES ADMIN",
        "WAREHOUSE",
        "SERVICES/REPLACEMENT",
    ]
    by_section: dict[str, int] = {}
    for row in result.rows:
        assert row.section_label is not None, f"{row.full_name} lost its section"
        by_section[row.section_label] = by_section.get(row.section_label, 0) + 1
    assert by_section == {
        "SALES PERSON": 8,
        "SALES ADMIN": 6,
        "WAREHOUSE": 2,
        "SERVICES/REPLACEMENT": 2,
    }


def test_a_person_named_like_a_footer_survives(result):
    """The furniture filter matches whole cells, so "Total Chin Wei" is a person."""
    names = [row.full_name for row in result.rows]
    assert "Total Chin Wei" in names


def test_repeated_header_rows_are_not_people(result):
    names = {row.full_name.upper() for row in result.rows}
    assert "STAFF NAME" not in names
    assert "NICK NAME" not in names


def test_emails_are_folded_and_trimmed(result):
    """Half the addresses carry trailing whitespace; a raw compare would split
    one domain into two."""
    emails = [row.email for row in result.rows if row.email]
    assert all(e == e.strip().lower() for e in emails)
    assert "kavitha@mocha.com.my" in emails
    # The raw value is kept alongside, because it is what the requester typed.
    kavitha = next(r for r in result.rows if r.email == "kavitha@mocha.com.my")
    assert kavitha.email_raw is not None and kavitha.email_raw != kavitha.email


def test_phones_are_msisdn_normalised(result):
    """Bare digits, no leading `+` - the form `users.contact_number` and
    `respond_contacts.phone_number` are stored in, so a collision check is a
    direct comparison rather than a second normalisation."""
    aisyah = next(r for r in result.rows if r.full_name.startswith("Nurul"))
    assert aisyah.phone_raw == "012-3456781"
    assert aisyah.phone == "60123456781"
    # An already-international number is idempotent, and a spaced one still reads.
    priya = next(r for r in result.rows if r.full_name.startswith("Priya"))
    assert priya.phone == "60193456787"
    mei = next(r for r in result.rows if r.full_name == "Ng Mei Ling")
    assert mei.phone == "60133456790"


def test_bad_rows_are_warnings_not_losses(result):
    """A missing email or an unreadable phone keeps the row and names the problem."""
    zul = next(r for r in result.rows if r.full_name.startswith("Ahmad Zulkifli"))
    assert zul.email is None
    assert "no email" in zul.problems

    rajesh = next(r for r in result.rows if r.full_name.startswith("Rajesh"))
    assert rajesh.phone_raw == "01x-34567"
    assert rajesh.phone is None
    assert "phone not recognised" in rajesh.problems

    # And neither of them cost the file anything.
    assert result.ok
    assert len(result.rows) == 18


def test_nicknames_are_read(result):
    aisyah = next(r for r in result.rows if r.full_name.startswith("Nurul"))
    assert aisyah.nick_name == "Aisyah"


def test_a_workbook_with_no_name_column_is_the_one_hard_failure(resolver):
    import openpyxl
    from io import BytesIO

    wb = openpyxl.Workbook()
    sheet = wb.active
    sheet.append(("DEPARTMENT", "HEADCOUNT"))
    sheet.append(("SALES", 8))
    buffer = BytesIO()
    wb.save(buffer)

    result = read_workbook(buffer.getvalue(), resolver)
    assert not result.ok
    assert result.missing_columns == ["full_name"]


def test_unreadable_bytes_are_reported_not_raised(resolver):
    result = read_workbook(b"this is not a workbook", resolver)
    assert not result.ok
    assert result.problems
    assert "could not read the workbook" in result.problems[0].reason
