/**
 * PHASE-1 mock fixtures for the Cross-Entity Activity Timeline.
 *
 * ~30 realistic entries spanning several entity types, users, and actions
 * across ~4 days, including two `trace_id` groups (one user action that
 * touched multiple rows). All entity labels are pre-resolved to human strings
 * (no UUIDs) exactly as the backend will be expected to return them.
 *
 * Timestamps are computed relative to "now" at module load so the "Today /
 * Yesterday" day grouping and relative-time rendering always look live in the
 * prototype regardless of when it is opened.
 */

import type {
  ActivityActorOption,
  ActivityItem,
} from '../types/activity.types';

const NOW = Date.now();
const MIN = 60 * 1000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

function iso(offsetMs: number): string {
  return new Date(NOW - offsetMs).toISOString();
}

export const MOCK_ACTORS: ActivityActorOption[] = [
  { id: 'u-jane', name: 'Jane Tan' },
  { id: 'u-arif', name: 'Arif Rahman' },
  { id: 'u-mei', name: 'Mei Ling' },
  { id: 'u-david', name: 'David Kok' },
  { id: 'u-system', name: 'System' },
];

/**
 * Ordered newest-first, mirroring the backend `changed_at DESC` default.
 */
export const MOCK_ACTIVITY_ITEMS: ActivityItem[] = [
  // ---- Today ----
  {
    id: 'a-01',
    entity_type: 'complaint',
    entity_label: 'Complaint CMP-1042',
    entity_href: '/complaint-management/complaints/CMP-1042',
    action: 'updated',
    actor_name: 'Jane Tan',
    changed_at: iso(8 * MIN),
    summary: 'status: pending → resolved',
    changes: [{ field: 'Status', from: 'Pending', to: 'Resolved' }],
    trace_id: null,
  },
  {
    id: 'a-02',
    entity_type: 'order',
    entity_label: 'Order SO-5567',
    entity_href: '/order-management/orders/SO-5567',
    action: 'updated',
    actor_name: 'Arif Rahman',
    changed_at: iso(22 * MIN),
    summary: 'fulfilment: unfulfilled → partially_fulfilled',
    changes: [
      { field: 'Fulfilment', from: 'Unfulfilled', to: 'Partially fulfilled' },
      { field: 'Linked complaint', from: '—', to: 'CMP-1042' },
    ],
    trace_id: 't-fulfil-1',
  },
  {
    id: 'a-03',
    entity_type: 'complaint',
    entity_label: 'Complaint CMP-1042',
    entity_href: '/complaint-management/complaints/CMP-1042',
    action: 'updated',
    actor_name: 'Arif Rahman',
    changed_at: iso(22 * MIN + 2000),
    summary: 'fulfilment_order: — → SO-5567',
    changes: [{ field: 'Fulfilment order', from: '—', to: 'SO-5567' }],
    trace_id: 't-fulfil-1',
  },
  {
    id: 'a-04',
    entity_type: 'user',
    entity_label: 'User Priya Nair',
    entity_href: '/user-management/users',
    action: 'created',
    actor_name: 'Mei Ling',
    changed_at: iso(55 * MIN),
    summary: 'New user account created (role: CS Agent)',
    changes: [
      { field: 'Name', from: '—', to: 'Priya Nair' },
      { field: 'Role', from: '—', to: 'CS Agent' },
    ],
    trace_id: null,
  },
  {
    id: 'a-05',
    entity_type: 'purchase_request',
    entity_label: 'Purchase Request PR-2231',
    entity_href: '/procurement-management/purchase-requests/PR-2231',
    action: 'updated',
    actor_name: 'David Kok',
    changed_at: iso(70 * MIN),
    summary: 'approval_status: pending → approved',
    changes: [{ field: 'Approval status', from: 'Pending', to: 'Approved' }],
    trace_id: null,
  },
  {
    id: 'a-06',
    entity_type: 'stock_inquiry',
    entity_label: 'Stock Inquiry SI-0884',
    entity_href: '/stock-inquiry-management/stock-inquiries/SI-0884',
    action: 'created',
    actor_name: 'System',
    changed_at: iso(2 * HOUR),
    summary: 'Inquiry created from Respond.io conversation',
    trace_id: null,
  },
  {
    id: 'a-07',
    entity_type: 'promotion',
    entity_label: 'Promotion "Raya Bundle 2026"',
    entity_href: '/marketing-management/promotions',
    action: 'updated',
    actor_name: 'Mei Ling',
    changed_at: iso(3 * HOUR),
    summary: 'end_date: 30 Jun → 15 Jul',
    changes: [{ field: 'End date', from: '30 Jun 2026', to: '15 Jul 2026' }],
    trace_id: null,
  },
  {
    id: 'a-08',
    entity_type: 'product',
    entity_label: 'Product SKU RICE-5KG-JAS',
    entity_href: '/master-data/products',
    action: 'updated',
    actor_name: 'David Kok',
    changed_at: iso(4 * HOUR),
    summary: 'unit_price: 28.50 → 30.00',
    changes: [{ field: 'Unit price', from: 'RM 28.50', to: 'RM 30.00' }],
    trace_id: null,
  },
  {
    id: 'a-09',
    entity_type: 'ticket',
    entity_label: 'Ticket TCK-3390',
    entity_href: '/complaint-management/tickets/TCK-3390',
    action: 'updated',
    actor_name: 'Jane Tan',
    changed_at: iso(5 * HOUR),
    summary: 'assignee: — → Arif Rahman',
    changes: [{ field: 'Assignee', from: 'Unassigned', to: 'Arif Rahman' }],
    trace_id: null,
  },
  {
    id: 'a-10',
    entity_type: 'complaint',
    entity_label: 'Complaint CMP-1039',
    entity_href: '/complaint-management/complaints/CMP-1039',
    action: 'created',
    actor_name: 'System',
    changed_at: iso(6 * HOUR),
    summary: 'Complaint created from web form submission',
    trace_id: null,
  },

  // ---- Yesterday ----
  {
    id: 'a-11',
    entity_type: 'order',
    entity_label: 'Order SO-5560',
    entity_href: '/order-management/orders/SO-5560',
    action: 'deleted',
    actor_name: 'David Kok',
    changed_at: iso(DAY + 1 * HOUR),
    summary: 'Order deleted (duplicate submission)',
    trace_id: null,
  },
  {
    id: 'a-12',
    entity_type: 'supplier',
    entity_label: 'Supplier "Golden Grain Sdn Bhd"',
    entity_href: '/master-data/suppliers',
    action: 'updated',
    actor_name: 'Mei Ling',
    changed_at: iso(DAY + 2 * HOUR),
    summary: 'contact_email updated',
    changes: [
      {
        field: 'Contact email',
        from: 'sales@goldengrain.my',
        to: 'orders@goldengrain.my',
      },
    ],
    trace_id: null,
  },
  {
    id: 'a-13',
    entity_type: 'form',
    entity_label: 'Form "Delivery Feedback"',
    entity_href: '/form-management/forms',
    action: 'updated',
    actor_name: 'Jane Tan',
    changed_at: iso(DAY + 3 * HOUR),
    summary: 'is_active: false → true',
    changes: [{ field: 'Active', from: 'No', to: 'Yes' }],
    trace_id: null,
  },
  {
    id: 'a-14',
    entity_type: 'purchase_request',
    entity_label: 'Purchase Request PR-2228',
    entity_href: '/procurement-management/purchase-requests/PR-2228',
    action: 'updated',
    actor_name: 'David Kok',
    changed_at: iso(DAY + 4 * HOUR),
    summary: 'status: submitted → processed_by_cs',
    changes: [{ field: 'Status', from: 'Submitted', to: 'Processed by CS' }],
    trace_id: null,
  },
  {
    id: 'a-15',
    entity_type: 'complaint',
    entity_label: 'Complaint CMP-1035',
    entity_href: '/complaint-management/complaints/CMP-1035',
    action: 'updated',
    actor_name: 'Arif Rahman',
    changed_at: iso(DAY + 5 * HOUR),
    summary: 'priority: low → high',
    changes: [{ field: 'Priority', from: 'Low', to: 'High' }],
    trace_id: null,
  },
  {
    id: 'a-16',
    entity_type: 'user',
    entity_label: 'User Arif Rahman',
    entity_href: '/user-management/users',
    action: 'updated',
    actor_name: 'Mei Ling',
    changed_at: iso(DAY + 6 * HOUR),
    summary: 'role: CS Agent → CS Supervisor',
    changes: [{ field: 'Role', from: 'CS Agent', to: 'CS Supervisor' }],
    trace_id: null,
  },
  {
    id: 'a-17',
    entity_type: 'promotion',
    entity_label: 'Promotion "Merdeka Special"',
    entity_href: '/marketing-management/promotions',
    action: 'created',
    actor_name: 'Mei Ling',
    changed_at: iso(DAY + 7 * HOUR),
    summary: 'New promotion drafted',
    trace_id: null,
  },
  {
    id: 'a-18',
    entity_type: 'order',
    entity_label: 'Order SO-5558',
    entity_href: '/order-management/orders/SO-5558',
    action: 'created',
    actor_name: 'Jane Tan',
    changed_at: iso(DAY + 9 * HOUR),
    summary: 'New order created (RM 1,240.00)',
    trace_id: null,
  },

  // ---- 2 days ago (bulk trace-id group) ----
  {
    id: 'a-19',
    entity_type: 'product',
    entity_label: 'Product SKU FLOUR-1KG',
    entity_href: '/master-data/products',
    action: 'updated',
    actor_name: 'David Kok',
    changed_at: iso(2 * DAY + 1 * HOUR),
    summary: 'category: — → Baking',
    changes: [{ field: 'Category', from: '—', to: 'Baking' }],
    trace_id: 't-bulk-cat',
  },
  {
    id: 'a-20',
    entity_type: 'product',
    entity_label: 'Product SKU SUGAR-1KG',
    entity_href: '/master-data/products',
    action: 'updated',
    actor_name: 'David Kok',
    changed_at: iso(2 * DAY + 1 * HOUR + 1000),
    summary: 'category: — → Baking',
    changes: [{ field: 'Category', from: '—', to: 'Baking' }],
    trace_id: 't-bulk-cat',
  },
  {
    id: 'a-21',
    entity_type: 'product',
    entity_label: 'Product SKU YEAST-100G',
    entity_href: '/master-data/products',
    action: 'updated',
    actor_name: 'David Kok',
    changed_at: iso(2 * DAY + 1 * HOUR + 2000),
    summary: 'category: — → Baking',
    changes: [{ field: 'Category', from: '—', to: 'Baking' }],
    trace_id: 't-bulk-cat',
  },
  {
    id: 'a-22',
    entity_type: 'complaint',
    entity_label: 'Complaint CMP-1031',
    entity_href: '/complaint-management/complaints/CMP-1031',
    action: 'updated',
    actor_name: 'Jane Tan',
    changed_at: iso(2 * DAY + 3 * HOUR),
    summary: 'status: resolved → closed',
    changes: [{ field: 'Status', from: 'Resolved', to: 'Closed' }],
    trace_id: null,
  },
  {
    id: 'a-23',
    entity_type: 'stock_inquiry',
    entity_label: 'Stock Inquiry SI-0879',
    entity_href: '/stock-inquiry-management/stock-inquiries/SI-0879',
    action: 'updated',
    actor_name: 'Arif Rahman',
    changed_at: iso(2 * DAY + 4 * HOUR),
    summary: 'status: open → answered',
    changes: [{ field: 'Status', from: 'Open', to: 'Answered' }],
    trace_id: null,
  },
  {
    id: 'a-24',
    entity_type: 'ticket',
    entity_label: 'Ticket TCK-3382',
    entity_href: '/complaint-management/tickets/TCK-3382',
    action: 'deleted',
    actor_name: 'Mei Ling',
    changed_at: iso(2 * DAY + 6 * HOUR),
    summary: 'Ticket deleted (created in error)',
    trace_id: null,
  },
  {
    id: 'a-25',
    entity_type: 'supplier',
    entity_label: 'Supplier "Sunrise Distributors"',
    entity_href: '/master-data/suppliers',
    action: 'created',
    actor_name: 'David Kok',
    changed_at: iso(2 * DAY + 8 * HOUR),
    summary: 'New supplier onboarded',
    trace_id: null,
  },

  // ---- 3 days ago ----
  {
    id: 'a-26',
    entity_type: 'order',
    entity_label: 'Order SO-5551',
    entity_href: '/order-management/orders/SO-5551',
    action: 'updated',
    actor_name: 'Jane Tan',
    changed_at: iso(3 * DAY + 2 * HOUR),
    summary: 'delivery_date: 26 Jun → 27 Jun',
    changes: [{ field: 'Delivery date', from: '26 Jun 2026', to: '27 Jun 2026' }],
    trace_id: null,
  },
  {
    id: 'a-27',
    entity_type: 'form',
    entity_label: 'Form "New Supplier Intake"',
    entity_href: '/form-management/forms',
    action: 'created',
    actor_name: 'Mei Ling',
    changed_at: iso(3 * DAY + 4 * HOUR),
    summary: 'New form published',
    trace_id: null,
  },
  {
    id: 'a-28',
    entity_type: 'purchase_request',
    entity_label: 'Purchase Request PR-2220',
    entity_href: '/procurement-management/purchase-requests/PR-2220',
    action: 'deleted',
    actor_name: 'David Kok',
    changed_at: iso(3 * DAY + 5 * HOUR),
    summary: 'Draft purchase request discarded',
    trace_id: null,
  },
  {
    id: 'a-29',
    entity_type: 'complaint',
    entity_label: 'Complaint CMP-1027',
    entity_href: '/complaint-management/complaints/CMP-1027',
    action: 'updated',
    actor_name: 'Arif Rahman',
    changed_at: iso(3 * DAY + 7 * HOUR),
    summary: 'assignee: Jane Tan → Arif Rahman',
    changes: [{ field: 'Assignee', from: 'Jane Tan', to: 'Arif Rahman' }],
    trace_id: null,
  },
  {
    id: 'a-30',
    entity_type: 'user',
    entity_label: 'User David Kok',
    entity_href: '/user-management/users',
    action: 'updated',
    actor_name: 'System',
    changed_at: iso(3 * DAY + 9 * HOUR),
    summary: 'last_login updated',
    trace_id: null,
  },
];
