"""The chatbot policy rows `chatbot_rearch_s0` seeds - FROZEN at the revision.

A migration must produce the same database whenever it runs, so it cannot read the
running application's data. `chatbot_rearch_s0` used to import
`app/services/chatbot/turn/policy_rows.py` and `app/modules/chatbot/lane_vocabulary.py`
at module scope: an `alembic upgrade head` replayed from genesis a year from now would
have seeded whatever those files say THEN, and an import that has moved or been deleted
would fail the whole upgrade on a fresh database. This is the immutable copy the
migration reads instead, in the shape it had when the revision was written.

Same precedent, and same reason, as `alembic/_legacy_prompt_bodies.py`. Nothing under
`app/` imports this module: the live policy is the `chatbot_domains` /
`chatbot_entity_kinds` TABLES, and `policy_rows.py` is the loader's own blank-schema
fallback. Changing the policy means a NEW migration against those tables, never an edit
here or there (S3 ruling, 16 Sep 2026).
"""
from __future__ import annotations

DATE_PARAM_TOOLS = {'crm_incoming_stock_by_product',
 'crm_incoming_stock_list',
 'crm_incoming_stock_shipments',
 'crm_low_stock_report',
 'crm_marketing_promotions_list',
 'crm_order_management_orders_by_product_list',
 'crm_order_management_orders_list',
 'crm_outstanding_report',
 'crm_procurement_po_placed_list',
 'crm_resource_attachments_catalogue',
 'crm_resource_attachments_list',
 'crm_sla_conversation_event_logs_list'}

DEFAULT_TIER_ORDER = ['dealer', 'office', 'end_user']

DEFAULT_DOMAIN_ROWS = [{'name': 'master_products',
  'label': 'product information',
  'intents': ['check_product'],
  'tools': ['crm_master_products_list',
            'crm_master_brands_list',
            'crm_master_product_categories_list',
            'crm_master_units_of_measure_list'],
  'escalation_team_code': 'purchasing',
  'switch_words': ['catalogue',
                   'catalog',
                   'spec',
                   'specs',
                   'specification',
                   'specifications',
                   'dimension',
                   'dimensions'],
  'narrowing': {},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'product_attachment',
  'label': 'product attachments',
  'intents': ['check_product_attachment'],
  'tools': ['crm_master_product_attachments_list', 'crm_certificates_list'],
  'escalation_team_code': 'marketing_product',
  'switch_words': [],
  'narrowing': {'attachment_type': 'narrow_by_type', 'product': 'must_narrow_one'},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'promotion',
  'label': 'promotions',
  'intents': ['check_promotion'],
  'tools': ['crm_marketing_promotions_list',
            'crm_marketing_promotion_attachments_list',
            'crm_marketing_promotion_products_list'],
  'escalation_team_code': 'marketing_promotion',
  'switch_words': ['promo', 'promos', 'promotion', 'promotions', 'promosi'],
  'narrowing': {'tier': 'narrow_by_tier'},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'forms',
  'label': 'forms',
  'intents': ['get_forms'],
  'tools': ['crm_forms_management_forms_list'],
  'escalation_team_code': 'marketing_form',
  'switch_words': [],
  'narrowing': {},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'inventory',
  'label': 'stock',
  'intents': ['check_stock', 'low_stock_report'],
  'tools': ['crm_inventory_stock_balance_list',
            'crm_inventory_warehouses_list',
            'crm_low_stock_report'],
  'escalation_team_code': 'warehouse',
  'switch_words': ['stock',
                   'stocks',
                   'inventory',
                   'stok',
                   'qty',
                   'quantity',
                   'low stock',
                   'reorder report',
                   'below level'],
  'narrowing': {'product': 'list_all'},
  'reveal_key': 'inventory.sellable',
  'supported': True,
  'ladder': ['incoming', 'purchase_order']},
 {'name': 'order',
  'label': 'orders',
  'intents': ['check_order'],
  'tools': ['crm_order_management_orders_list',
            'crm_order_management_orders_by_product_list',
            'crm_master_customers_list',
            'crm_outstanding_report'],
  'escalation_team_code': 'customer_service',
  'switch_words': ['order',
                   'orders',
                   'outstanding',
                   'tempahan',
                   'delivery',
                   'deliveries',
                   'deliver',
                   'delivered',
                   'penghantaran',
                   'hantar',
                   'dihantar'],
  'narrowing': {'customer': 'must_narrow_one'},
  'reveal_key': 'sales_orders.outstanding',
  'supported': True,
  'ladder': []},
 {'name': 'incoming',
  'label': 'incoming stock',
  'intents': ['check_incoming'],
  'tools': ['crm_incoming_stock_list',
            'crm_incoming_stock_by_product',
            'crm_incoming_stock_shipments'],
  'escalation_team_code': 'purchasing',
  'switch_words': ['incoming',
                   'eta',
                   'shipment',
                   'shipments',
                   'arriving',
                   'container',
                   'containers'],
  'narrowing': {'product': 'narrow_to_code'},
  'reveal_key': None,
  'supported': True,
  'ladder': ['inventory', 'purchase_order']},
 {'name': 'portal_link',
  'label': 'this request',
  'intents': ['get_portal_link'],
  'tools': ['crm_portal_link_get'],
  'escalation_team_code': None,
  'switch_words': [],
  'narrowing': {},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'resource_attachment',
  'label': 'resource attachments',
  'intents': ['get_resource_attachment'],
  'tools': ['crm_resource_attachments_list',
            'crm_resource_attachments_catalogue',
            'crm_resource_attachments_current_stock_list'],
  'escalation_team_code': None,
  'switch_words': [],
  'narrowing': {},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'goods_receive',
  'label': 'goods receive',
  'intents': ['check_goods_receive'],
  'tools': [],
  'escalation_team_code': None,
  'switch_words': [],
  'narrowing': {},
  'reveal_key': None,
  'supported': False,
  'ladder': []},
 {'name': 'spo_allocation',
  'label': 'last in',
  'intents': ['check_spo'],
  'tools': ['crm_procurement_spo_allocations_last_receipt_list'],
  'escalation_team_code': None,
  'switch_words': ['spo'],
  'narrowing': {'product': 'narrow_to_code'},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'ideate',
  'label': 'ideas',
  'intents': ['submit_idea'],
  'tools': [],
  'escalation_team_code': None,
  'switch_words': [],
  'narrowing': {},
  'reveal_key': None,
  'supported': True,
  'ladder': []},
 {'name': 'purchase_order',
  'label': 'outstanding purchase orders',
  'intents': ['check_po'],
  'tools': ['crm_procurement_po_placed_list'],
  'escalation_team_code': 'purchasing',
  'switch_words': ['po'],
  'narrowing': {'product': 'narrow_to_code'},
  'reveal_key': 'purchase_orders.placed',
  'supported': True,
  'ladder': []},
 {'name': 'purchase_cost',
  'label': 'last purchase cost',
  'intents': ['check_po_cost'],
  'tools': ['crm_procurement_po_last_cost_list'],
  'escalation_team_code': 'purchasing',
  'switch_words': [],
  'narrowing': {'product': 'narrow_to_code'},
  'reveal_key': 'purchase_orders.cost',
  'supported': True,
  'ladder': []}]

DEFAULT_KIND_ROWS = [{'kind': 'product',
  'label': 'Product',
  'resolver_source': 'master_products',
  'did_you_mean': True,
  'default_narrowing': 'list_all',
  'family_grouping': 'base_code',
  'base_property_words': {'price': 'list_price',
                          'list price': 'list_price',
                          'harga': 'list_price',
                          'cost': 'cost_price',
                          'dimension': 'dimensions',
                          'dimensions': 'dimensions',
                          'size': 'dimensions',
                          'ukuran': 'dimensions',
                          'saiz': 'dimensions',
                          'description': 'description',
                          'name': 'product_name',
                          'discontinued': 'is_discontinued',
                          'brand': 'brand_id'}},
 {'kind': 'promotion',
  'label': 'Promotion',
  'resolver_source': 'promotions',
  'did_you_mean': True,
  'default_narrowing': 'optional_filter',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'customer',
  'label': 'Customer',
  'resolver_source': 'customers',
  'did_you_mean': True,
  'default_narrowing': 'must_narrow_one',
  'family_grouping': 'ledger_family',
  'base_property_words': {}},
 {'kind': 'transporter',
  'label': 'Transporter',
  'resolver_source': 'transporters',
  'did_you_mean': True,
  'default_narrowing': 'optional_filter',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'inbound_shipment',
  'label': 'Inbound shipment',
  'resolver_source': 'packing_lists',
  'did_you_mean': False,
  'default_narrowing': 'optional_filter',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'warehouse',
  'label': 'Warehouse',
  'resolver_source': 'warehouses',
  'did_you_mean': True,
  'default_narrowing': 'optional_filter',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'attachment',
  'label': 'Attachment',
  'resolver_source': 'attachments',
  'did_you_mean': False,
  'default_narrowing': 'not_applicable',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'form',
  'label': 'Form',
  'resolver_source': 'forms',
  'did_you_mean': False,
  'default_narrowing': 'not_applicable',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'order',
  'label': 'Order',
  'resolver_source': 'orders',
  'did_you_mean': False,
  'default_narrowing': 'not_applicable',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'category',
  'label': 'Category',
  'resolver_source': 'product_categories',
  'did_you_mean': True,
  'default_narrowing': 'optional_filter',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'brand',
  'label': 'Brand',
  'resolver_source': 'brands',
  'did_you_mean': True,
  'default_narrowing': 'optional_filter',
  'family_grouping': None,
  'base_property_words': {}},
 {'kind': 'attachment_type',
  'label': 'Attachment type',
  'resolver_source': 'attachment_types',
  'did_you_mean': True,
  'default_narrowing': 'narrow_by_type',
  'family_grouping': None,
  'base_property_words': {}}]
