"""S4 - prompt blocks rendered from `chatbot_domains` / `chatbot_entity_kinds` (AC-1550,
PLAN-chatbot-turn-rearch.md "The policy": "The parser prompt's domain and entity
blocks are rendered from these rows at publish time").

`app.services.chatbot_parser_prompt.render_prompt_blocks(db) -> str` and
`prompt_blocks_hash(db) -> str` do not exist yet (coordinator-specified names/paths),
so every test is RED at collection with `ImportError: cannot import name
'render_prompt_blocks' from 'app.services.chatbot_parser_prompt'` - the module itself
exists (it holds the live prompt constants), the two functions do not.

Runs against the REAL migrated database (`tests._pg_fixture.pg_session`, this
worktree's private `sorento_ai_automation_rearch_test`) - `chatbot_domains` /
`chatbot_entity_kinds` are migration-seeded data (S0, already committed), same
substrate rule as `test_rearch_s0_domains_seed.py`.

**Grammar this tester invented for the golden file** (nothing in the PLAN/UAC pins the
exact wording beyond "one paragraph per domain: name, label, intents, switch words,
entity kinds with narrowing policy, 'takes a date window' when set, 'escalates to
<team code>'; then one paragraph per entity kind: kind, resolver source, did-you-mean
on/off, default narrowing; deterministic order = sort_order then name") - flagged as
an ambiguity, not resolved unilaterally:

    Domain <name> ("<label>"): intents <i1, i2>. Switch words: <w1, w2> (or "(none)").
    [<kind> narrows <policy>[; <kind2> narrows <policy2>].] [Takes a date window.]
    [Escalates to <team_code>.]

    (blank line between the domain paragraphs and the entity-kind paragraphs)

    Entity kind <kind>: resolver <resolver_source>. Did-you-mean <on/off>. Default
    narrowing <policy>.

One domain paragraph per line, one entity-kind paragraph per line, domains sorted by
`(sort_order, name)`, entity kinds sorted by `kind` (the table has no `sort_order`
column - measured: `SELECT * FROM chatbot_entity_kinds` has no such column). The
golden file `tests/chatbot/fixtures/prompt_blocks_seed.txt` was generated BY HAND from
this worktree's real seeded rows (same DB the test reads), following exactly this
grammar. This grammar is now the CONTRACT (coordinator ruling, 16 Sep 2026): the
coder reshapes `render_prompt_blocks` to match the fixture, not the reverse.

Staleness hash storage (coordinator ruling, 16 Sep 2026, superseding this file's
first cut): `AIPromptVersion` already carries a JSONB `config_json` column
(`app/models/ai_prompt.py`) - there is no second JSONB column. `blocks_hash` lives at
`AIPromptVersion.config_json["blocks_hash"]`, never a `metadata` attribute (which
would in any case collide with SQLAlchemy's own reserved `Base.metadata` on every
declarative model).
"""
from __future__ import annotations

import pathlib

import pytest
from sqlalchemy import text

# Forces collection failure now - see module docstring.
from app.services.chatbot_parser_prompt import prompt_blocks_hash, render_prompt_blocks  # noqa: F401,E501

from tests._pg_fixture import pg_session

FIXTURE = pathlib.Path(__file__).resolve().parent / "fixtures" / "prompt_blocks_seed.txt"


def _golden() -> str:
    return FIXTURE.read_text(encoding="utf-8")


class TestRenderMatchesGolden:
    def test_render_prompt_blocks_equals_golden_file(self) -> None:
        with pg_session() as db:
            rendered = render_prompt_blocks(db)

        assert rendered == _golden(), (
            "render_prompt_blocks(db) must equal the hand-written golden file "
            f"byte-for-byte.\n--- rendered ---\n{rendered}\n--- golden ---\n{_golden()}"
        )


class TestChangingARowChangesOutputAndHash:
    def test_switch_words_change_flows_into_render_and_hash(self) -> None:
        with pg_session() as db:
            before_render = render_prompt_blocks(db)
            before_hash = prompt_blocks_hash(db)

            db.execute(
                text(
                    "UPDATE chatbot_domains SET switch_words = switch_words || :extra "
                    "WHERE name = 'master_products'"
                ),
                {"extra": ["ZZT-prompt-blocks-word"]},
            )
            db.flush()

            after_render = render_prompt_blocks(db)
            after_hash = prompt_blocks_hash(db)

            assert after_render != before_render, (
                "changing one domain row's switch_words must change the rendered "
                "block text"
            )
            assert after_hash != before_hash, (
                "changing one domain row's switch_words must change the blocks hash"
            )
            # Rolled back by pg_session's own teardown - no explicit revert needed.


class TestMigrationPublishesFirstRearchVersionUnlabelled:
    """The migration that publishes the first rearch parser version (S4, not yet
    written) must leave exactly ONE new unlabelled `ai_prompt_versions` row for
    `chatbot_semantic_parser` whose body contains the rendered blocks verbatim and
    whose `config_json` carries `blocks_hash`; the `production` label must not move.

    RE-PINNED (owner ruling 21 Sep 2026, hand pass 12 S12): `chatbot_rearch_s12`
    republishes AND promotes `production` ON PURPOSE, once the narrowing values it
    ships are live (S12's own docstring: "deploying this lane must need NO hand
    setup on prod" - this REVERSES S4's own "the owner promotes from the Prompts
    page" rule for later publishes). Asserting "the label has not moved" against
    `pg_session` (the FULLY migrated database, S12 included) now fails for the
    right reason: S12 has already moved it, on purpose. `test_production_label_
    not_moved_by_the_migration` below now runs S4 ALONE (`blank_session()`, S0 then
    S4 only, never the full chain) to keep pinning what THIS migration promises on
    its own step; `test_rearch_s12_config_ships.py::TestS12Upgrade` is where the
    promote-on-purpose rule is pinned."""

    PROMPT_NAME = "chatbot_semantic_parser"

    @pytest.mark.xfail(
        strict=True,
        reason=(
            "S4 publishes before s6d/s6e change the narrowing, so the published "
            "template never equals today's render - republish per narrowing "
            "migration or accept the banner (follow-up, PR #952)"
        ),
    )
    def test_exactly_one_new_unlabelled_version_with_blocks_and_hash(self) -> None:
        from app.models.ai_prompt import AIPromptLabel, AIPromptVersion

        with pg_session() as db:
            rendered = render_prompt_blocks(db)
            blocks_hash = prompt_blocks_hash(db)

            versions = (
                db.query(AIPromptVersion)
                .filter(AIPromptVersion.name == self.PROMPT_NAME)
                .all()
            )
            labelled_version_ids = {
                row.version_id
                for row in db.query(AIPromptLabel).filter(AIPromptLabel.name == self.PROMPT_NAME)
            }
            unlabelled = [v for v in versions if v.id not in labelled_version_ids]
            carrying_blocks = [
                v
                for v in unlabelled
                if rendered in (v.template or "")
                and (v.config_json or {}).get("blocks_hash") == blocks_hash
            ]

            assert len(carrying_blocks) == 1, (
                f"expected exactly one unlabelled version whose body contains the "
                f"rendered blocks verbatim and whose config_json['blocks_hash'] "
                f"matches - found {len(carrying_blocks)} "
                f"(unlabelled total: {len(unlabelled)})"
            )

    def test_production_label_not_moved_by_the_migration(self) -> None:
        """S4 ALONE (`blank_session()`, S0 then S4, never S6d..S12): a fresh scratch
        schema's own `seed_prompt_registry` bootstrap (called from inside `publish_
        policy_blocks` itself) seeds v1 AND its production label the FIRST time this
        install has ever seeded the key - production then stays at that v1 while
        S4's own new-version logic publishes today's rendered blocks as a SECOND,
        UNLABELLED version. `test_rearch_s12_config_ships.py::TestS12Upgrade` pins
        the opposite, ON-PURPOSE promote S12 performs once the chain reaches it -
        this test only ever exercises S4's own step."""
        from app.models.ai_prompt import AIPromptLabel, AIPromptVersion
        from tests._pg_fixture import blank_session
        from tests.chatbot.test_rearch_s12_config_ships import _load

        with blank_session() as db:
            bind = db.get_bind()
            _load("chatbot_rearch_s0.py").seed_domains_and_kinds(bind)
            _load("chatbot_rearch_s4.py").publish_policy_blocks(bind)
            db.commit()

            production = (
                db.query(AIPromptLabel)
                .filter(AIPromptLabel.name == self.PROMPT_NAME, AIPromptLabel.label == "production")
                .first()
            )
            assert production is not None, "no 'production' label row for chatbot_semantic_parser"

            rendered = render_prompt_blocks(db)
            production_version = (
                db.query(AIPromptVersion).filter(AIPromptVersion.id == production.version_id).first()
            )
            assert production_version is not None
            assert rendered not in (production_version.template or ""), (
                "S4 ALONE must not move the production label - the version "
                "production still points at (the bootstrap v1) must not be the new "
                "rendered-blocks version S4 published unlabelled"
            )
