/**
 * PHASE 1 MOCK - delete in Phase 2 (issue #62 / S4).
 *
 * Real rows lifted from `Container Status 2026.xlsx`, restricted to containers that
 * already exist as packing lists in the dev database, so the prototype renders against
 * data the team recognises rather than invented values.
 *
 * The spread of tabs is deliberate - it exercises the states the real sheet contains:
 *   - `Fitting`  -> inspection/approval EMPTY (brass fittings are not CIDB Fourth Schedule)
 *   - `Ceramic`  -> inspection/approval FILLED (ceramic + sanitary ware are regulated)
 *   - `Arrived`  -> the full chain through to collection
 *   - `Arrived - Joint Mocha Container` -> a second consignee on the same container
 *
 * `ata_date`, `ori_doc_received_date`, `k1_submission_date` and `yard_arrival_date` are
 * near-always null on purpose: fill rates across 411 sheet rows are 6/4/4/4. They round-trip
 * the sheet and nothing keys off them.
 */
import type { ClearanceFields } from '../types/packingList.types';

/** Keyed by normalized container number (uppercase, separators stripped). */
export const MOCK_CLEARANCE_BY_CONTAINER: Record<string, ClearanceFields> = {
  "GXYU5106903": {
    loc: null,
    liner_code: "CMA",
    china_forwarder: "Onetouch",
    malaysia_forwarder: "MPM",
    consignee: "Sorento (Mocha)",
    free_days_available: 21,
    stacked: null,
    loading_date: "2026-06-09",
    etc_date: "2026-06-13",
    etd_date: "2026-06-15",
    eta_date: "2026-06-21",
    eta_delay_date: "2026-07-08",
    inspection_date: null,
    approval_date: null,
    gatepass_date: "2026-07-08",
    delivery_warehouse: null,
    warehouse_arrival_date: null,
    informed_collection_date: null,
    collection_date: null,
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Fitting",
  },
  "GXYU5115470": {
    loc: "MWH",
    liner_code: "CMA",
    china_forwarder: "Onetouch",
    malaysia_forwarder: "Sataka",
    consignee: "Sorento",
    free_days_available: 14,
    stacked: null,
    loading_date: "2026-06-10",
    etc_date: "2026-06-13",
    etd_date: "2026-06-15",
    eta_date: "2026-06-21",
    eta_delay_date: "2026-07-12",
    inspection_date: null,
    approval_date: null,
    gatepass_date: "2026-07-13",
    delivery_warehouse: null,
    warehouse_arrival_date: null,
    informed_collection_date: null,
    collection_date: null,
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Fitting",
  },
  "OOCU8630645": {
    loc: null,
    liner_code: "OOCL",
    china_forwarder: "Onetouch",
    malaysia_forwarder: "Sataka",
    consignee: "Sorento",
    free_days_available: 21,
    stacked: null,
    loading_date: "2026-06-20",
    etc_date: "2026-06-23",
    etd_date: "2026-06-25",
    eta_date: "2026-07-02",
    eta_delay_date: "2026-07-06",
    inspection_date: null,
    approval_date: null,
    gatepass_date: "2026-07-07",
    delivery_warehouse: null,
    warehouse_arrival_date: null,
    informed_collection_date: null,
    collection_date: null,
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Fitting",
  },
  "FCIU7600305": {
    loc: "BRW",
    liner_code: "CMA",
    china_forwarder: "Haiian",
    malaysia_forwarder: "Haiian",
    consignee: "Sorento",
    free_days_available: 21,
    stacked: null,
    loading_date: "2026-06-20",
    etc_date: "2026-06-23",
    etd_date: "2026-06-25",
    eta_date: "2026-07-04",
    eta_delay_date: "2026-07-05",
    inspection_date: "2026-07-09",
    approval_date: "2026-07-10",
    gatepass_date: "2026-07-15",
    delivery_warehouse: null,
    warehouse_arrival_date: null,
    informed_collection_date: null,
    collection_date: null,
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Ceramic",
  },
  "SEGU4326041": {
    loc: "DC1",
    liner_code: "CMA",
    china_forwarder: "Haiian",
    malaysia_forwarder: "Haiian",
    consignee: "Sorento",
    free_days_available: 21,
    stacked: null,
    loading_date: "2026-06-20",
    etc_date: "2026-06-23",
    etd_date: "2026-06-25",
    eta_date: "2026-07-04",
    eta_delay_date: "2026-07-05",
    inspection_date: "2026-07-09",
    approval_date: "2026-07-10",
    gatepass_date: "2026-07-15",
    delivery_warehouse: null,
    warehouse_arrival_date: null,
    informed_collection_date: null,
    collection_date: null,
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Ceramic",
  },
  "CAIU7321914": {
    loc: "DC1",
    liner_code: "CMA",
    china_forwarder: "Haiian",
    malaysia_forwarder: "Haiian",
    consignee: "Sorento",
    free_days_available: 21,
    stacked: null,
    loading_date: "2026-06-20",
    etc_date: "2026-06-23",
    etd_date: "2026-06-25",
    eta_date: "2026-07-04",
    eta_delay_date: "2026-07-05",
    inspection_date: "2026-07-09",
    approval_date: "2026-07-10",
    gatepass_date: "2026-07-15",
    delivery_warehouse: null,
    warehouse_arrival_date: null,
    informed_collection_date: null,
    collection_date: null,
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Ceramic",
  },
  "UETU5190029": {
    loc: "DC1",
    liner_code: "OOCL",
    china_forwarder: "Kaidila",
    malaysia_forwarder: "MPM",
    consignee: "Sorento",
    free_days_available: 14,
    stacked: null,
    loading_date: "2026-01-01",
    etc_date: "2026-01-16",
    etd_date: "2026-01-18",
    eta_date: "2026-01-24",
    eta_delay_date: "2026-02-05",
    inspection_date: null,
    approval_date: null,
    gatepass_date: "2026-02-05",
    delivery_warehouse: null,
    warehouse_arrival_date: "2026-02-12",
    informed_collection_date: "2026-02-13",
    collection_date: "2026-02-13",
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Arrived",
  },
  "CSLU6318938": {
    loc: "BRW",
    liner_code: "OOCL",
    china_forwarder: "Onetouch",
    malaysia_forwarder: "MPM",
    consignee: "Sorento (Mocha)",
    free_days_available: 14,
    stacked: null,
    loading_date: "2026-03-23",
    etc_date: "2026-03-26",
    etd_date: "2026-03-28",
    eta_date: "2026-04-06",
    eta_delay_date: "2026-04-12",
    inspection_date: null,
    approval_date: null,
    gatepass_date: "2026-04-15",
    delivery_warehouse: null,
    warehouse_arrival_date: "2026-04-16",
    informed_collection_date: "2026-04-18",
    collection_date: "2026-04-18",
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Arrived",
  },
  "BEAU4776828": {
    loc: "BRW",
    liner_code: "CMA",
    china_forwarder: "Hongxin",
    malaysia_forwarder: "MPM",
    consignee: "Sorento (Mocha)",
    free_days_available: 14,
    stacked: null,
    loading_date: "2026-04-20",
    etc_date: "2026-04-21",
    etd_date: "2026-04-23",
    eta_date: "2026-05-04",
    eta_delay_date: "2026-05-04",
    inspection_date: null,
    approval_date: null,
    gatepass_date: "2026-05-08",
    delivery_warehouse: null,
    warehouse_arrival_date: "2026-05-09",
    informed_collection_date: "2026-05-11",
    collection_date: "2026-05-13",
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Arrived",
  },
  "BMOU5697857": {
    loc: "MWH",
    liner_code: "YML",
    china_forwarder: "Onetouch",
    malaysia_forwarder: "MPM",
    consignee: "Mocha (Sorento)",
    free_days_available: 14,
    stacked: null,
    loading_date: "2026-04-08",
    etc_date: "2026-04-10",
    etd_date: "2026-04-12",
    eta_date: "2026-04-19",
    eta_delay_date: "2026-04-20",
    inspection_date: null,
    approval_date: null,
    gatepass_date: null,
    delivery_warehouse: null,
    warehouse_arrival_date: "2026-04-21",
    informed_collection_date: "2026-04-22",
    collection_date: "2026-04-23",
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Arrived - Joint Mocha Container",
  },
  "TCNU3652081": {
    loc: "MWH",
    liner_code: "YML",
    china_forwarder: "Onetouch",
    malaysia_forwarder: "Sataka",
    consignee: "Mocha",
    free_days_available: 14,
    stacked: null,
    loading_date: "2026-06-11",
    etc_date: "2026-06-12",
    etd_date: "2026-06-14",
    eta_date: "2026-06-21",
    eta_delay_date: "2026-06-29",
    inspection_date: null,
    approval_date: null,
    gatepass_date: "2026-07-03",
    delivery_warehouse: null,
    warehouse_arrival_date: "2026-07-08",
    informed_collection_date: "2026-07-09",
    collection_date: "2026-07-09",
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Arrived - Joint Mocha Container",
  },
  "CSNU7568570": {
    loc: "MWH",
    liner_code: "OOCL",
    china_forwarder: "Onetouch",
    malaysia_forwarder: "Sataka",
    consignee: "Mocha",
    free_days_available: 14,
    stacked: null,
    loading_date: "2026-06-18",
    etc_date: "2026-06-21",
    etd_date: "2026-06-23",
    eta_date: "2026-07-02",
    eta_delay_date: "2026-07-06",
    inspection_date: null,
    approval_date: null,
    gatepass_date: null,
    delivery_warehouse: null,
    warehouse_arrival_date: "2026-07-09",
    informed_collection_date: null,
    collection_date: "2026-07-09",
    ata_date: null,
    ori_doc_received_date: null,
    k1_submission_date: null,
    yard_arrival_date: null,
    source_sheet: "Arrived - Joint Mocha Container",
  },
};

/** Normalize a container number the same way the backend matcher does. */
export function normalizeContainer(value?: string | null): string {
  return (value ?? '').toUpperCase().replace(/[^A-Z0-9]/g, '');
}

/**
 * Overlay mock clearance onto whatever the real list/detail endpoint returned.
 * A container with no mock entry keeps every clearance field undefined, which is the
 * unentitled/not-yet-imported shape - useful for eyeballing the empty states.
 */
export function withMockClearance<T extends { shipping_container_number?: string | null }>(
  row: T,
): T & ClearanceFields {
  const mock = MOCK_CLEARANCE_BY_CONTAINER[normalizeContainer(row.shipping_container_number)];
  return mock ? { ...row, ...mock } : row;
}

