"""Phase 2 RED tests - the delivered-basis sales report reply (lane SALES-REPORT, PR #1401).

`documentation/plans/chatbot/selfref-scope-acceptance-criteria.md` AC-SR-27 (the reply) and the
envelope half of AC-SR-24 / AC-SR-28 (the `options` the lane arms its open question from);
the exact reply text is the approved mock `documentation/mockups/sales-report/index.html`
(made-up names and figures).

Written BEFORE `_sales_report` / `_sales_report_envelope` read the delivered body. The bodies
under `tests/fixtures/sales_report/` are the route's new shape (`total`, `periods`, `group_by`,
`rows`, `more`, `options`); the `.txt` beside each is the bubble the mock shows, written by
hand from the mock, NOT generated by the presenter. The same bytes live under
`documentation/plans/chatbot/samples/` (the mirror test below keeps the two copies equal).

Run with `PYTHONPATH=$PWD` from `sorento_crm_mcp/` so the shared venv does not import another
checkout's package.

Ambiguities flagged to the captain, not guessed here: the DO list header ("Delivery orders,
<window>" in the mock, with no "delivery date" words, unlike a "By product" drill); how a
window-less ask prints its `*Delivery date:*`; how a one-day week/month period prints; the
`*By sales agent*` drill header (not an offered option today).
"""
from __future__ import annotations

import copy
import json
import re
from pathlib import Path

import pytest

from sorento_crm_mcp.presenters import _sales_report, _sales_report_envelope, present_response

_FIXTURES = Path(__file__).parent / "fixtures" / "sales_report"
_DOC_SAMPLES = Path(__file__).parent.parent.parent / "documentation" / "plans" / "chatbot" / "samples"

NAMES = [
    "month", "day", "week", "drill-product", "drill-do", "drill-do-multi",
    "channel-location", "miss", "refused",
]

DO_ALIASES = ["DO", "delivery order", "delivery orders"]


def _mock(name: str) -> dict:
    return json.loads((_FIXTURES / f"sales-report-{name}.json").read_text())


def _golden(name: str) -> str:
    """The mock's bubble, trailing newline stripped (the presenter never appends one)."""
    return (_FIXTURES / f"sales-report-{name}.txt").read_text().rstrip("\n")


def _envelope(name: str) -> dict:
    return json.loads(present_response("crm_sales_report", json.dumps(_mock(name))))


# ============================================================ AC-SR-27: the goldens


@pytest.mark.parametrize(
    "name",
    ["month", "day", "week", "drill-product", "drill-do", "drill-do-multi", "channel-location", "miss"],
)
def test_reply_matches_the_mock_byte_for_byte(name):
    assert _sales_report(_mock(name)) == _golden(name)


def test_default_reply_is_header_blank_total_period_lines_blank_drill_down():
    lines = _sales_report(_mock("month")).split("\n")
    assert lines == [
        "*Customer:* ACME HARDWARE SDN BHD [A/C I]",
        "*Product:* all",
        "*Delivery date:* 01/07/2026 to 30/09/2026",
        "",
        "*Total:* Qty 685, RM 58,700.00",
        "Aug 2026: Qty 640, RM 52,400.00",
        "Jul 2026: Qty 45, RM 6,300.00",
        "",
        "*Drill down:*",
        "1. By product",
        "2. Delivery orders",
    ]


def test_a_one_day_window_prints_one_date_and_day_period_lines():
    rendered = _sales_report(_mock("day"))
    assert "*Delivery date:* 30/09/2026\n" in rendered
    assert "to 30/09/2026" not in rendered
    assert "\n30/09/2026: Qty 12, RM 1,500.00\n" in rendered


def test_week_periods_print_as_dd_mm_to_dd_mm_without_the_year():
    rendered = _sales_report(_mock("week"))
    assert "24/08 to 30/08: Qty 600, RM 49,900.00" in rendered
    assert "03/08 to 09/08: Qty 3, RM 0.00" in rendered


def test_month_periods_print_as_mon_yyyy_even_when_clipped_to_the_window():
    body = copy.deepcopy(_mock("month"))
    body["periods"][1]["from"] = "2026-07-15"  # July clipped to start on the 15th
    assert "Jul 2026: Qty 45, RM 6,300.00" in _sales_report(body)


def test_periods_print_in_the_order_given_never_re_sorted():
    body = copy.deepcopy(_mock("month"))
    body["periods"].reverse()
    rendered = _sales_report(body)
    assert rendered.index("Jul 2026") < rendered.index("Aug 2026")


def test_a_drill_prints_header_rows_and_more_then_total_then_the_remaining_options():
    lines = _sales_report(_mock("drill-product")).split("\n")
    assert lines[0] == "*By product*, delivery date 01/07/2026 to 30/09/2026"
    assert lines[1] == "1. PRD-A101: Qty 12, RM 5,200.00"
    assert lines[10] == "10. PRD-E513: Qty 12, RM 1,950.00"
    assert lines[11] == "and 61 more"
    assert lines[12] == "*Total:* Qty 685, RM 58,700.00"
    assert lines[13:] == ["", "*Drill down:*", "11. Delivery orders"]


def test_and_n_more_is_absent_when_nothing_is_left_over():
    body = copy.deepcopy(_mock("drill-product"))
    body["more"] = 0
    assert "more" not in _sales_report(body)


def test_do_rows_carry_the_date_and_the_account_only_when_the_body_names_one():
    single = _sales_report(_mock("drill-do")).split("\n")
    assert single[1] == "1. DO-0824, 28/08/2026: Qty 40, RM 0.00"
    multi = _sales_report(_mock("drill-do-multi")).split("\n")
    assert multi[1] == "1. DO-0910, 15/09/2026, BETA TRADING SDN BHD: Qty 5, RM 500.00"


def test_a_customer_drill_header_names_the_view_and_the_window():
    body = copy.deepcopy(_mock("drill-product"))
    body["group_by"] = "customer"
    body["more"] = 0
    body["rows"] = body["rows"][:2]
    body["options"] = [{"key": "product", "label": "By product"}, {"key": "delivery_order", "label": "Delivery orders"}]
    lines = _sales_report(body).split("\n")
    assert lines[0] == "*By customer*, delivery date 01/07/2026 to 30/09/2026"
    assert lines[1] == "1. PRD-A101: Qty 12, RM 5,200.00"
    assert lines[-3:] == ["*Drill down:*", "3. By product", "4. Delivery orders"]


def test_channel_and_location_lines_print_between_product_and_delivery_date():
    lines = _sales_report(_mock("channel-location")).split("\n")
    assert lines[:5] == [
        "*Customer:* ACME HARDWARE SDN BHD [A/C I], BETA TRADING SDN BHD",
        "*Product:* all",
        "*Channel:* Project",
        "*Location:* WH-A",
        "*Delivery date:* 01/07/2026 to 30/09/2026",
    ]


@pytest.mark.parametrize(
    "channel,shown,expected",
    [
        (None, True, "*Channel:* all"),
        ("project", True, "*Channel:* Project"),
        ("retail", True, "*Channel:* Retail"),
        ("project", False, None),
        (None, False, None),
    ],
)
def test_the_channel_line_prints_only_when_channel_shown(channel, shown, expected):
    body = copy.deepcopy(_mock("month"))
    body["channel"], body["channel_shown"] = channel, shown
    rendered = _sales_report(body)
    if expected is None:
        assert "*Channel:*" not in rendered
    else:
        assert expected + "\n" in rendered


def test_the_location_line_prints_only_when_a_location_was_named():
    body = copy.deepcopy(_mock("month"))
    assert "*Location:*" not in _sales_report(body)
    body["location_token"], body["warehouse_codes"] = "IB", ["BRW-IB", "MWH-IB"]
    assert "*Location:* IB (BRW-IB, MWH-IB)\n" in _sales_report(body)
    body["location_token"], body["warehouse_codes"] = "BRW-IB", ["BRW-IB"]
    rendered = _sales_report(body)
    assert "*Location:* BRW-IB\n" in rendered
    assert "BRW-IB (BRW-IB)" not in rendered


@pytest.mark.parametrize(
    "product_code,product_codes,expected",
    [
        (None, [], "all"),
        ("SRT5674", ["SRT5674"], "SRT5674"),
        ("SRT5674", ["SRT5674", "SRT5674-N"], "SRT5674, SRT5674-N"),
        ("SRT56", [f"SRT56{i:02d}" for i in range(11)], "SRT56 (11 products)"),
    ],
)
def test_the_product_line_keeps_the_existing_family_rule(product_code, product_codes, expected):
    body = copy.deepcopy(_mock("month"))
    body["product_code"], body["product_codes"] = product_code, product_codes
    assert f"*Product:* {expected}\n" in _sales_report(body)


def test_no_periods_prints_the_header_a_blank_line_and_no_sales_found_and_nothing_else():
    rendered = _sales_report(_mock("miss"))
    assert rendered == (
        "*Customer:* ACME HARDWARE SDN BHD [A/C I]\n"
        "*Product:* all\n"
        "*Delivery date:* 01/09/2026 to 30/09/2026\n"
        "\n"
        "No sales found."
    )
    assert "*Total:*" not in rendered and "*Drill down:*" not in rendered


def test_thousands_and_two_decimals_on_every_money_figure():
    body = copy.deepcopy(_mock("month"))
    body["total"] = {"qty": 1234, "amount": 1234567.5}
    body["periods"] = [{"from": "2026-08-01", "to": "2026-08-31", "qty": 1234, "amount": 1234567.5}]
    rendered = _sales_report(body)
    assert "*Total:* Qty 1,234, RM 1,234,567.50" in rendered
    assert "Aug 2026: Qty 1,234, RM 1,234,567.50" in rendered


# ============================================================ envelope: options for the lane


def test_envelope_default_options_number_from_one_with_their_aliases():
    env = _envelope("month")
    assert env["result_type"] == "sales_report", env
    assert env["response"] == _golden("month"), env
    assert env["has_result"] is True, env
    assert env["options"] == [
        {"idx": 1, "label": "By product", "value": "product", "aliases": ["by product"]},
        {"idx": 2, "label": "Delivery orders", "value": "delivery_order", "aliases": DO_ALIASES},
    ], env["options"]


def test_envelope_option_numbers_continue_after_the_rows_printed():
    env = _envelope("drill-product")
    assert env["options"] == [
        {"idx": 11, "label": "Delivery orders", "value": "delivery_order", "aliases": DO_ALIASES},
    ], env["options"]
    do_env = _envelope("drill-do")
    assert do_env["options"] == [
        {"idx": 11, "label": "By product", "value": "product", "aliases": ["by product"]},
    ], do_env["options"]


def test_envelope_numbering_follows_the_rows_actually_printed_not_ten():
    """Two rows printed, so the options are 3 and 4."""
    env = _envelope("drill-do-multi")
    assert [(o["idx"], o["value"]) for o in env["options"]] == [(3, "customer"), (4, "product")], env
    by_customer = env["options"][0]
    assert by_customer == {"idx": 3, "label": "By customer", "value": "customer", "aliases": ["by customer"]}


def test_envelope_options_carry_the_same_numbers_the_text_prints():
    for name in ("month", "drill-product", "drill-do", "drill-do-multi", "channel-location"):
        env = _envelope(name)
        for option in env["options"]:
            assert f"{option['idx']}. {option['label']}" in env["response"], (name, option)


def test_a_miss_has_no_options_and_is_not_a_result():
    env = _envelope("miss")
    assert env["result_type"] == "sales_report", env
    assert env["has_result"] is False, env
    assert env["options"] == [], env
    assert env["response"] == _golden("miss"), env


def test_a_refused_body_answers_with_the_message_and_arms_nothing():
    env = _envelope("refused")
    assert env["response"] == "Sorry, REPAIR isn't one of the locations you can check.", env
    assert env["has_result"] is True, "a refusal is a final answer, never the miss lane's escalate offer"
    assert env["options"] == [], env


def test_the_envelope_function_and_present_response_agree():
    for name in NAMES:
        assert _sales_report_envelope(_mock(name)) == _envelope(name), name


def test_a_body_without_options_yields_an_empty_option_list_not_a_crash():
    body = copy.deepcopy(_mock("month"))
    del body["options"]
    assert _sales_report_envelope(body)["options"] == []


# ============================================================ the retired shape is gone


def test_the_retired_reply_text_is_never_produced():
    for name in NAMES:
        text = _sales_report(_mock(name))
        for retired in ("Reply 1 for the sales order list", "*SO Number:*", "*_By product_*",
                        "Required date (or order date)", "Confirmed (DO)", "Outstanding:"):
            assert retired not in text, (name, retired)


# ============================================================ dash guard and mirror

_BANNED = ("\u2014", "\u2013", "\u2192", "->", "=>")


@pytest.mark.parametrize("name", NAMES)
def test_no_dashes_in_any_golden(name):
    text = _golden(name)
    for banned in _BANNED:
        assert banned not in text, f"{name} carries a banned character/sequence: {banned!r}"
    assert not re.search(r"-{2,}", text)


def test_documentation_samples_mirror_the_fixtures():
    if not _DOC_SAMPLES.exists():
        pytest.skip("documentation/ not present in this environment (CI mcp test container)")
    for path in _FIXTURES.iterdir():
        mirror = _DOC_SAMPLES / path.name
        assert mirror.exists(), f"{path.name} has no documentation/ mirror"
        assert mirror.read_bytes() == path.read_bytes(), f"{path.name} has drifted from its mirror"
