/**
 * PHASE 1 FIXTURE. Deleted when `chatbotTurnService` is pointed at the real endpoint.
 *
 * Six turns, chosen to cover every shape the screen has to render rather than to look
 * tidy: an answered business query, an escalation, a clarify ask, a failure at
 * `understood` on its second attempt, a turn still delegated to n8n, and a duplicate
 * delivery. Between them they exercise both tones, the collapsed "not reached" row, an
 * empty `facts`, a null `response`, and an `attempt` above 1.
 *
 * The sentences are written the way the ENGINE writes them (D11: composed from structured
 * state, never from the customer's words), so what is being reviewed here is the real
 * wording, not lorem standing in for it.
 */
import type { ChatbotTurn } from '../types/chatbotTurn.types';

/** Anchored so the relative times in the trace read sensibly against each other. */
const BASE = Date.parse('2026-09-05T06:02:03.000Z'); // 14:02:03 Malaysia

function at(offsetSeconds: number): string {
  return new Date(BASE + offsetSeconds * 1000).toISOString();
}

export const MOCK_TURNS: ChatbotTurn[] = [
  // 1. Answered: the happy path, every stage present.
  {
    id: '8f2c41d6-0b7a-4d33-9c2e-11ab5f0e7a10',
    contact_respond_id: '900000009',
    message_id: 'wamid.mock.0001',
    status: 'done',
    stage: 'sent',
    branch_kind: 'business_query',
    attempt: 1,
    is_test: false,
    created_at: at(0),
    finished_at: at(4.1),
    response: { reply: { text: 'SRTWC8517 Sorento WC-8517: 12 pcs on hand.' } },
    trace: [
      {
        stage: 'received',
        status: 'ok',
        started_at: at(0),
        ms: 0,
        summary: 'Received a text message with no attachment.',
        why: 'Every turn starts from what the bot remembered about this contact.',
        facts: { remembered: '9 keys', quoted: 'no' },
        error: null,
        raw: { message: { type: 'text' }, session_vars: { variables: { entities: [] } } },
      },
      {
        stage: 'understood',
        status: 'ok',
        started_at: at(0.1),
        ms: 2310,
        summary: 'Understood as a business query about stock for product SRTWC8517, dealer tier.',
        why: 'The parser is the only step that reads the customer words; everything after it works on structured state.',
        facts: { model: 'gpt-5.4-mini', prompt: 'chatbot_semantic_parser v3', entities: 2 },
        error: null,
        raw: {
          parser_raw: { message_type: 'business_query', domain_hint: 'inventory' },
          derived: { access_levels: ['dealer'], query_brands: ['sorento'] },
        },
      },
      {
        stage: 'access',
        status: 'ok',
        started_at: at(2.4),
        ms: 40,
        summary: 'Access allowed for General Enquiries.',
        why: 'The contact must be granted the agent this turn would use before anything is looked up.',
        facts: { agent: 'general_enquiries', decision: 'allow' },
        error: null,
        raw: { allowed: true, decision: 'allow', agent_name: 'General Enquiries' },
      },
      {
        stage: 'routed',
        status: 'ok',
        started_at: at(2.45),
        ms: 1,
        summary: 'Routed to the business query: inventory.',
        why: 'Routed to the business lane: access allowed, no escalation asked.',
        facts: { lane: 'business_query' },
        error: null,
        raw: { item: { branch_kind: 'business_query', allowed: true } },
      },
      {
        stage: 'looked_up',
        status: 'ok',
        started_at: at(2.46),
        ms: 1400,
        summary: 'SRTWC8517 resolved to Sorento WC-8517. One row: 12 pcs on hand, 300 arriving 12 Oct.',
        why: 'Incoming stock was probed as well because the quantity asked for is more than the balance.',
        facts: {
          resolver: 'exact code match, 1 candidate',
          tool: 'crm_inventory_stock_balance_list',
          similarity: 0.81,
        },
        error: null,
        raw: {
          tool: 'crm_inventory_stock_balance_list',
          args: { product_ids: ['1f3e...'], warehouse: null },
          rows: 1,
        },
      },
      {
        stage: 'replied',
        status: 'ok',
        started_at: at(3.9),
        ms: 3,
        summary: 'Composed a stock answer with an incoming-stock note, one message part.',
        why: 'The answer text is assembled from the rows that were read, not written by a model.',
        facts: { parts: 1, quick_replies: 0 },
        error: null,
        raw: { reply: { text: 'SRTWC8517 Sorento WC-8517: 12 pcs on hand.' } },
      },
      {
        stage: 'remembered',
        status: 'ok',
        started_at: at(3.91),
        ms: 2,
        summary: 'Saved what the next turn will know.',
        why: 'A follow-up like "and the price?" is answered from this, so it is what a wrong follow-up is traced to.',
        facts: {},
        error: null,
        raw: {
          before: {
            entities: [{ raw: 'SRTWC8517', hint: 'product' }],
            access_levels: ['dealer'],
            dym_offer: { candidates: [{ code: 'SRTWC8157' }] },
          },
          after: {
            entities: [{ raw: 'SRTWC8517', hint: 'product' }],
            access_levels: ['dealer'],
            last_result_set: [{ idx: 1, label: 'Sorento WC-8517' }],
            dym_offer: null,
          },
        },
      },
      {
        stage: 'sent',
        status: 'ok',
        started_at: at(3.92),
        ms: 320,
        summary: 'Delivered one WhatsApp message.',
        why: 'Sending stays with the caller; the CRM returns the message and n8n sends it.',
        facts: { channel: 'whatsapp', delivered_at: '14:02:07' },
        error: null,
        raw: { actions: [{ kind: 'send_message' }] },
      },
    ],
  },

  // 2. Escalated: no lookup at all, so `looked_up` is simply absent from the trace.
  {
    id: '3b91ee02-7c45-49aa-8d0f-2c7719ab4e51',
    contact_respond_id: '900000009',
    message_id: 'wamid.mock.0002',
    status: 'done',
    stage: 'sent',
    branch_kind: 'out_of_scope',
    attempt: 1,
    is_test: false,
    created_at: at(240),
    finished_at: at(242.6),
    response: { reply: { text: 'I have passed this to Customer Service.' } },
    trace: [
      {
        stage: 'received',
        status: 'ok',
        started_at: at(240),
        ms: 0,
        summary: 'Received a text message with no attachment.',
        why: 'Every turn starts from what the bot remembered about this contact.',
        facts: { remembered: '11 keys' },
        error: null,
        raw: { message: { type: 'text' } },
      },
      {
        stage: 'understood',
        status: 'ok',
        started_at: at(240.1),
        ms: 1900,
        summary: 'Understood as a request for help, no domain named.',
        why: 'The customer asked for a person rather than for data.',
        facts: { model: 'gpt-5.4-mini', team_named: 'no' },
        error: null,
        raw: { parser_raw: { message_type: 'request_for_help' } },
      },
      {
        stage: 'access',
        status: 'ok',
        started_at: at(242),
        ms: 38,
        summary: 'Access allowed for Order Enquiries.',
        why: 'The contact must be granted the agent this turn would use before anything is looked up.',
        facts: { agent: 'order_enquiries', decision: 'allow' },
        error: null,
        raw: { allowed: true },
      },
      {
        stage: 'routed',
        status: 'ok',
        started_at: at(242.05),
        ms: 1,
        summary: 'Routed to escalation.',
        why: 'Routed to escalation: the customer asked for a person or accepted the offer.',
        facts: { lane: 'out_of_scope', team: 'customer_service' },
        error: null,
        raw: { item: { branch_kind: 'out_of_scope' } },
      },
      {
        stage: 'replied',
        status: 'ok',
        started_at: at(242.1),
        ms: 4,
        summary: 'Composed the hand-off acknowledgement and the PIC comment.',
        why: 'The assignment itself is an action the caller executes, not something the CRM sends.',
        facts: { assignee: 'Nur Aisyah', actions: 4 },
        error: null,
        raw: { actions: [{ kind: 'assign_conversation' }, { kind: 'add_comment' }] },
      },
      {
        stage: 'remembered',
        status: 'ok',
        started_at: at(242.15),
        ms: 2,
        summary: 'Saved what the next turn will know.',
        why: 'A follow-up like "and the price?" is answered from this, so it is what a wrong follow-up is traced to.',
        facts: {},
        error: null,
        raw: {
          before: { domain_hint: 'order', routing: { suggested_team: 'customer_service' } },
          after: {
            domain_hint: 'order',
            routing: { suggested_team: 'customer_service' },
            escalation: { is_escalation_confirmation: true },
          },
        },
      },
      {
        stage: 'sent',
        status: 'ok',
        started_at: at(242.2),
        ms: 410,
        summary: 'Delivered two WhatsApp messages and assigned the conversation.',
        why: 'Sending stays with the caller; the CRM returns the message and n8n sends it.',
        facts: { channel: 'whatsapp', assigned_to: 'Nur Aisyah' },
        error: null,
        raw: { actions: [{ kind: 'send_message' }, { kind: 'assign_conversation' }] },
      },
    ],
  },

  // 3. Asked to clarify: a TAG-ONLY arm, so the trace is short by design.
  {
    id: 'c40a7715-9d2b-4f8e-b6a1-88ee01f2c937',
    contact_respond_id: '900000009',
    message_id: 'wamid.mock.0003',
    status: 'done',
    stage: 'sent',
    branch_kind: 'clarify_menu',
    attempt: 1,
    is_test: false,
    created_at: at(600),
    finished_at: at(602.2),
    response: { reply: { text: 'Is this about an order, stock, a product, or a promotion?' } },
    trace: [
      {
        stage: 'received',
        status: 'ok',
        started_at: at(600),
        ms: 0,
        summary: 'Received a text message with no attachment.',
        why: 'Every turn starts from what the bot remembered about this contact.',
        facts: { remembered: '4 keys' },
        error: null,
        raw: { message: { type: 'text' } },
      },
      {
        stage: 'understood',
        status: 'ok',
        started_at: at(600.1),
        ms: 1700,
        summary: 'Understood as a clarification with no domain and no entities.',
        why: 'The parser is the only step that reads the customer words; everything after it works on structured state.',
        facts: { model: 'gpt-5.4-mini', entities: 0 },
        error: null,
        raw: { parser_raw: { message_type: 'clarification', domain_hint: null } },
      },
      {
        stage: 'access',
        status: 'ok',
        started_at: at(601.8),
        ms: 35,
        summary: 'Access allowed for General Enquiries.',
        why: 'The contact must be granted the agent this turn would use before anything is looked up.',
        facts: { agent: 'general_enquiries', decision: 'allow' },
        error: null,
        raw: { allowed: true },
      },
      {
        stage: 'routed',
        status: 'ok',
        started_at: at(601.85),
        ms: 1,
        summary: 'Routed to the clarify menu.',
        why: 'Routed to the clarify menu: the turn was understood as a clarification.',
        facts: { lane: 'clarify_menu' },
        error: null,
        raw: { item: { branch_kind: 'clarify_menu' } },
      },
      {
        stage: 'replied',
        status: 'ok',
        started_at: at(601.9),
        ms: 2,
        summary: 'Sent the standing clarify menu with four quick replies.',
        why: 'The wording comes from the prompt registry, so it can be edited without a deploy.',
        facts: { quick_replies: 4, copy_key: 'chatbot_reply_clarify_menu' },
        error: null,
        raw: { reply: { quick_replies: ['Order', 'Stock', 'Product', 'Promotion'] } },
      },
      {
        stage: 'remembered',
        status: 'ok',
        started_at: at(601.95),
        ms: 1,
        summary: 'Saved what the next turn will know.',
        why: 'A follow-up like "and the price?" is answered from this, so it is what a wrong follow-up is traced to.',
        facts: {},
        error: null,
        raw: {
          before: { domain_hint: 'promotion', last_result_set: [{ idx: 1 }] },
          after: { pending: { kind: 'team_clarify' }, last_result_set: [{ idx: 1 }] },
        },
      },
      {
        stage: 'sent',
        status: 'ok',
        started_at: at(602),
        ms: 190,
        summary: 'Delivered one WhatsApp message.',
        why: 'Sending stays with the caller; the CRM returns the message and n8n sends it.',
        facts: { channel: 'whatsapp' },
        error: null,
        raw: { actions: [{ kind: 'send_message' }] },
      },
    ],
  },

  // 4. Failed at `understood`, second attempt. The Retry button's only enabled case.
  {
    id: '9a10bf83-2e64-4c19-a7d5-5b0c33e19d84',
    contact_respond_id: '900000009',
    message_id: 'wamid.mock.0004',
    status: 'failed',
    stage: 'understood',
    branch_kind: null,
    attempt: 2,
    is_test: false,
    created_at: at(900),
    finished_at: at(909.8),
    response: null,
    trace: [
      {
        stage: 'received',
        status: 'ok',
        started_at: at(900),
        ms: 0,
        summary: 'Received a text message with no attachment.',
        why: 'Every turn starts from what the bot remembered about this contact.',
        facts: { remembered: '9 keys' },
        error: null,
        raw: { message: { type: 'text' } },
      },
      {
        stage: 'understood',
        status: 'failed',
        started_at: at(900.1),
        ms: 9700,
        summary: 'Could not understand the message.',
        why: 'The parser did not return a usable answer, so the turn was not routed.',
        facts: { model: 'gpt-5.4-mini', prompt: 'chatbot_semantic_parser v3', attempt: 2 },
        error:
          'The language model did not answer in time, and the customer was sent the standard try-again reply.',
        raw: {
          stage: 'understood',
          error: 'ReadTimeout: openai chat 8000ms',
          attempt: 2,
          prompt: 'chatbot_semantic_parser@v3',
        },
      },
      {
        stage: 'sent',
        status: 'ok',
        started_at: at(909.6),
        ms: 210,
        summary: 'Delivered the error reply.',
        why: 'A failed turn still answers the customer; it is recorded here rather than dropped.',
        facts: { channel: 'whatsapp', delivered_at: '14:05:51' },
        error: null,
        raw: { actions: [{ kind: 'send_message' }] },
      },
    ],
  },

  // 5. Still with n8n: the head decided, the lane has not answered yet.
  {
    id: '2d77c0ba-4a18-4de6-9f31-7ac6b2e50f19',
    contact_respond_id: '900000009',
    message_id: 'wamid.mock.0005',
    status: 'delegated',
    stage: 'routed',
    branch_kind: 'check_promotion',
    attempt: 1,
    is_test: false,
    created_at: at(1200),
    finished_at: at(1202.4),
    response: { item: { branch_kind: 'check_promotion' } },
    trace: [
      {
        stage: 'received',
        status: 'ok',
        started_at: at(1200),
        ms: 0,
        summary: 'Received a text message with no attachment.',
        why: 'Every turn starts from what the bot remembered about this contact.',
        facts: { remembered: '12 keys' },
        error: null,
        raw: { message: { type: 'text' } },
      },
      {
        stage: 'understood',
        status: 'ok',
        started_at: at(1200.1),
        ms: 2100,
        summary: 'Understood as a business query about promotion, dealer tier.',
        why: 'The parser is the only step that reads the customer words; everything after it works on structured state.',
        facts: { model: 'gpt-5.4-mini', tier: 'dealer' },
        error: null,
        raw: { parser_raw: { domain_hint: 'promotion' } },
      },
      {
        stage: 'access',
        status: 'ok',
        started_at: at(1202.2),
        ms: 41,
        summary: 'Access allowed for General Enquiries.',
        why: 'The contact must be granted the agent this turn would use before anything is looked up.',
        facts: { agent: 'general_enquiries', decision: 'allow' },
        error: null,
        raw: { allowed: true },
      },
      {
        stage: 'routed',
        status: 'ok',
        started_at: at(1202.3),
        ms: 1,
        summary: 'Routed to the business query: promotion.',
        why: 'Routed to the business lane: access allowed, no escalation asked.',
        facts: { lane: 'check_promotion', handled_by: 'n8n promotion lane' },
        error: null,
        raw: { item: { branch_kind: 'check_promotion' } },
      },
    ],
  },

  // 6. A duplicate delivery: the webhook and the failover poller both posted this message.
  {
    id: '61f0d24c-8b93-4a77-8e02-9de41c7b3355',
    contact_respond_id: '900000009',
    message_id: 'wamid.mock.0006',
    status: 'done',
    stage: 'sent',
    branch_kind: 'low_signal',
    attempt: 1,
    is_test: false,
    duplicate: true,
    created_at: at(1500),
    finished_at: at(1503.1),
    response: { reply: { text: 'Happy to help. What can I look up for you?' } },
    trace: [
      {
        stage: 'received',
        status: 'ok',
        started_at: at(1500),
        ms: 0,
        summary: 'Received a text message that had already been answered.',
        why: 'The webhook and the failover poller both delivered it, so the second delivery was not answered again.',
        facts: { ingress: 'poller', duplicate_of: '61f0d24c' },
        error: null,
        raw: { duplicate: true, ingress: 'poller' },
      },
      {
        stage: 'understood',
        status: 'ok',
        started_at: at(1500.1),
        ms: 1600,
        summary: 'Understood as small talk with no domain.',
        why: 'The parser is the only step that reads the customer words; everything after it works on structured state.',
        facts: { model: 'gpt-5.4-mini' },
        error: null,
        raw: { parser_raw: { message_type: 'casual' } },
      },
      {
        stage: 'access',
        status: 'ok',
        started_at: at(1501.8),
        ms: 36,
        summary: 'Access allowed for General Enquiries.',
        why: 'The contact must be granted the agent this turn would use before anything is looked up.',
        facts: { agent: 'general_enquiries', decision: 'allow' },
        error: null,
        raw: { allowed: true },
      },
      {
        stage: 'routed',
        status: 'ok',
        started_at: at(1501.9),
        ms: 1,
        summary: 'Routed to small talk.',
        why: 'Routed to small talk: no domain and no decisive intent were understood.',
        facts: { lane: 'low_signal' },
        error: null,
        raw: { item: { branch_kind: 'low_signal' } },
      },
      {
        stage: 'replied',
        status: 'ok',
        started_at: at(1502),
        ms: 900,
        summary: 'Composed a short reply and an invitation to ask something specific.',
        why: 'Small talk is the one lane besides understanding that calls a model.',
        facts: { model: 'gpt-4.1-mini' },
        error: null,
        raw: { reply: { text: 'Happy to help.' } },
      },
      {
        stage: 'remembered',
        status: 'ok',
        started_at: at(1502.9),
        ms: 1,
        summary: 'Saved what the next turn will know.',
        why: 'A follow-up like "and the price?" is answered from this, so it is what a wrong follow-up is traced to.',
        facts: {},
        error: null,
        raw: {
          before: { domain_hint: 'inventory' },
          after: { domain_hint: 'inventory' },
        },
      },
      {
        stage: 'sent',
        status: 'ok',
        started_at: at(1503),
        ms: 180,
        summary: 'Nothing was sent: this delivery was a repeat.',
        why: 'The caller checks the duplicate flag and sends nothing, so the customer sees one reply.',
        facts: { channel: 'whatsapp', sent: 'no' },
        error: null,
        raw: { duplicate: true, actions: [] },
      },
    ],
  },
];
